(function(root,factory){const node=typeof module==='object'&&module.exports;const api=factory(node?require('./spec'):root.CircuitTaskSpec,node?require('../circuit-workbench/circuit-model'):root.CircuitModel,node?require('../circuit-workbench/circuit-profile'):root.CircuitProfile,node?require('../circuit-workbench/circuit-activity-data'):root.CircuitActivityData);if(node)module.exports=api;else root.CircuitTaskPersistence=api;})(globalThis,function(Q,M,F,A){
'use strict';
const profile=F.compile(Q.config()),fresh=()=>({revision:1,phase:'edit',question:0,answers:Array.from({length:2},()=>({position:null,reason:null,view:0}))});
function validate(s){A.keys(s,['revision','phase','question','answers']);if(s.revision!==1||!['edit','check'].includes(s.phase)||!Number.isInteger(s.question)||s.question<0||s.question>1||!Array.isArray(s.answers)||s.answers.length!==2)throw new Error('調參作答無效');for(const a of s.answers){A.keys(a,['position','reason','view']);if(a.position!==null&&(!Number.isFinite(a.position)||a.position<0||a.position>1)||![null,-1,1].includes(a.reason)||![0,1].includes(a.view))throw new Error('調參答案無效');}return M.clone(s);}
function document(s){s=validate(s);const d=M.clone(profile.initial),a=s.answers[s.question];d.components.find(c=>c.id==='c3').params.position=a.position??.5;d.display.view=a.view?'schematic':'real';return profile.assertSnapshot(d);}
function capture(input,s){const d=profile.assertSnapshot(input),old=document(s);s=validate(s);const p=d.components.find(c=>c.id==='c3').params.position;if(p!==old.components.find(c=>c.id==='c3').params.position)s.answers[s.question].position=p;s.answers[s.question].view=d.display.view==='schematic'?1:0;return validate(s);}
function decode(x,kind){A.envelope(x,Q.ACTIVITY,kind);const s=validate(x.answer);if(kind==='review'&&s.phase!=='check')throw new Error('提交階段無效');return s;}
return {ACTIVITY:Q.ACTIVITY,fresh,document,capture,validate,draft:validate,review:s=>validate({...s,phase:'check'}),decode,bytes:A.bytes};
});
