'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),M=require('./circuit-model'),F=require('./circuit-profile'),P=require('./circuit-ac-presets'),T=require('./circuit-transient'),AC=require('./circuit-ac-components'),D=require('./circuit-document'),Data=require('../circuit-ac-workbench/example-state');
for(const name of Object.keys(P.names)){const d=P.create(name),s=new T.Session(d);assert.deepEqual(D.decode(D.encode(d)),d);s.advance(.0123456789);assert.equal(s.fault,null,name);const saved=s.capture(),restored=T.Session.restore(JSON.parse(JSON.stringify(saved)));restored.advance(.00123);s.advance(.00123);assert.equal(restored.fault,null,name);assert.ok(Math.abs(restored.state.time-s.state.time)<1e-10);assert.deepEqual(restored.doc,s.doc);}
for(const name of ['transformer','lc']){const config=P.examples(name),profile=F.compile(config),d=M.clone(profile.initial);assert.equal(profile.analysis,'transient');assert.equal(profile.wires,false);assert.equal(profile.simulation.reset,false);assert.equal(profile.simulation.rate,false);
  for(const mutate of [x=>x.wires.pop(),x=>x.components[0].params.voltage++,x=>x.components[0].x++,x=>x.components[0].label='偽造',x=>x.components[0].locked=true,x=>M.add(x,'resistor',0,0),x=>{x.version=6;delete x.analysis;delete x.modelRevision;}]){const bad=M.clone(d);mutate(bad);assert.throws(()=>profile.assertSnapshot(bad));}
  const component=d.components.find(c=>c.type===(name==='transformer'?'transformer':'spdt'));component.params[name==='transformer'?'secondaryTurns':'closed']=name==='transformer'?150:'c';profile.assertSnapshot(d);const session=new T.Session(d);session.advance(.013456789012345);const encoded=Data.encode(name,session.capture()),decoded=Data.decode(encoded);assert.deepEqual(decoded.document,session.doc);const restored=T.Session.restore(decoded);restored.advance(.009);assert.equal(restored.fault,null);
  const window={location:{},addEventListener(){}};window.parent=window;window.top=window;vm.runInNewContext(fs.readFileSync(require.resolve('../shared/scorm'),'utf8'),{window,console,TextEncoder,setTimeout,clearTimeout});const answer=JSON.parse(encoded),draft=window.SimScorm.makeSnapshot('ac-capacity-'+name,'draft',answer),review=window.SimScorm.makeSnapshot('ac-capacity-'+name,'review',answer,{score:0,passed:false}),pending={version:1,activity:'ac-capacity-'+name,kind:'pending-final',payload:{reviewJson:JSON.stringify(review),score:0,maxScore:100,passed:false}};const sizes=[draft,review,pending].map(Data.bytes);sizes.forEach(n=>assert(n<=4000));console.log(name+' technical codec draft/review/pending-envelope bytes: '+sizes.join('/'));
  for(const mutate of [x=>x.version++,x=>x.model++,x=>x.extra=true,x=>x.parameters.push(1),x=>x.physics.sources.bad=0,x=>x.physics.time=-1]){const bad=JSON.parse(encoded);mutate(bad);assert.throws(()=>Data.decode(bad));}
}
{const s=new T.Session(P.create('lc'));s.advance(.037);const before=s.capture(),preview=M.clone(s.doc);preview.components.find(c=>c.type==='capacitor').params.capacitance*=2;s.preview(preview);assert.deepEqual(s.capture(),before);const moved=M.clone(s.doc);moved.components[0].label='換名';s.update(moved);assert.deepEqual(s.state,before.physics);const after=s.capture();assert.equal(after.document.components[0].label,'換名');const readonlyDocument=F.compile({role:'teacher'});assert.throws(()=>readonlyDocument.assertSnapshot(s.doc));assert.throws(()=>F.compile({analysis:'dc',initialDocument:s.doc}));}
{const palette=F.compile({analysis:'transient',palette:[{type:'capacitor',limit:1}],components:{default:{move:true,remove:true,params:['capacitance']}},ui:{palette:true}}),d=M.clone(palette.initial);M.add(d,'capacitor',100,100);palette.assertSnapshot(d);assert.equal(palette.canAdd(palette.palette[0],d),false);M.add(d,'capacitor',300,100);assert.throws(()=>palette.assertSnapshot(d));assert.throws(()=>F.compile({analysis:'transient',palette:[{type:'relay'}]}));assert.throws(()=>AC.toAC({...M.empty(),components:[M.component(M.empty(),'lamp',0,0,{model:'thermal'})]}));}
console.log('AC profiles, every preset session continuation, production example codec, capacity and invalid-state checks passed');
for(const name of ['transformer','lc']){const config=P.examples(name),session=new T.Session(config.initialDocument),snapshots=[session.capture()];if(name==='transformer'){const d=M.clone(session.doc);d.components.find(c=>c.type==='transformer').params.secondaryTurns=2000;d.components.find(c=>c.label==='負載電阻').params.resistance=.01;session.update(d);session.advance(.01345678912345);snapshots.push(session.capture());}else{session.advance(.007123456789);snapshots.push(session.capture());session.advance(.1-session.state.time);snapshots.push(session.capture());const d=M.clone(session.doc);d.components.find(c=>c.type==='spdt').params.closed='c';session.update(d);snapshots.push(session.capture());session.advance(session.compiled.period/4);snapshots.push(session.capture());session.advance(session.compiled.period/4);snapshots.push(session.capture());}
 let worst=0;for(const snapshot of snapshots){const encoded=Data.encode(name,snapshot),resumed=T.Session.restore(Data.decode(encoded));worst=Math.max(worst,Data.bytes(encoded));assert.deepEqual(resumed.state,snapshot.physics);resumed.advance(.000123);assert.equal(resumed.fault,null);const review={version:1,activity:'ac-capacity-'+name,kind:'review',answer:JSON.parse(encoded),score:0,passed:false},pending={version:1,activity:'ac-capacity-'+name,kind:'pending-final',payload:{reviewJson:JSON.stringify(review),score:0,maxScore:100,passed:false}};assert(Data.bytes(pending)<4000);}
 console.log(name+' production phase variants '+snapshots.length+'; largest compact session '+worst+' bytes');}

// The actual renderer changes view without changing terminals or simulation state.
{const R=require('./component-registry'),V=require('./circuit-renderer');for(const type of Object.keys(AC.types)){const c=M.component(M.empty('transient'),type,160,200),r={reading:1,current:.01,phase:.7};const real=V.body(c,r,{view:'real',values:true}),symbol=V.body(c,r,{view:'schematic',values:true});assert(real.includes('data-ac-view="real"'));assert(symbol.includes('data-ac-view="schematic"'));assert.notEqual(real.replace(/data-ac-view="[^"]*"/,''),symbol.replace(/data-ac-view="[^"]*"/,''),type);for(const angle of [0,90,180,270]){c.angle=angle;const bounds=R.bodyBounds(c);assert(bounds.right>bounds.left&&bounds.bottom>bounds.top);assert.equal(R.ports(c).length,AC.types[type].ports.length);}}}
// Lamp visuals follow solved power: an ordinary 50 Hz lamp is stable, a low-frequency lamp varies.
{const V=require('./circuit-renderer');function light(voltage,frequency,time){const d=P.create('resistive');d.components.find(c=>c.type==='ac-source').params.voltage=voltage;d.components.find(c=>c.type==='ac-source').params.frequency=frequency;const s=new T.Session(d);s.advance(time);assert.equal(s.fault,null);const lamp=d.components.find(c=>c.type==='lamp');return V.lampLight(lamp,s.read().components[lamp.id]);}const dim=light(3,50,.055),bright=light(6,50,.055);assert(bright.brightness>dim.brightness);assert(Math.abs(bright.power/ dim.power-4)<.02);assert(Math.abs(bright.brightness-light(6,50,.060).brightness)<.005);assert(light(6,1,.26).brightness>light(6,1,.51).brightness+.3);assert.equal(light(0,50,.05).brightness,0);}
console.log('AC apparatus/symbol rendering, unchanged ports and solved lamp brightness passed');

{const R=require('./component-registry'),V=require('./circuit-renderer'),d=P.create('resistive'),source=d.components[0];assert.equal(source.params.frequency,1);assert.equal(P.create('mains').components[0].params.frequency,50);assert.equal(P.rate('lc'),1);source.params.frequency=2;assert.equal(R.stepPrimaryParameter(source,1),50);source.params.frequency=50;assert.equal(R.stepPrimaryParameter(source,-1),2);const profile=F.compile({role:'teacher',analysis:'transient',palette:AC.palette,initialDocument:d}),bad=M.clone(d);bad.components[0].params.frequency=3;assert.throws(()=>profile.assertTransition(d,bad));const options={wireCurrents:new Set(d.wires.map(w=>w.id))},widths=[];for(const current of [0,1e-100,1e-9,.0009,.1,-.2597,10,1e100,null]){const r=new T.Session(d).read();r.wires=Object.fromEntries(d.wires.map(w=>[w.id,{...r.wires[w.id],current}]));const labels=V.labels(d,r,1,{},null,options).filter(p=>p.rows[0].kind==='wireCurrent');widths.push(labels[0].box.right-labels[0].box.left);assert(labels[0].rows[0].text.includes(current===null?'未能確定':'mA'));}assert(Math.max(...widths)-Math.min(...widths)<1e-9);assert(widths.every(width=>width<145),'compact current cards should not reserve 178 px');}
console.log('AC low-frequency controls, 50 Hz option and stable current label widths passed');

{const s=new T.Session(P.create('mains'));for(let n=0;n<120;n++){s.advance(1/60);if(n>2){const lamp=s.read().components.c3;assert(Number.isFinite(lamp.displayPower),'50 Hz rolling-window bins must stay complete across floating-point boundaries');assert(Math.abs(lamp.displayPower-3)<.015);}}}
console.log('50 Hz display power stays available and stable across 120 frame boundaries');

// Authored compact diagrams retain usable body separation and correctly attached finite cables.
{const R=require('./component-registry'),G=require('./circuit-routing');for(const name of Object.keys(P.names)){const d=P.create(name),ports=M.endpoints(d);for(let i=0;i<d.components.length;i++)for(const c of d.components.slice(i+1)){const a=R.bodyBounds(d.components[i]),b=R.bodyBounds(c);assert(a.right<=b.left||b.right<=a.left||a.bottom<=b.top||b.bottom<=a.top,name+' body overlap');}for(const w of d.wires){const points=G.route(d,w);assert(G.length(points)<=w.length+.01,name+' finite cable');for(const [point,id]of [[points[0],w.from],[points.at(-1),w.to]]){assert.equal(point.x,ports.get(id).x);assert.equal(point.y,ports.get(id).y);}}if(d.wires.length){const points=d.wires.flatMap(w=>G.route(d,w));assert(Math.max(...points.map(p=>p.x))-Math.min(...points.map(p=>p.x))<=680,name+' unnecessarily wide diagram');}}const legacy=JSON.parse(Data.encode('lc',new T.Session(P.examples('lc').initialDocument).capture()));legacy.version=1;assert.throws(()=>Data.decode(legacy),'an old fixed template must not be silently moved');}
console.log('Compact presets: body separation, finite terminal routes and fixed-template version guard passed');
