'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),M=require('./circuit-model'),F=require('./circuit-profile'),P=require('./circuit-ac-presets'),T=require('./circuit-transient'),AC=require('./circuit-ac-components'),D=require('./circuit-document'),Data=require('../circuit-ac-workbench/example-state');
for(const name of Object.keys(P.names)){const d=P.create(name),s=new T.Session(d);assert.deepEqual(D.decode(D.encode(d)),d);s.advance(.0123456789);assert.equal(s.fault,null,name);const saved=s.capture(),restored=T.Session.restore(JSON.parse(JSON.stringify(saved)));restored.advance(.00123);s.advance(.00123);assert.equal(restored.fault,null,name);assert.ok(Math.abs(restored.state.time-s.state.time)<1e-10);assert.deepEqual(restored.doc,s.doc);}
for(const name of ['transformer','lc']){const config=P.examples(name),profile=F.compile(config),d=M.clone(profile.initial);assert.equal(profile.analysis,'transient');assert.equal(profile.wires,false);assert.equal(profile.simulation.reset,false);assert.equal(profile.simulation.rate,false);
  for(const mutate of [x=>x.wires.pop(),x=>x.components[0].params.voltage++,x=>x.components[0].x++,x=>x.components[0].label='偽造',x=>x.components[0].locked=true,x=>M.add(x,'resistor',0,0),x=>{x.version=6;delete x.analysis;delete x.modelRevision;}]){const bad=M.clone(d);mutate(bad);assert.throws(()=>profile.assertSnapshot(bad));}
  const component=d.components.find(c=>c.type===(name==='transformer'?'transformer':'spdt'));component.params[name==='transformer'?'secondaryTurns':'closed']=name==='transformer'?150:'c';profile.assertSnapshot(d);const session=new T.Session(d);session.advance(.013456789012345);const encoded=Data.encode(name,session.capture()),decoded=Data.decode(encoded);assert.deepEqual(decoded.document,session.doc);const restored=T.Session.restore(decoded);restored.advance(.009);assert.equal(restored.fault,null);
  const window={location:{},addEventListener(){}};window.parent=window;window.top=window;vm.runInNewContext(fs.readFileSync(require.resolve('../shared/scorm'),'utf8'),{window,console,TextEncoder,setTimeout,clearTimeout});const answer=JSON.parse(encoded),draft=window.SimScorm.makeSnapshot('ac-capacity-'+name,'draft',answer),review=window.SimScorm.makeSnapshot('ac-capacity-'+name,'review',answer,{score:0,passed:false}),pending={version:1,activity:'ac-capacity-'+name,kind:'pending-final',payload:{reviewJson:JSON.stringify(review),score:0,maxScore:100,passed:false}};const sizes=[draft,review,pending].map(Data.bytes);sizes.forEach(n=>assert(n<=4000));console.log(name+' technical codec draft/review/pending-envelope bytes: '+sizes.join('/'));
  for(const mutate of [x=>x.version++,x=>x.model++,x=>x.extra=true,x=>x.parameters.push(1),x=>x.physics.sources.bad=0,x=>x.physics.time=-1]){const bad=JSON.parse(encoded);mutate(bad);assert.throws(()=>Data.decode(bad));}
}
{const s=new T.Session(P.create('lc'));s.advance(.037);const before=s.capture(),preview=M.clone(s.doc);preview.components.find(c=>c.type==='capacitor').params.capacitance*=2;s.preview(preview);assert.deepEqual(s.capture(),before);const moved=M.clone(s.doc);moved.components[0].label='換名';s.update(moved);assert.deepEqual(s.state,before.physics);const after=s.capture();assert.equal(after.document.components[0].label,'換名');const readonlyDocument=F.compile({role:'teacher'});assert.throws(()=>readonlyDocument.assertSnapshot(s.doc));assert.throws(()=>F.compile({analysis:'dc',initialDocument:s.doc}));}
{const palette=F.compile({analysis:'transient',palette:[{type:'capacitor',limit:1}],components:{default:{move:true,remove:true,params:['capacitance']}},ui:{palette:true}}),d=M.clone(palette.initial);M.add(d,'capacitor',100,100);palette.assertSnapshot(d);assert.equal(palette.canAdd(palette.palette[0],d),false);M.add(d,'capacitor',300,100);assert.throws(()=>palette.assertSnapshot(d));assert.throws(()=>F.compile({analysis:'transient',palette:[{type:'relay'}]}));assert.throws(()=>AC.toAC({...M.empty(),components:[M.component(M.empty(),'lamp',0,0,{model:'thermal'})]}));}
console.log('AC profiles, every preset session continuation, production example codec, capacity and invalid-state checks passed');
for(const name of ['transformer','lc']){const config=P.examples(name),session=new T.Session(config.initialDocument),snapshots=[session.capture()];if(name==='transformer'){const d=M.clone(session.doc);d.components.find(c=>c.type==='transformer').params.secondaryTurns=2000;d.components.find(c=>c.label==='負載電阻').params.resistance=.01;session.update(d);session.advance(.01345678912345);snapshots.push(session.capture());}else{session.advance(.007123456789);snapshots.push(session.capture());session.advance(.1-session.state.time);snapshots.push(session.capture());const d=M.clone(session.doc);d.components.find(c=>c.type==='spdt').params.closed='c';session.update(d);snapshots.push(session.capture());session.advance(session.compiled.period/4);snapshots.push(session.capture());session.advance(session.compiled.period/4);snapshots.push(session.capture());}
 let worst=0;for(const snapshot of snapshots){const encoded=Data.encode(name,snapshot),resumed=T.Session.restore(Data.decode(encoded));worst=Math.max(worst,Data.bytes(encoded));assert.deepEqual(resumed.state,snapshot.physics);resumed.advance(.000123);assert.equal(resumed.fault,null);const review={version:1,activity:'ac-capacity-'+name,kind:'review',answer:JSON.parse(encoded),score:0,passed:false},pending={version:1,activity:'ac-capacity-'+name,kind:'pending-final',payload:{reviewJson:JSON.stringify(review),score:0,maxScore:100,passed:false}};assert(Data.bytes(pending)<4000);}
 console.log(name+' production phase variants '+snapshots.length+'; largest compact session '+worst+' bytes');}

// The actual renderer changes view without changing terminals or simulation state.
{const R=require('./component-registry'),V=require('./circuit-renderer');for(const type of Object.keys(AC.types)){const c=M.component(M.empty('transient'),type,160,200),r={reading:1,current:.01,phase:.7};const real=V.body(c,r,{view:'real',values:true}),symbol=V.body(c,r,{view:'schematic',values:true});assert(real.includes('data-ac-view="real"'));assert(symbol.includes('data-ac-view="schematic"'));assert.notEqual(real.replace(/data-ac-view="[^"]*"/,''),symbol.replace(/data-ac-view="[^"]*"/,''),type);for(const angle of [0,90,180,270]){c.angle=angle;const bounds=R.bodyBounds(c);assert(bounds.right>bounds.left&&bounds.bottom>bounds.top);assert.equal(R.ports(c).length,AC.types[type].ports.length);}}}
// Lamp visuals follow solved power: an ordinary 50 Hz lamp is stable, a low-frequency lamp varies.
{const V=require('./circuit-renderer');function light(voltage,frequency,time){const d=P.create('resistive');d.components.find(c=>c.type==='ac-source').params.voltage=voltage;d.components.find(c=>c.type==='ac-source').params.frequency=frequency;const s=new T.Session(d);s.advance(time);assert.equal(s.fault,null);const lamp=d.components.find(c=>c.type==='lamp');return V.lampLight(lamp,s.read().components[lamp.id]);}const dim=light(3,50,.055),bright=light(6,50,.055);assert(bright.brightness>dim.brightness);assert(Math.abs(bright.power/ dim.power-4)<.02);assert(Math.abs(bright.brightness-light(6,50,.060).brightness)<.005);assert(light(6,1,.26).brightness>light(6,1,.51).brightness+.3);assert.equal(light(0,50,.05).brightness,0);}
console.log('AC apparatus/symbol rendering, unchanged ports and solved lamp brightness passed');

{const R=require('./component-registry'),V=require('./circuit-renderer'),d=P.create('resistive'),source=d.components[0];assert.equal(source.params.frequency,1);assert.equal(P.create('mains').components[0].params.frequency,50);assert.equal(P.rate('lc'),1);source.params.frequency=2;assert.equal(R.stepPrimaryParameter(source,1),50);source.params.frequency=50;assert.equal(R.stepPrimaryParameter(source,-1),2);const profile=F.compile({role:'teacher',analysis:'transient',palette:AC.palette,initialDocument:d}),bad=M.clone(d);bad.components[0].params.frequency=3;assert.throws(()=>profile.assertTransition(d,bad));const options={wireCurrents:new Set(d.wires.map(w=>w.id))},widths=[];for(const current of [0,1e-100,1e-9,.0009,.1,-.2597,10,1e100,null]){const r=new T.Session(d).read();r.wires=Object.fromEntries(d.wires.map(w=>[w.id,{...r.wires[w.id],current}]));const labels=V.labels(d,r,1,{},null,options).filter(p=>p.rows[0].kind==='wireCurrent');widths.push(labels[0].box.right-labels[0].box.left);assert(labels[0].rows[0].text.includes(current===null?'未能確定':'mA'));}assert(Math.max(...widths)-Math.min(...widths)<1e-9);assert(widths.every(width=>width<145),'compact current cards should not reserve 178 px');}
console.log('AC low-frequency controls, 50 Hz option and stable current label widths passed');

{const s=new T.Session(P.create('mains'));for(let n=0;n<120;n++){s.advance(1/60);if(n>2){const lamp=s.read().components.c3;assert(Number.isFinite(lamp.displayPower),'50 Hz rolling-window bins must stay complete across floating-point boundaries');assert(Math.abs(lamp.displayPower-3)<.015);}}}
console.log('50 Hz display power stays available and stable across 120 frame boundaries');

// Authored compact diagrams retain usable body separation and correctly attached finite cables.
{const R=require('./component-registry'),G=require('./circuit-routing');for(const name of Object.keys(P.names)){const d=P.create(name),ports=M.endpoints(d);for(let i=0;i<d.components.length;i++)for(const c of d.components.slice(i+1)){const a=R.bodyBounds(d.components[i]),b=R.bodyBounds(c);assert(a.right<=b.left||b.right<=a.left||a.bottom<=b.top||b.bottom<=a.top,name+' body overlap');}for(const w of d.wires){const points=G.route(d,w);assert(G.length(points)<=w.length+.01,name+' finite cable');for(const [point,id]of [[points[0],w.from],[points.at(-1),w.to]]){assert.equal(point.x,ports.get(id).x);assert.equal(point.y,ports.get(id).y);}}if(d.wires.length){const points=d.wires.flatMap(w=>G.route(d,w));assert(Math.max(...points.map(p=>p.x))-Math.min(...points.map(p=>p.x))<=680,name+' unnecessarily wide diagram');}}const legacy=JSON.parse(Data.encode('lc',new T.Session(P.examples('lc').initialDocument).capture()));legacy.version=1;assert.throws(()=>Data.decode(legacy),'an old fixed template must not be silently moved');}
console.log('Compact presets: body separation, finite terminal routes and fixed-template version guard passed');

// Visual charge signs follow CU, stay balanced, reverse colours, and respect field permissions.
{const R=require('./component-registry'),V=require('./circuit-renderer'),{XMLValidator}=require('fast-xml-parser'),cap=M.component(M.empty('transient'),'capacitor',0,0),display={view:'real',values:true,fields:true},counts=[];const count=svg=>Number(svg.match(/data-charge-count="(\d+)"/)[1]);for(const voltage of [0,1,3,6,12,1000]){const svg=V.body(cap,{voltage,charge:cap.params.capacitance*voltage},display);assert.equal(XMLValidator.validate('<svg>'+svg+'</svg>'),true);counts.push(count(svg));assert.equal((svg.match(/data-charge-count="(\d+)"/g)||[]).length,2);assert(svg.includes('data-charge-sign="'+(voltage?1:0)+'"'));assert(svg.includes('data-charge-sign="'+(voltage?-1:0)+'"'));}assert.equal(counts[0],0);assert(counts[3]>=40);for(let i=1;i<counts.length;i++)assert(counts[i]>counts[i-1]);const negative=V.body(cap,{voltage:-6},display);assert(negative.includes('data-capacitor-plate="a" data-charge-count="48" data-charge-sign="-1" data-charge-colour="#286cb7"'));assert(negative.includes('data-capacitor-plate="b" data-charge-count="48" data-charge-sign="1" data-charge-colour="#c43f4c"'));assert.equal(count(V.body(cap,{voltage:6},{...display,fields:false})),0);assert.equal(count(V.body(cap,{voltage:6},{...display,values:false})),48);const bigger=M.clone(cap);bigger.params.capacitance*=2;assert.equal(count(V.body(bigger,{voltage:3},display)),counts[3]);const unknown=V.body(cap,{voltage:null},display);assert(unknown.includes('data-charge-known="false"'));assert(unknown.includes('電荷未能確定'));assert.equal(count(unknown),0);
 for(const view of ['real','schematic']){const l=M.component(M.empty('transient'),'inductor',0,0),turns=[];for(const inductance of [.1,1,4,100]){l.params.inductance=inductance;const svg=V.body(l,{}, {...display,view});assert.equal(XMLValidator.validate('<svg>'+svg+'</svg>'),true);turns.push(Number(svg.match(/data-inductor-turns="(\d+)"/)[1]));}assert.deepEqual(turns,[3,10,20,100]);const t=M.component(M.empty('transient'),'transformer',0,0);assert.equal(R.get('transformer').name,'變壓器');for(const [primaryTurns,secondaryTurns]of [[200,100],[400,100],[200,300],[1,2000]]){t.params.primaryTurns=primaryTurns;t.params.secondaryTurns=secondaryTurns;const svg=V.body(t,{}, {...display,view});assert.equal(XMLValidator.validate('<svg>'+svg+'</svg>'),true);assert(svg.includes('data-transformer-winding="primary" data-nominal-turns="'+primaryTurns+'" data-visible-turns="'+Math.max(1,Math.round(primaryTurns/10))+'"'));assert(svg.includes('data-transformer-winding="secondary" data-nominal-turns="'+secondaryTurns+'" data-visible-turns="'+Math.max(1,Math.round(secondaryTurns/10))+'"'));}}
}
console.log('Parallel plates: balanced coloured CU charges, density/overlap and hidden/unknown states; dynamic L/N windings in both views passed');

// Range configuration is shared by UI and all snapshot/transition paths, in SI units.
{const R=require('./component-registry'),ranges={capacitor:{ranges:{capacitance:{min:.0001,max:.002,step:.00001}}},inductor:{ranges:{inductance:{min:.05,max:5,step:.05}}}},d=P.create('lc'),profile=F.compile({role:'teacher',analysis:'transient',palette:AC.palette,initialDocument:d,components:{byType:ranges}}),c=d.components.find(c=>c.type==='capacitor'),l=d.components.find(c=>c.type==='inductor');assert.equal(profile.parameterSpec(c,'capacitance').max,.002);assert.equal(R.stepPrimaryParameter(c,1,profile.parameterSpec(c,'capacitance')),.00101);for(const [id,key,value]of [[c.id,'capacitance',.003],[c.id,'capacitance',.00005],[l.id,'inductance',.001],[l.id,'inductance',6]]){const bad=M.clone(d);bad.components.find(x=>x.id===id).params[key]=value;assert.throws(()=>profile.assertSnapshot(bad),/範圍/);assert.throws(()=>profile.assertTransition(d,bad),/範圍/);}const student=F.compile({...P.examples('lc'),components:{...P.examples('lc').components,byType:ranges}}),bad=M.clone(student.initial);bad.components.find(c=>c.type==='capacitor').params.capacitance=.003;assert.throws(()=>student.assertSnapshot(bad));for(const bounds of [{min:.002,max:.0001},{min:0,max:.002},{min:.0001,max:.002,step:0},{min:.0001,max:.002,extra:true}])assert.throws(()=>F.compile({role:'teacher',analysis:'transient',palette:AC.palette,components:{byType:{capacitor:{ranges:{capacitance:bounds}}}}}));assert.throws(()=>F.compile({role:'teacher',analysis:'transient',palette:AC.palette,components:{byType:{capacitor:{ranges:{unknown:{min:0,max:1}}}}}}));const individual=F.compile({role:'teacher',analysis:'transient',palette:[],initialDocument:d,components:{byType:ranges,byId:{[c.id]:{ranges:{capacitance:{min:.0005,max:.0015}}}}}});assert.equal(individual.parameterSpec(c,'capacitance').min,.0005);assert.equal(individual.parameterSpec(c,'capacitance').step,.00001);assert.equal(individual.parameterSpec(l,'inductance').max,5);}
{const V=require('./circuit-renderer'),c=M.component(M.empty('transient'),'capacitor',0,0),gaps=[];for(const capacitance of [.0001,.001,.002]){c.params.capacitance=capacitance;const gap=AC.capacitorGap(c);gaps.push(gap);const svg=V.body(c,{voltage:6},{view:'real',values:true,fields:true}),right=gap/2;assert(svg.includes('data-plate-gap="'+gap+'"'));const lead=svg.match(/data-capacitor-leads="true" d="([^"]*)"/)[1];const left=Number(lead.match(/^M-60 0H([^ ]+)/)[1]),u=(left+gap/2+1.5)/.48;assert(Math.abs(Math.abs(u)-28)<1e-10,'left lead must meet the projected rear rim without a gap');assert.equal(lead,'M-60 0H'+left+' M60 0H'+right);assert(!/[VLQC]/.test(lead),'both leads must be straight horizontal lines');assert.equal((svg.match(/data-capacitor-disc="front"/g)||[]).length,2,'two projected circular faces');assert.equal((svg.match(/data-capacitor-disc="back"/g)||[]).length,2,'thin visible metal rims');assert(svg.indexOf('data-capacitor-leads')>svg.indexOf('data-capacitor-plate="b"'),'right lead must remain visible over the front face');assert(svg.includes('matrix(.48 0 0 1 '+right+' 0)'),'right lead must end at the projected circular face centre');for(const group of svg.matchAll(/<g data-capacitor-plate="[ab]"[^>]*>(.*?)<\/g>/g)){const centre=Number(group[1].match(/data-capacitor-disc="front"[^>]*matrix\(.48 0 0 1 ([^ ]+) 0\)/)[1]);for(const mark of group[1].matchAll(/M([-+\d.e]+) ([-+\d.e]+)([hv])3.4/g))for(const end of [0,3.4]){const x=Number(mark[1])+(mark[3]==='h'?end:0),y=Number(mark[2])+(mark[3]==='v'?end:0),u=(x-centre)/.48,v=y;assert(u*u+v*v<28*28,'charge strokes must remain on the circular face');}}}assert(gaps[0]>gaps[1]&&gaps[1]>gaps[2]);assert(gaps[0]>28*.48*2&&gaps[2]<28*.48*2,'far plates separate and near plates visibly overlap');}
console.log('Configurable C/L bounds, rejected out-of-range snapshots and inverse plate gaps with midpoint leads passed');

// Sparse/dense windings share a blue-grey former and tangent-continuous copper leads.
{const V=require('./circuit-renderer'),c=M.component(M.empty('transient'),'inductor',0,0),spans=[];for(const inductance of [.1,1,4,5]){c.params.inductance=inductance;const svg=V.body(c,{}, {view:'real',values:true});assert(svg.includes('data-inductor-former="true"'));assert(svg.includes('fill="#e3edf2"'));assert(svg.includes('stroke="#567185"'));assert(svg.includes('stroke="#8d6135"'));assert(svg.includes('data-inductor-back="true"'));const entry=Number(svg.match(/data-winding-entry="([^"]+)"/)[1]),exit=Number(svg.match(/data-winding-exit="([^"]+)"/)[1]),span=Number(svg.match(/data-winding-span="([^"]+)"/)[1]);spans.push(span);const turns=Number(svg.match(/data-inductor-turns="([^"]+)"/)[1]),pitch=span/turns;assert(Math.abs(2*entry+(turns-1)*pitch-3.5)<1e-10,'winding must be centred on the visible cylindrical surface');const lead=svg.match(/data-inductor-leads="true"><path d="([^"]*)"/)[1];const lower=entry-pitch/2;assert.equal(lead,'M-60 0H'+(entry-12)+'C'+(entry-2)+' 0 '+(lower+5)+' 24 '+lower+' 24 M'+exit+' 0H60');assert(svg.includes('M'+lower+' 24C'+(lower-5)+' 24 '+(entry-5)+' -24 '+entry+' -24'),'left lead must wind from below up the rear to the first top turn');assert(svg.indexOf('data-inductor-back')<svg.indexOf('data-inductor-former'),'the return half-turn belongs behind the former');assert(!/[VL]/.test(lead),'coil leads must have curved transitions, not right-angle elbows');assert(svg.includes('M'+entry+' -24C'));assert(svg.includes((exit-1)+' 0 '+exit+' 0'),'last half-turn must unwind horizontally into the outgoing lead');assert(!svg.includes('<rect'),'former should not be a rectangular core');}assert(spans[0]<15);assert(spans[1]>spans[0]);assert.equal(spans[2],68);assert.equal(spans[3],68);}
console.log('Styled cylindrical inductor: continuous front/back winding, sparse/dense turns and smooth tangent leads passed');

{const V=require('./circuit-renderer'),G=require('./circuit-routing');for(const view of ['real','schematic'])for(const [time,on,off]of [[.125,'c4','c5'],[.375,'c5','c4']]){const d=P.create('led');d.display.view=view;const session=new T.Session(d);session.advance(time);assert.equal(session.fault,null);const result=session.read(),path=V.componentFlowPaths(d,result).find(p=>p.component===on),ports=M.endpoints(d);assert(path.current>0);for(const [point,port]of [[path.points[0],ports.get(on+':a')],[path.points.at(-1),ports.get(on+':b')]]){assert.equal(point.x,port.x);assert.equal(point.y,port.y);}const routes=Object.fromEntries(d.wires.map(w=>[w.id,G.route(d,w)]));let svg=V.flow(d,result,routes,time,1);assert(svg.includes('data-flow-component="'+on+'"'));assert(!svg.includes('data-flow-component="'+off+'"'));d.display.flow='electron';svg=V.flow(d,result,routes,time,1);assert(svg.includes('data-flow-component="'+on+'"'));d.display.flow='off';assert.equal(V.flow(d,result,routes,time,1),'');}}
{const s=new T.Session(P.create('inductive'));s.advance(.1);const current=s.state.dynamic['c4:a'].i,energy=s.read().energy,sw=M.clone(s.doc);assert(Math.abs(current)>.1);sw.components[1].params.closed='c';assert.equal(s.update(sw),'event');assert.equal(s.fault,null);assert.equal(s.state.dynamic['c4:a'].i,current);s.advance(.04);assert.equal(s.fault,null);assert(s.read().energy<energy*.01);const saved=s.capture(),restored=T.Session.restore(saved);s.advance(.03);restored.advance(.03);assert.deepEqual(restored.capture(),s.capture());const powered=M.clone(s.doc);powered.components[1].params.closed='b';s.update(powered);s.advance(.05);assert.equal(s.fault,null);}
console.log('LED real/symbol current paths alternate with conducting branches; inductive supply/discharge switch preserves current and drains energy without faults');

{const s=new T.Session(P.create('rl'));assert.equal(s.doc.components[1].params.closed,'c');const on=M.clone(s.doc);on.components[1].params.closed='b';s.update(on);s.advance(.1);const i=s.state.dynamic['c4:a'].i;assert(i>0);const off=M.clone(s.doc);off.components[1].params.closed='c';s.update(off);assert.equal(s.fault,null);assert.equal(s.state.dynamic['c4:a'].i,i);s.advance(.4);assert.equal(s.fault,null);assert(s.state.dynamic['c4:a'].i<i*.01);}
{const V=require('./circuit-renderer'),c=M.component(M.empty('transient'),'transformer',0,0),svg=V.body(c,{}, {view:'real',values:true});assert.equal((svg.match(/data-transformer-back=/g)||[]).length,2);assert.equal((svg.match(/data-transformer-front=/g)||[]).length,2);assert.equal((svg.match(/data-transformer-leads=/g)||[]).length,2);assert(svg.indexOf('data-transformer-back')<svg.indexOf('data-transformer-core'));assert(svg.indexOf('data-transformer-core')<svg.indexOf('data-transformer-front'));assert(!svg.includes('<rect'),'windings should wrap around an open iron core rather than look like striped blocks');for(const key of ['primaryTurns','secondaryTurns']){assert.equal(AC.types.transformer.params[key].slider,true);assert.equal(AC.types.transformer.params[key].controlStep,1);}}
{const d=P.create('transformer'),profile=F.compile({role:'teacher',analysis:'transient',palette:[],initialDocument:d,components:{byType:{transformer:{ranges:{primaryTurns:{min:100,max:1000,step:25}}}}}}),spec=profile.parameterSpec(d.components[1],'primaryTurns');assert.equal(spec.slider,true);assert.equal(spec.step,25);assert.equal(spec.controlStep,undefined,'activity step must override the workbench slider step');}
console.log('RL supply/discharge current continuity and decay; transformer front/back helical windings and both endpoint-capable controls passed');
