"use strict";
const assert=require('node:assert/strict');
const M=require('./circuit-model'),G=require('./circuit-routing'),D=require('./circuit-document'),P=require('./presets'),S=require('./circuit-solver');
let cases=0;
const test=(name,fn)=>{fn();cases++;};
const xy=p=>({x:p.x,y:p.y});
const ends=(d,w)=>[xy(M.endpoints(d).get(w.from)),xy(M.endpoints(d).get(w.to))];
const route=(d,id='w1')=>G.route(d,d.wires.find(w=>w.id===id));
const offset=p=>({x:p.x+80,y:p.y+45});
const gap=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const bow=p=>Math.max(...p.map(q=>G.nearest([p[0],p.at(-1)],q).distance));
const turn=p=>Math.max(0,...p.slice(1,-1).map((b,i)=>{const a=p[i],c=p[i+2],u=Math.atan2(b.y-a.y,b.x-a.x),v=Math.atan2(c.y-b.y,c.x-b.x);return Math.abs(Math.atan2(Math.sin(v-u),Math.cos(v-u)))*180/Math.PI;}));
function attachedFixture(key){const d=M.empty();M.add(d,'battery',180,220);const w=M.addWire(d,360,320);assert(M.attach(d,w.id,key,'c1:a'));return{d,w,other:key==='from'?'to':'from'};}

test('default and preset stock',()=>{assert.equal(M.empty().cables.count,20);for(const name of Object.keys(P.names))assert.equal(P.create(name).cables.count,20,name);});
test('20 cables, atomic 21st rejection and return to stock',()=>{const h=M.history(M.empty());for(let i=0;i<20;i++)h.change(d=>M.addWire(d,i*200,100));const full=D.encode(h.get());assert.throws(()=>h.change(d=>M.addWire(d,0,200)),/用完/);assert.equal(D.encode(h.get()),full);h.change(d=>M.remove(d,'w1'));h.change(d=>M.addWire(d,0,100));assert.equal(h.get().wires.length,20);});
test('explicit old stock remains, missing legacy stock gets new default',()=>{const d=M.empty();d.cables.count=10;assert.equal(D.decode(D.encode(d)).cables.count,10);d.version=1;delete d.cables;assert.equal(D.decode(JSON.stringify(d)).cables.count,20);});
test('new cable and loose body are rigid straight segments',()=>{const d=M.empty(),w=M.addWire(d,360,320),p=route(d);assert.equal(w.via.length,0);assert.equal(p.length,2);M.bendWire(d,w.id,G.along(p,90),40,70);assert.deepEqual(route(d),p.map(q=>({x:q.x+40,y:q.y+70})));});

for(const key of ['from','to']){
  test(key+' loose endpoint leaves far end fixed and straight',()=>{const d=M.empty(),w=M.addWire(d,360,320),before=ends(d,w),other=key==='from'?'to':'from',target=offset(M.endpoints(d).get(w[key]));M.moveWireEnd(d,w.id,key,target);assert.deepEqual(xy(M.endpoints(d).get(w[other])),before[key==='from'?1:0]);assert.deepEqual(xy(M.endpoints(d).get(w[key])),target);assert.equal(w.via.length,0);M.validate(d);});
  test(key+' endpoint snap does not shift far end',()=>{const d=M.empty();M.add(d,'resistor',180,220);const w=M.addWire(d,360,320),other=key==='from'?'to':'from',fixed=xy(M.endpoints(d).get(w[other]));assert(M.attach(d,w.id,key,'c1:a'));assert.deepEqual(xy(M.endpoints(d).get(w[other])),fixed);assert.equal(w.via.length,0);});
  test(key+' loose endpoint finite reach and unreachable snap',()=>{const d=M.empty(),w=M.addWire(d,360,320),other=key==='from'?'to':'from',fixed=xy(M.endpoints(d).get(w[other]));assert(M.moveWireEnd(d,w.id,key,{x:fixed.x+2000,y:fixed.y+1000}).limited);assert.deepEqual(xy(M.endpoints(d).get(w[other])),fixed);assert(Math.abs(G.length(route(d))-w.length)<.02);assert.equal(w.via.length,0);M.add(d,'resistor',3000,2000);const before=D.encode(d);assert.equal(M.attach(d,w.id,key,'c1:a'),false);assert.equal(D.encode(d),before);});
  test(key+' one connected endpoint permits body bend with both positions fixed',()=>{const{d,w}=attachedFixture(key),fixed=ends(d,w),ids=[w.from,w.to],p=route(d);M.bendWire(d,w.id,G.along(p,G.length(p)/2),0,80);assert.deepEqual(ends(d,w),fixed);assert.deepEqual([w.from,w.to],ids);assert(bow(route(d))>60);assert(turn(route(d))<18.01);M.validate(d);});
  test(key+' curved free endpoint preserves shape and changes continuously',()=>{const{d,w,other}=attachedFixture(key),p=route(d);M.bendWire(d,w.id,G.along(p,G.length(p)/2),0,80);const curved=route(d),base=M.clone(d),fixed=xy(M.endpoints(d).get(w[key])),start=xy(M.endpoints(d).get(w[other]));let previous=curved;
    for(let frame=0;frame<=12;frame++){const next=M.clone(base),target={x:start.x+frame*5,y:start.y-frame*2};M.moveWireEnd(next,w.id,other,target);const path=route(next);assert.deepEqual(xy(M.endpoints(next).get(next.wires[0][key])),fixed);assert.deepEqual(xy(M.endpoints(next).get(next.wires[0][other])),target);assert(bow(path)>40,'existing bend is not reset');assert(turn(path)<18.01,'no sharp corner appears');assert(G.length(path)<=w.length+.05);for(let i=0;i<=24;i++)assert(gap(G.along(previous,G.length(previous)*i/24),G.along(path,G.length(path)*i/24))<8,'no frame rebound');previous=path;M.validate(next);}
  });
  test(key+' curved endpoint reaches the finite limit smoothly',()=>{const{d,w,other}=attachedFixture(key),p=route(d);M.bendWire(d,w.id,G.along(p,G.length(p)/2),0,80);const fixed=xy(M.endpoints(d).get(w[key]));assert(M.moveWireEnd(d,w.id,other,{x:fixed.x+2000,y:fixed.y}).limited);assert.deepEqual(xy(M.endpoints(d).get(w[key])),fixed);assert(G.length(route(d))<=w.length+.05);assert(bow(route(d))<.01);M.validate(d);});
  test(key+' restore, continuation and one-step undo keep curve and fixed ends',()=>{const{d,w,other}=attachedFixture(key),p=route(d);M.bendWire(d,w.id,G.along(p,G.length(p)/2),0,80);const saved=D.encode(d),h=M.history(D.decode(saved)),fixed=xy(M.endpoints(h.get()).get(w[key]));h.change(next=>M.moveWireEnd(next,w.id,other,offset(M.endpoints(next).get(w[other]))));assert.deepEqual(xy(M.endpoints(h.get()).get(w[key])),fixed);assert(bow(route(h.get()))>30);h.undo();assert.equal(D.encode(h.get()),saved);h.redo();M.validate(h.get());});
}
test('shared wire endpoint stays fixed when another cable is joined or unplugged',()=>{const d=M.empty(),a=M.addWire(d,240,300),b=M.addWire(d,470,380),original=ends(d,a),free=xy(M.endpoints(d).get(b.to));assert(M.attach(d,b.id,'from',a.to));assert.deepEqual(ends(d,a),original);assert.deepEqual(xy(M.endpoints(d).get(b.to)),free);assert(M.attached(d,a,'to'));M.moveWireEnd(d,b.id,'from',{x:400,y:450});assert.deepEqual(ends(d,a),original);assert.deepEqual(xy(M.endpoints(d).get(b.to)),free);assert.equal(b.via.length,0);M.validate(d);});
test('already connected far endpoint stays connected and reconnect restores readings',()=>{const d=P.create('series'),w=d.wires[0],far=w.to,original=w.from,p=xy(M.endpoints(d).get(far)),readings=S.solve(d).components;M.moveWireEnd(d,w.id,'from',{x:120,y:130});assert.equal(w.to,far);assert.deepEqual(xy(M.endpoints(d).get(far)),p);assert(!M.attached(d,w,'from'));M.validate(d);assert(M.attach(d,w.id,'from',original));assert.deepEqual(S.solve(d).components,readings,'the restored closed circuit has the same physical readings');});
console.log(`Cable grip: ${cases} focused cases passed; straight 20-stock, fixed endpoints, natural existing curves, finite reach, shared nodes and restored undo continuation.`);
