(function(root){
  'use strict';
  function mount({host,refs,profile,controller,viewDocument,routes}){
    const V=root.CircuitRenderer,Q=root.CircuitMath,abort=new AbortController();
    host.classList.add('ac-editor');
    const on=(e,type,fn)=>e.addEventListener(type,fn,{signal:abort.signal});
    const element=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text)e.textContent=text;return e;};
    const section=(title)=>{const e=element('section','panel-section'),h=element('h2','',title);e.append(h);return e;};
    const button=(text,fn,label=text)=>{const b=element('button','',text);b.type='button';b.setAttribute('aria-label',label);on(b,'click',fn);return b;};
    const quantity=(value,unit)=>Q.html(Q.quantity(value,unit));
    if(profile.ui.presets){refs.preset.replaceChildren(...Object.entries(root.CircuitACPresets.names).map(([key,label])=>new Option(label,key)));refs.preset.value='resistive';}
    const step=button('單步',()=>controller.advanceTime((controller.getAnalysis().period||1)/128)),reset=button('回到初始條件',()=>controller.resetSimulation()),notice=element('p','diagnostic ac-diagnostic');notice.setAttribute('role','status');refs.panel.prepend(notice);
    function documentLoaded(doc){if(!profile.ui.presets)return;const value=JSON.stringify(doc),name=Object.keys(root.CircuitACPresets.names).find(name=>JSON.stringify(root.CircuitACPresets.create(name))===value);if(name)refs.preset.value=name;else{if(![...refs.preset.options].some(o=>o.value==='custom')){const option=new Option('自訂電路','custom');option.disabled=true;refs.preset.add(option);}refs.preset.value='custom';}}
    const scope=profile.ui.waveform?root.CircuitScopeUI.mount({host,refs,profile,controller,viewDocument,routes}):null;
    let lastAnalysis=controller.getAnalysis(),energyScale=0;
    if(profile.ui.waveform&&(profile.simulation.step||profile.simulation.reset)){const experiment=element('details','panel-section'),summary=element('summary','','實驗操作');experiment.append(summary);if(profile.simulation.step)experiment.append(step);if(profile.simulation.reset)experiment.append(reset);refs.panel.insertBefore(experiment,refs.panel.querySelector('.inspector'));}
    const energyPanel=section('儲能與耗散'),fieldPanel=section('場與發電機示意'),energyContent=element('div','ac-energy'),fieldContent=element('div','ac-field'),fieldCheck=document.createElement('input'),energyCheck=document.createElement('input');fieldCheck.type=energyCheck.type='checkbox';fieldCheck.checked=energyCheck.checked=true;
    const fieldLabel=element('label','check','顯示場示意'),energyLabel=element('label','check','顯示能量');fieldLabel.prepend(fieldCheck);energyLabel.prepend(energyCheck);fieldPanel.append(fieldLabel,fieldContent);energyPanel.append(energyLabel,energyContent);on(fieldCheck,'change',()=>{fieldContent.hidden=!fieldCheck.checked;controller.setFieldDisplay(fieldCheck.checked);});on(energyCheck,'change',()=>energyContent.hidden=!energyCheck.checked);if(profile.ui.energy)refs.panel.append(energyPanel);if(profile.ui.field)refs.panel.append(fieldPanel);
    if(profile.ui.help){const p=element('p','note','交流模型：電容电壓及電感電流有時間狀態。R／開關變更保留儲能；C／L／匝數及重新接線建立新實驗。理想空斷線圈、短接帶電電容可能沒有有限解。');refs.helpDialog.querySelector('.help-body')?.prepend(p);}
    function render(analysis){lastAnalysis=analysis;const playback=controller.getPlayback();step.disabled=reset.disabled=playback.readOnly;refs.pause.disabled=playback.readOnly||!profile.simulation.play;refs.slowMotion.disabled=playback.readOnly||!profile.simulation.rate;notice.hidden=!analysis.diagnostics.length;notice.textContent=analysis.diagnostics.map(d=>d.message).join(' ');
      if(profile.ui.energy){const doc=controller.getDocument(),electric=doc.components.filter(c=>c.type==='capacitor').reduce((s,c)=>s+(analysis.components[c.id]?.energy||0),0),magnetic=doc.components.filter(c=>['inductor','transformer'].includes(c.type)).reduce((s,c)=>s+(analysis.components[c.id]?.energy||0),0);energyScale=Math.max(energyScale,electric+magnetic,1e-12);energyContent.innerHTML=[['電場儲能',electric],['磁場儲能',magnetic]].map(([label,value])=>'<div class="ac-energy-row"><span>'+label+'</span><span>'+quantity(value,'J')+'</span><meter min="0" max="'+energyScale+'" value="'+value+'" aria-label="'+label+'"></meter></div>').join('')+'<p class="note">儲能條以已觀察最大儲能為量尺。</p><p>累計耗散 '+quantity(analysis.dissipatedEnergy,'J')+'</p>';
      }
      if(profile.ui.field){const doc=controller.getDocument(),selection=controller.getInteraction().selection,c=doc.components.find(c=>c.id===selection?.id&&['generator','capacitor','inductor','transformer'].includes(c.type))||doc.components.find(c=>['generator','capacitor','inductor','transformer'].includes(c.type)),r=c&&analysis.components[c.id];
        if(!c)fieldContent.textContent='選取電容、線圈或發電機觀察示意。';else if(c.type==='generator')fieldContent.innerHTML='<svg viewBox="0 0 280 100" role="img" aria-label="轉動線圈及磁場示意"><text x="18" y="54" fill="#b4534d">N</text><text x="248" y="54" fill="#397cab">S</text><path d="M48 25H232M48 50H232M48 75H232" stroke="#c4d2dc"/><g transform="translate(140 50) rotate('+r.phase*180/Math.PI+')"><ellipse rx="18" ry="40" fill="none" stroke="#c28748" stroke-width="4"/><path d="M0 0H65M55-5L65 0L55 5" fill="none" stroke="#397cab" stroke-width="2"/></g></svg><p>法線角度 θ = '+Number((r.phase*180/Math.PI).toFixed(1))+'°</p><p>單匝 Φ '+quantity(r.flux,'Wb')+'；NΦ '+quantity(r.fluxLinkage,'Wb')+'</p><p>電動勢 '+quantity(r.sourceEmf,'V')+'</p>';
        else if(c.type==='capacitor'){const reverse=r.voltage<0,extent=Math.max(1,root.CircuitAC.capacitorGap(c)/2-5),arrows=[-18,0,18].map(y=>'<path d="'+(reverse?'M'+extent+' '+y+'H'+(-extent)+'M'+(-extent+2)+' '+(y-2)+'L'+(-extent)+' '+y+'L'+(-extent+2)+' '+(y+2):'M'+(-extent)+' '+y+'H'+extent+'M'+(extent-2)+' '+(y-2)+'L'+extent+' '+y+'L'+(extent-2)+' '+(y+2))+'" stroke="#397cab" fill="none" opacity="'+(Math.abs(r.voltage)>1e-8?1:0)+'"/>').join('');fieldContent.innerHTML='<svg viewBox="-65 -65 130 130" style="height:160px" role="img" aria-label="平行板電容及電荷、電場示意"><g transform="rotate('+c.angle+')">'+V.body(c,r,{...doc.display,view:'real',fields:true})+arrows+'</g></svg><p>電場由正板指向負板；電子不穿過介質。符號示意電荷量，數值按 q=CU。</p><p>電荷 '+quantity(r.charge,'C')+'；電壓 '+quantity(r.voltage,'V')+'</p>';
        }else{const transformer=c.type==='transformer',arrow=transformer?'':'<path d="'+(r.current<0?'M45 32H-45M-35 27L-45 32L-35 37':'M-45 32H45M35 27L45 32L35 37')+'" stroke="#397cab" fill="none" opacity="'+(Math.abs(r.current)>1e-10?1:0)+'"/>';fieldContent.innerHTML='<svg viewBox="-85 -45 170 105" role="img" aria-label="'+(transformer?'變壓器繞組示意':'電感線圈及磁場方向示意')+'">'+V.body({...c,angle:0},r,{...doc.display,view:'real',fields:true})+arrow+'</svg><p>'+ (transformer?'原／副線圈匝數依設定顯示；畫面以比例示意。':'線圈密度隨電感增加；固定磁路下 L 與匝數平方成正比。')+'</p><p>'+(transformer?'原線圈':'線圈')+'電流 '+quantity(r.current,'A')+'</p>'+(transformer?'<p>副線圈電流 '+quantity(r.secondaryCurrent,'A')+'</p>':'');}
      }
      scope?.render();
    }
    function clear(){scope?.clear();energyScale=0;}
    const originalLoaded=documentLoaded;
    render(lastAnalysis);
    return {render,animate:()=>scope?.render(),setChannels:channels=>scope?.setChannels(channels)??false,getTools:()=>scope?.getTools()||[],setTools:tools=>scope?.setTools(tools)??false,clear,documentLoaded(doc){originalLoaded(doc);scope?.resetDocument();},destroy(){abort.abort();scope?.destroy();host.classList.remove('ac-editor');}};
  }
  root.CircuitACUI={mount};
})(window);
