(function(root){
  'use strict';
  function mount({host,refs,profile,controller}){
    const O=root.CircuitObservation,V=root.CircuitRenderer,Q=root.CircuitMath,abort=new AbortController(),buffer=new O.Buffer(),colors=['#245b9e','#b25617','#20806a','#864a9c'];
    host.classList.add('ac-editor');
    const on=(e,type,fn)=>e.addEventListener(type,fn,{signal:abort.signal});
    const element=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text)e.textContent=text;return e;};
    const section=(title)=>{const e=element('section','panel-section'),h=element('h2','',title);e.append(h);return e;};
    const button=(text,fn,label=text)=>{const b=element('button','',text);b.type='button';b.setAttribute('aria-label',label);on(b,'click',fn);return b;};
    const quantity=(value,unit)=>Q.html(Q.quantity(value,unit));
    if(profile.ui.presets){refs.preset.replaceChildren(...Object.entries(root.CircuitACPresets.names).map(([key,label])=>new Option(label,key)));refs.preset.value='resistive';}
    const step=button('單步',()=>controller.advanceTime((controller.getAnalysis().period||1)/128)),reset=button('回到初始條件',()=>controller.resetSimulation()),notice=element('p','diagnostic ac-diagnostic');notice.setAttribute('role','status');refs.panel.prepend(notice);
    function documentLoaded(doc){if(!profile.ui.presets)return;const value=JSON.stringify(doc),name=Object.keys(root.CircuitACPresets.names).find(name=>JSON.stringify(root.CircuitACPresets.create(name))===value);if(name)refs.preset.value=name;else{if(![...refs.preset.options].some(o=>o.value==='custom')){const option=new Option('自訂電路','custom');option.disabled=true;refs.preset.add(option);}refs.preset.value='custom';}}
    const plot=element('section','ac-waveform'),canvas=document.createElement('canvas'),heading=element('div','ac-plot-heading'),plotArea=element('div','ac-plot-area'),caption=element('output','ac-cursor-readings');canvas.setAttribute('aria-label','已計算的電壓、電流與能量波形；量測數值可在操作面板讀取');plotArea.append(canvas);heading.append(element('strong','','波形'),button('返回電路',()=>{refs.stage.classList.remove('graph-open','graph-view');graphButton.setAttribute('aria-pressed','false');controller.fit();}),button('放大波形',()=>{refs.stage.classList.toggle('graph-view');controller.fit();}));plot.append(heading,plotArea,caption);refs.stage.insertBefore(plot,refs.stage.querySelector('.stage-bottom'));
    const graphButton=button('波形',()=>{const open=refs.stage.classList.toggle('graph-open');if(window.matchMedia('(max-width:759px)').matches)refs.stage.classList.toggle('graph-view',open);graphButton.setAttribute('aria-pressed',String(open));controller.fit();});graphButton.setAttribute('aria-pressed','false');
    const observation=section('波形與量測'),selectors=[],cursorInputs=[],cursorButtons=[],cursors=[.25,.75],windows=document.createElement('select');windows.setAttribute('aria-label','波形時間範圍');for(const n of [1,2,4])windows.add(new Option(n+' 個參考週期',n));windows.value=2;on(windows,'change',draw);observation.append(graphButton,windows);if(profile.simulation.step)observation.append(step);if(profile.simulation.reset)observation.append(reset);
    let selected=[],options=[],docKey='',lastAnalysis=controller.getAnalysis(),energyScale=0,range={start:0,end:1};
    for(let i=0;i<4;i++){const select=document.createElement('select');select.setAttribute('aria-label','波形通道 '+(i+1));select.dataset.channel=String(i);on(select,'change',()=>{const next=selectors.map(s=>s.value).filter(Boolean);if(new Set(next).size!==next.length){select.value=selected[i]?.key||'';return;}selected=next.map(k=>options.find(o=>o.key===k));draw();});selectors.push(select);observation.append(select);}
    const measured=element('div','ac-measurements');measured.setAttribute('aria-live','off');observation.append(measured);
    for(let i=0;i<2;i++){const label=element('label','', '游標 '+(i+1)+' 位置'),input=document.createElement('input');input.type='range';input.min=0;input.max=100;input.step=.1;input.value=cursors[i]*100;on(input,'input',()=>{cursors[i]=Number(input.value)/100;draw();});label.append(input);observation.append(label);cursorInputs.push(input);
      const grip=button('',()=>{},'游標 '+(i+1));grip.className='ac-cursor';grip.style.touchAction='none';plotArea.append(grip);cursorButtons.push(grip);
      on(grip,'pointerdown',e=>{grip.setPointerCapture(e.pointerId);e.preventDefault();});on(grip,'pointermove',e=>{if(!grip.hasPointerCapture(e.pointerId))return;const r=plotArea.getBoundingClientRect();cursors[i]=Math.max(0,Math.min(1,(e.clientX-r.left-72)/Math.max(1,r.width-126)));input.value=cursors[i]*100;draw();});on(grip,'pointerup',e=>{if(grip.hasPointerCapture(e.pointerId))grip.releasePointerCapture(e.pointerId);});on(grip,'keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();e.stopPropagation();cursors[i]=Math.max(0,Math.min(1,cursors[i]+(e.key==='ArrowLeft'?-.01:.01)));input.value=cursors[i]*100;draw();});
    }
    const phaseOutput=element('p','note');observation.append(phaseOutput);refs.panel.insertBefore(observation,refs.panel.querySelector('.inspector'));
    if(!profile.ui.waveform){plot.remove();graphButton.remove();observation.remove();}
    const energyPanel=section('儲能與耗散'),fieldPanel=section('場與發電機示意'),energyContent=element('div','ac-energy'),fieldContent=element('div','ac-field'),fieldCheck=document.createElement('input'),energyCheck=document.createElement('input');fieldCheck.type=energyCheck.type='checkbox';fieldCheck.checked=energyCheck.checked=true;
    const fieldLabel=element('label','check','顯示場示意'),energyLabel=element('label','check','顯示能量');fieldLabel.prepend(fieldCheck);energyLabel.prepend(energyCheck);fieldPanel.append(fieldLabel,fieldContent);energyPanel.append(energyLabel,energyContent);on(fieldCheck,'change',()=>{fieldContent.hidden=!fieldCheck.checked;controller.setFieldDisplay(fieldCheck.checked);});on(energyCheck,'change',()=>energyContent.hidden=!energyCheck.checked);if(profile.ui.energy)refs.panel.append(energyPanel);if(profile.ui.field)refs.panel.append(fieldPanel);
    if(profile.ui.help){const p=element('p','note','交流模型：電容电壓及電感電流有時間狀態。R／開關變更保留儲能；C／L／匝數及重新接線建立新實驗。理想空斷線圈、短接帶電電容可能沒有有限解。');refs.helpDialog.querySelector('.help-body')?.prepend(p);}
    function refresh(){const doc=controller.getDocument(),key=JSON.stringify(doc.components.map(c=>[c.id,c.type,c.label,c.params.model]));if(key===docKey)return;docKey=key;options=O.channels(doc).filter(o=>profile.observationChannels===null||profile.observationChannels.some(c=>c.id===o.id&&c.quantity===o.quantity));
      selected=selected.filter(c=>options.some(o=>o.key===c.key));if(!selected.length){const source=doc.components.find(c=>['ac-source','generator'].includes(c.type)),reactive=doc.components.find(c=>c.type==='capacitor'),load=doc.components.find(c=>['lamp','resistor','inductor'].includes(c.type));const defaults=source?[source.id+':voltage',(load||source).id+':current',...(source.type==='generator'?[source.id+':flux']:[])]:reactive?[reactive.id+':voltage',reactive.id+':current',reactive.id+':energy']:[options[0]?.key];selected=defaults.map(k=>options.find(o=>o.key===k)).filter(Boolean).slice(0,4);}
      if(profile.observationChannels!==null)selected=options.slice(0,4);syncSelectors();}
    function syncSelectors(){for(let i=0;i<selectors.length;i++){selectors[i].replaceChildren(new Option('不顯示通道 '+(i+1),''),...options.map(o=>new Option(o.label+' / '+o.unit,o.key)));selectors[i].value=selected[i]?.key||'';}}
    function setChannels(channels){if(!profile.ui.waveform||!Array.isArray(channels)||channels.length>4)return false;refresh();const list=channels.map(c=>options.find(o=>o.id===c.id&&o.quantity===c.quantity));if(list.some(c=>!c)||new Set(list.map(c=>c.key)).size!==list.length)return false;selected=list;syncSelectors();draw();return true;}
    function draw(){
      if(!profile.ui.waveform)return;const r=plotArea.getBoundingClientRect(),width=Math.max(160,r.width),height=Math.max(110,r.height),ratio=window.devicePixelRatio||1;if(canvas.width!==Math.round(width*ratio)||canvas.height!==Math.round(height*ratio)){canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);}const ctx=canvas.getContext('2d');ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,width,height);ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);
      const span=(lastAnalysis.period||1)*Number(windows.value);range={start:Math.max(0,lastAnalysis.time-span),end:Math.max(span,lastAnalysis.time)};const x=t=>72+(t-range.start)/(range.end-range.start)*(width-126),points=buffer.points.filter(p=>p.time>=range.start&&p.time<=range.end),lane=(height-28)/Math.max(1,selected.length);
      ctx.font='13px "Cambria Math",serif';ctx.lineWidth=1;ctx.fillStyle='#52677c';ctx.strokeStyle='#e0e7ef';for(let i=0;i<=4;i++){const xx=72+i*(width-126)/4;ctx.beginPath();ctx.moveTo(xx,2);ctx.lineTo(xx,height-24);ctx.stroke();ctx.fillText(Number((range.start+(range.end-range.start)*i/4).toPrecision(3))+' s',Math.max(0,Math.min(width-52,xx-18)),height-6);}
      selected.forEach((channel,i)=>{const values=points.map(p=>p.values[channel.id]?.[channel.quantity]).filter(Number.isFinite),max=Math.max(...values.map(Math.abs),1e-12),top=i*lane+8,mid=top+(lane-16)/2,amplitude=(lane-22)/2;ctx.fillStyle=colors[i];ctx.fillText(channel.unit,6,top+12);ctx.fillText(Number(max.toPrecision(3)).toString(),6,top+28);ctx.strokeStyle='#d6e0e9';ctx.beginPath();ctx.moveTo(72,mid);ctx.lineTo(width-54,mid);ctx.stroke();ctx.strokeStyle=colors[i];ctx.lineWidth=1.8;ctx.beginPath();let pen=false;
        for(const p of points){const v=p.values[channel.id]?.[channel.quantity];if(!Number.isFinite(v)){pen=false;continue;}if(!pen){ctx.moveTo(x(p.time),mid-v/max*amplitude);pen=true;}else ctx.lineTo(x(p.time),mid-v/max*amplitude);}ctx.stroke();});
      if(!points.length){ctx.fillStyle='#64748b';ctx.font='14px system-ui';ctx.fillText('播放或單步以收集波形',80,height/2);}
      const cursorTimes=cursors.map(c=>range.start+c*(range.end-range.start));for(let i=0;i<2;i++){cursorButtons[i].style.left=x(cursorTimes[i])+'px';cursorButtons[i].setAttribute('aria-label','游標 '+(i+1)+' · '+Number(cursorTimes[i].toPrecision(4))+' s');}
      caption.textContent='Δt = '+Number(Math.abs(cursorTimes[1]-cursorTimes[0]).toPrecision(4))+' s';measured.replaceChildren();
      selected.forEach((channel,i)=>{const row=element('p','ac-channel-value');row.style.borderLeftColor=colors[i];row.append(element('strong','',channel.label));const pair=cursorTimes.map(t=>!points.length||t<points[0].time||t>points.at(-1).time?null:points.reduce((best,p)=>!best||Math.abs(p.time-t)<Math.abs(best.time-t)?p:best,null));const value=element('span');value.innerHTML='游標 1：'+quantity(pair[0]?.values[channel.id]?.[channel.quantity],channel.unit)+'　游標 2：'+quantity(pair[1]?.values[channel.id]?.[channel.quantity],channel.unit);row.append(value);const q=lastAnalysis.measurements?.[channel.id],metric=element('span');metric.innerHTML=q?.status==='ready'?channel.quantity==='voltage'?'有效值 '+quantity(q.voltageRms,'V'):channel.quantity==='current'?'有效值 '+quantity(q.currentRms,'A')+'；平均功率 '+quantity(q.averagePower,'W'):'':q?.status==='unknown'?'量測未能確定':'收集量測中';row.append(metric);measured.append(row);});
      const doc=controller.getDocument(),sources=doc.components.filter(c=>['ac-source','generator'].includes(c.type)),frequency=sources[0]?.params.frequency,validSource=sources.length===1&&(sources[0].type==='generator'||sources[0].params.waveform==='sine'),phase=profile.ui.phase&&validSource&&selected.length>1?O.phase(points,selected[0],selected[1],frequency):null;phaseOutput.hidden=!profile.ui.phase;phaseOutput.textContent=phase===null?'相位差：需要兩個穩定正弦通道及足夠資料。':'通道 2 相對通道 1：'+Number(phase.toFixed(1))+'°（正值為超前）';
    }
    function render(analysis){lastAnalysis=analysis;refresh();const playback=controller.getPlayback();step.disabled=reset.disabled=playback.readOnly;refs.pause.disabled=playback.readOnly||!profile.simulation.play;refs.slowMotion.disabled=playback.readOnly||!profile.simulation.rate;notice.hidden=!analysis.diagnostics.length;notice.textContent=analysis.diagnostics.map(d=>d.message).join(' ');
      if(profile.ui.energy){const doc=controller.getDocument(),electric=doc.components.filter(c=>c.type==='capacitor').reduce((s,c)=>s+(analysis.components[c.id]?.energy||0),0),magnetic=doc.components.filter(c=>['inductor','transformer'].includes(c.type)).reduce((s,c)=>s+(analysis.components[c.id]?.energy||0),0);energyScale=Math.max(energyScale,electric+magnetic,1e-12);energyContent.innerHTML=[['電場儲能',electric],['磁場儲能',magnetic]].map(([label,value])=>'<div class="ac-energy-row"><span>'+label+'</span><span>'+quantity(value,'J')+'</span><meter min="0" max="'+energyScale+'" value="'+value+'" aria-label="'+label+'"></meter></div>').join('')+'<p class="note">儲能條以已觀察最大儲能為量尺。</p><p>累計耗散 '+quantity(analysis.dissipatedEnergy,'J')+'</p>';
      }
      if(profile.ui.field){const doc=controller.getDocument(),selection=controller.getInteraction().selection,c=doc.components.find(c=>c.id===selection?.id&&['generator','capacitor','inductor','transformer'].includes(c.type))||doc.components.find(c=>['generator','capacitor','inductor','transformer'].includes(c.type)),r=c&&analysis.components[c.id];
        if(!c)fieldContent.textContent='選取電容、線圈或發電機觀察示意。';else if(c.type==='generator')fieldContent.innerHTML='<svg viewBox="0 0 280 100" role="img" aria-label="轉動線圈及磁場示意"><text x="18" y="54" fill="#b4534d">N</text><text x="248" y="54" fill="#397cab">S</text><path d="M48 25H232M48 50H232M48 75H232" stroke="#c4d2dc"/><g transform="translate(140 50) rotate('+r.phase*180/Math.PI+')"><ellipse rx="18" ry="40" fill="none" stroke="#c28748" stroke-width="4"/><path d="M0 0H65M55-5L65 0L55 5" fill="none" stroke="#397cab" stroke-width="2"/></g></svg><p>法線角度 θ = '+Number((r.phase*180/Math.PI).toFixed(1))+'°</p><p>單匝 Φ '+quantity(r.flux,'Wb')+'；NΦ '+quantity(r.fluxLinkage,'Wb')+'</p><p>電動勢 '+quantity(r.sourceEmf,'V')+'</p>';
        else if(c.type==='capacitor'){const reverse=r.voltage<0;fieldContent.innerHTML='<svg viewBox="0 0 280 100" role="img" aria-label="電容極板及電場方向示意"><path d="M60 12V88M220 12V88" stroke="#7a9ba8" stroke-width="6"/>'+[30,50,70].map(y=>'<path d="'+(reverse?'M205 '+y+'H75M85 '+(y-5)+'L75 '+y+'L85 '+(y+5):'M75 '+y+'H205M195 '+(y-5)+'L205 '+y+'L195 '+(y+5))+'" stroke="#397cab" fill="none" opacity="'+(Math.abs(r.voltage)>1e-8?1:0)+'"/>').join('')+'</svg><p>電場方向示意；電子不穿過介質。</p><p>電荷 '+quantity(r.charge,'C')+'；電壓 '+quantity(r.voltage,'V')+'</p>';
        }else fieldContent.innerHTML='<svg viewBox="0 0 280 100" role="img" aria-label="線圈磁場方向示意"><path d="M80 68V32q10-25 20 0t20 0t20 0t20 0t20 0v36" fill="none" stroke="#a57545" stroke-width="4"/><path d="'+(r.current<0?'M225 80H55M65 75L55 80L65 85':'M55 80H225M215 75L225 80L215 85')+'" stroke="#397cab" fill="none" opacity="'+(Math.abs(r.current)>1e-10?1:0)+'"/></svg><p>磁場方向示意，箭嘴隨線圈電流方向改變。</p><p>線圈電流 '+quantity(r.current,'A')+'</p>';
      }
      if(profile.ui.waveform&&refs.stage.classList.contains('graph-open'))draw();
    }
    const unsubscribe=controller.onAnalysis(r=>buffer.sample(r)),unChange=controller.onChange(()=>{const next=root.CircuitTransient.signature(controller.getDocument());if(next!==lastSignature)clear();lastSignature=next;refresh();});let lastSignature=root.CircuitTransient.signature(controller.getDocument());
    const resize=new ResizeObserver(draw);resize.observe(plotArea);
    function clear(){buffer.clear();buffer.sample(controller.getAnalysis());energyScale=0;draw();}
    buffer.sample(lastAnalysis);refresh();render(lastAnalysis);
    return {render,setChannels,clear,documentLoaded,destroy(){abort.abort();resize.disconnect();unsubscribe();unChange();host.classList.remove('ac-editor');}};
  }
  root.CircuitACUI={mount};
})(window);
