"use strict";
const assert = require("node:assert/strict"), M = require("./circuit-model"), R = require("./component-registry"), S = require("./circuit-solver"), D = require("./circuit-document"), G = require("./circuit-routing"), V = require("./circuit-renderer"), P = require("./presets"), { XMLValidator } = require("fast-xml-parser");
const near = (a, b, msg, eps = 1e-7) => assert(Math.abs(a - b) <= eps * Math.max(1, Math.abs(b)), `${msg}: ${a} != ${b}`);
function simple(resistance = 12, internal = 0, model = "ideal") { const d = M.empty(), b = M.add(d, "battery", 0, 0, { resistance: internal }), r = M.add(d, "lamp", 200, 0, { resistance, model }); M.connect(d, b.id + ":a", r.id + ":a"); M.connect(d, r.id + ":b", b.id + ":b"); return { d, b, r }; }
for (const name of Object.keys(P.names)) {
  const d = P.create(name), r = S.solve(d), restored = D.decode(D.encode(d)); assert.deepEqual(restored, d); assert.deepEqual(S.solve(restored).components, r.components); assert.equal(r.diagnostics.length, 0, name);
  // Execute a legal continuation after the production round trip.
  if (restored.policy.mode === "wiring") M.connect(restored, restored.components[0].id + ":a", restored.components[1].id + ":a"); else M.add(restored, "resistor", 900, 600);
  M.validate(restored); S.solve(restored);
}
near(S.solve(P.create("series")).components.c1.current, -.25, "series"); near(S.solve(P.create("parallel")).components.c1.current, -1, "parallel"); near(S.solve(P.create("bridge")).components.c6.reading, 0, "balanced bridge");
let f = simple(12, 2), out = S.solve(f.d); near(out.components[f.r.id].current, 6 / 14, "full circuit Ohm"); near(out.components[f.b.id].internalPower, (6 / 14) ** 2 * 2, "source heat"); near(out.components[f.b.id].sourcePower, out.components[f.b.id].delivered + out.components[f.b.id].internalPower, "source energy");
f = simple(12, 0, "thermal"); out = S.solve(f.d); near(out.components[f.r.id].current, .5, "thermal rated current", 1e-6); near(out.components[f.r.id].resistance, 12, "thermal rated R", 1e-6); near(out.components[f.r.id].temperature, 2600, "thermal rated temperature", 1e-6);
for (const voltage of [0, .0001, .1, 1, 3, 6, 12, 60]) { const at = R.lampAt(voltage, f.r.params); assert(at.conductance > 0); const dv = 1e-5; near(at.conductance, (R.lampAt(voltage + dv, f.r.params).current - R.lampAt(voltage - dv, f.r.params).current) / (2 * dv), "lamp Jacobian", 1e-4); f.b.params.voltage = voltage; out = S.solve(f.d); assert.equal(out.diagnostics.length, 0); assert(out.residual < 1e-8); near(out.components[f.r.id].power, voltage * out.components[f.r.id].current, "lamp power"); }
f = simple(); f.d.wires.pop(); out = S.solve(f.d); near(out.components[f.r.id].current, 0, "open loop"); assert.equal(out.voltage(f.b.id + ":b", f.r.id + ":b"), -6);
const isolated = M.add(f.d, "voltmeter", 0, 200); out = S.solve(f.d); assert.equal(out.components[isolated.id].reading, null, "floating meter"); assert.equal(out.voltage(f.b.id + ":a", isolated.id + ":a"), null);
f = simple(); M.connect(f.d, f.b.id + ":a", f.b.id + ":b"); out = S.solve(f.d); assert(out.diagnostics.some((x) => x.code === "inconsistent")); assert.equal(out.components[f.b.id].current, null);
f.r.params.model="thermal";out=S.solve(f.d);assert.equal(out.components[f.r.id].resistance,null,'failed thermal working resistance is unknown');assert(!V.scene(f.d,out).includes('1.2 Ω'),'failed thermal diagram cannot show a guessed cold resistance');f.r.params.model="ideal";
f.b.params.resistance = 2; out = S.solve(f.d); near(out.components[f.b.id].current, -3, "finite short current"); near(out.components[f.r.id].current, 0, "shorted load");
const independent = M.add(f.d, "battery", 500, 500); independent.params.voltage = 9; out = S.solve(f.d); near(out.voltage(independent.id + ":a", independent.id + ":b"), 9, "independent island"); assert.equal(out.voltage(independent.id + ":a", f.b.id + ":a"), null);
f.b.params.resistance = 0; out = S.solve(f.d); near(out.components[independent.id].voltage, 9, "independent solve survives bad island");
const meters = P.create("meters"); out = S.solve(meters); near(out.components.c3.reading, 3, "four port watts"); const w = meters.components.find((c) => c.type === "wattmeter"); const aWire = meters.wires.find((wire) => wire.from === w.id + ":c"); const bWire = meters.wires.find((wire) => wire.from === w.id + ":d"); [aWire.from, bWire.from] = [bWire.from, aWire.from]; out = S.solve(meters); near(out.components.c3.reading, -3, "reversed W potential coil");
const reversedCurrentCoil = P.create("meters");
reversedCurrentCoil.wires.forEach(wire => { for (const key of ["from", "to"]) if (["c3:a", "c3:b"].includes(wire[key])) wire[key] = wire[key] === "c3:a" ? "c3:b" : "c3:a"; });
near(S.solve(reversedCurrentCoil).components.c3.reading, -3, "reversed W current coil");
const loadedW = P.create("meters"); Object.assign(loadedW.components[2].params, {resistance: 1, inputResistance: 12}); out = S.solve(loadedW);
near(out.components.c3.current, 6 / 7, "finite W series and parallel loading"); near(out.components.c3.sensedVoltage, 36 / 7, "loaded W sensed voltage");
near(out.components.c3.reading, 216 / 49, "W reading includes sensed circuit current"); near(out.components.c3.power, 144 / 49, "W own power is both coils, not its reading");
near(Object.values(out.components).reduce((s, r) => s + r.power, 0), 0, "finite W energy balance");
const sources = M.empty(); M.add(sources, "battery", 0, 0, {voltage: 6, resistance: 2}); M.add(sources, "battery", 0, 200, {voltage: 3, resistance: 1}); M.add(sources, "resistor", 300, 0);
for (const id of ["c2", "c3"]) for (const port of ["a", "b"]) M.connect(sources, "c1:" + port, id + ":" + port);
out = S.solve(sources); near(out.components.c3.voltage, 72 / 19, "multiple finite sources"); assert(out.components.c2.delivered < 0, "weaker source absorbs terminal power");
near(Object.values(out.components).reduce((s, r) => s + r.power, 0), 0, "supplying and absorbing source power balance");
// Gauge changes cannot change measurable voltage/current or energy.
const parallel = P.create("parallel"), original = S.solve(parallel); parallel.display.reference = "c1:a"; const gauged = S.solve(parallel); near(gauged.potentials["c1:a"], 0, "selected reference"); for (const id of Object.keys(original.components)) { near(gauged.components[id].current, original.components[id].current, "gauge current"); near(gauged.components[id].voltage, original.components[id].voltage, "gauge voltage"); }
// Consistent ideal-source loops have ambiguous source currents but identifiable load voltage/current.
f = simple(); const other = M.add(f.d, "battery", 0, 200); M.connect(f.d, other.id + ":a", f.b.id + ":a"); M.connect(f.d, other.id + ":b", f.b.id + ":b"); out = S.solve(f.d); assert(out.diagnostics.some((d) => d.code === "indeterminate")); assert.equal(out.components[f.b.id].current, null); near(out.components[f.r.id].current, .5, "identifiable load in ideal-source loop"); near(out.wires.w1.current, .5, "identifiable wire cut despite source ambiguity");
other.params.voltage = 8; out = S.solve(f.d); assert(out.diagnostics.some((d) => d.code === "inconsistent"));
// Wire cycles don't invent a current direction.
f = simple(); f.d.junctions.push({ id: "j1", x: 80, y: 0 }, { id: "j2", x: 100, y: 80 }); M.connect(f.d, "c1:a", "j1:p"); M.connect(f.d, "j1:p", "j2:p"); M.connect(f.d, "j2:p", "c1:a"); out = S.solve(f.d); assert.equal(out.wires.w3.current, null); near(out.wires.w1.current, .5, "wire bridge remains known");
// Unequal bridge checked independently with node-equation analytical solution.
const bridge = P.create("bridge"); bridge.components[3].params.resistance = 30; out = S.solve(bridge); const left = 1 / (1 / 10 + 1 / 30), right = 1 / (1 / 20 + 1 / 20); near(out.components.c6.current, 6 * left / (left + right) / 10 - 6 * right / (left + right) / 20, "unbalanced bridge");
// Finite voltmeter changes loading; ideal meter does not.
f = simple(); const v = M.add(f.d, "voltmeter", 0, 300, { resistance: 12 }); M.connect(f.d, v.id + ":a", f.r.id + ":a"); M.connect(f.d, v.id + ":b", f.r.id + ":b"); out = S.solve(f.d); near(out.components[f.b.id].current, -1, "finite V loading"); v.params.resistance = 0; near(S.solve(f.d).components[f.b.id].current, -.5, "ideal V loading");
f.b.params.polarity = -1; v.params.range = 3; out = S.solve(f.d); near(out.components[v.id].reading, -6, "reverse voltmeter reading"); assert(V.body(v, out.components[v.id], f.d.display).includes("超量程"));
const signedA = P.create("meters"); signedA.components[0].params.polarity = -1; signedA.components[1].params.range = .1; out = S.solve(signedA); near(out.components.c2.reading, -.5, "reverse ammeter reading"); assert(V.body(signedA.components[1], out.components.c2, signedA.display).includes("超量程"));
// Round trip every independent display enum and each actual document variant.
for (const view of ["real", "schematic"]) for (const flow of ["off", "current", "electron"]) for (const meters of ["digital", "analog"]) { const d = P.create("series"); Object.assign(d.display, { view, flow, meters, potential: true }); d.components[0].locked = true; const restored = D.decode(D.encode(d)); restored.components[1].params.closed = false; M.validate(restored); S.solve(restored); }
const malformed = (fn) => { const d = P.create("series"); fn(d); assert.throws(() => D.decode(JSON.stringify(d))); };
malformed(d => { d.components[0].type = ["battery"]; }); malformed(d => { d.components[0].type = {}; });
malformed((d) => { d.version = 2; }); malformed((d) => { d.display.flow = "charge"; }); malformed((d) => { d.components[0].x = null; }); malformed((d) => { d.components[0].params.resistance = -1; }); malformed((d) => { d.wires[0].to = "missing:a"; }); malformed((d) => { d.wires.push({ ...d.wires[0], id: "w20" }); }); malformed((d) => { d.components[1].id = d.components[0].id; }); malformed((d) => { d.policy.allowRotate = "yes"; }); malformed((d) => { d.display.reference = "unknown:a"; }); malformed((d) => { d.unknown = 1; }); malformed((d) => { delete d.components[0].params.voltage; }); assert.throws(() => D.decode("x".repeat(M.limits.bytes + 1))); assert.throws(() => D.decode("{"));
const hist = M.history(P.create("series")), before = D.encode(hist.get()); assert.throws(() => hist.change((d) => { d.wires[0].to = "missing:a"; })); assert.equal(D.encode(hist.get()), before, "invalid edits atomic"); hist.change((d) => M.remove(d, "c1")); assert.equal(hist.get().wires.length, 2); hist.undo(); assert.equal(D.encode(hist.get()), before); hist.redo(); assert.equal(hist.get().components.length, 3);
const locked = P.create("wiring"); assert.equal(M.permission(locked, locked.components[0], "move"), false); assert.throws(() => M.add(locked, "resistor", 0, 0)); assert.throws(() => M.remove(locked, "c1")); locked.policy.allowRotate = true; assert.equal(M.permission(locked, locked.components[0], "rotate"), true); locked.components[0].editable = true; assert.equal(M.permission(locked, locked.components[0], "params"), true);
const series = P.create("series"), wire = series.wires[0], route = G.route(series, wire), p = G.nearest(route, { x: 180, y: 220 }); const junction = M.splitWire(series, wire.id, p, route); M.validate(series); const result = S.solve(series); near(result.components.c1.current, -.25, "split preserves topology"); assert(M.endpoints(series).has(junction));
series.components[1].x += 40; series.components[1].angle = 90; near(S.solve(series).components.c1.current, -.25, "geometry doesn't change topology"); for (const wire of series.wires) { const route = G.route(series, wire); route.slice(1).forEach((p, i) => assert(p.x === route[i].x || p.y === route[i].y, "orthogonal")); }
series.components[0].label = '<script>bad & "</script>'; const html = V.scene(series, S.solve(series)); assert(!html.includes("<script>")); assert(html.includes("&lt;script&gt;")); assert.equal(XMLValidator.validate(`<svg xmlns="http://www.w3.org/2000/svg">${html}</svg>`), true, "exported SVG is valid XML");
assert.equal(D.template(series).policy.mode, "wiring"); assert.equal(D.template(series).wires.length, 0);
console.log("Circuit core: analytical networks, thermal calibration, signed meters, ambiguous/floating/short cases, energy, round trips, atomic validation, routing and history passed.");
// Restorable unsolved work stays editable, and repair is a legal continuation.
let broken = simple(); M.connect(broken.d, broken.b.id + ':a', broken.b.id + ':b'); const savedBroken = D.decode(D.encode(broken.d)); assert(S.solve(savedBroken).diagnostics.length); savedBroken.components[0].params.resistance = 1; assert.equal(S.solve(savedBroken).diagnostics.length, 0);
let seed = 87; const rand = () => { seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0; return seed / 2 ** 32; };
for (let n = 0; n < 50; n++) {
  const d = M.empty(), source = M.add(d, 'battery', 0, 0, { voltage: .1 + rand() * 119, resistance: rand() * 10 });
  d.junctions.push({id:'j1',x:200,y:0},{id:'j2',x:400,y:0},{id:'j3',x:400,y:200});
  const connections = [['c1:a','j1:p'],['c1:a','j2:p'],['j1:p','j2:p'],['j1:p','j3:p'],['j2:p','j3:p'],['j3:p','c1:b']];
  const kcl = Object.fromEntries(['j1:p','j2:p','j3:p'].map(k=>[k,0]));
  for (const [a,b] of connections) { const c = M.add(d, n>=35 && rand()>.5 ? 'lamp' : 'resistor', 200, 200, n>=35 ? undefined : { resistance: .1 + rand()*100 }); if(c.type==='lamp')c.params.model='thermal'; M.connect(d,c.id+':a',a); M.connect(d,c.id+':b',b); }
  const result = S.solve(d); assert.equal(result.diagnostics.length, 0, 'random arbitrary network'); const load = d.components.slice(1);
  load.forEach((c,i)=>{const [a,b]=connections[i];if(a in kcl)kcl[a]+=result.components[c.id].current;if(b in kcl)kcl[b]-=result.components[c.id].current;}); Object.values(kcl).forEach(v=>near(v,0,'independent junction KCL',1e-6));
  near(Object.values(result.components).reduce((s,r)=>s+r.power,0),0,'network power conservation',1e-6); assert(result.residual<1e-8);
}
for (const name of Object.keys(P.names)) for (const view of ['real','schematic']) for(const meters of ['digital','analog']) { const d=P.create(name); Object.assign(d.display,{view,meters,potential:true}); const r=S.solve(d),routes=Object.fromEntries(d.wires.map(w=>[w.id,G.route(d,w)])); assert.equal(XMLValidator.validate(`<svg xmlns="http://www.w3.org/2000/svg">${V.scene(d,r,.65,routes)}${V.flow(d,r,routes,1,.65)}</svg>`),true,'all diagram exports valid'); }
const backwards = simple(); backwards.b.params.polarity=-1; const reversed=S.solve(backwards.d); near(reversed.components.c2.current,-.5,'reversed source'); near(reversed.components.c1.delivered,3,'reversed source delivery'); assert.equal(R.ports(backwards.b)[0].label,'−');
near(reversed.potentials['c1:a'],0,'automatic reference follows reversed negative terminal'); near(reversed.potentials['c1:b'],6,'reversed positive terminal potential');
console.log('Circuit extended verification: 50 arbitrary networks, nonlinear KCL/energy, repair continuation and all SVG variants passed.');
// A new nonlinear, four-port device is defined entirely through registry hooks.
R.register('two-loads',{name:'雙負載模型',icon:'T',ports:[{key:'p',x:-60,y:0,label:'p'},{key:'q',x:60,y:0,label:'q'},{key:'r',x:-60,y:60,label:'r'},{key:'s',x:60,y:60,label:'s'}],params:{resistance:{value:12,min:.1,max:100}},dc:c=>[{from:'p',to:'q',kind:'nonlinear',law:(v,p)=>({current:v/p.resistance+.001*v**3,conductance:1/p.resistance+.003*v**2})},{from:'r',to:'s',kind:'resistor',resistance:c.params.resistance}]});
const extension=M.empty();M.add(extension,'battery',0,0);const newDevice=M.add(extension,'two-loads',300,0);for(const [a,b] of [['p','a'],['q','b'],['r','a'],['s','b']])M.connect(extension,newDevice.id+':'+a,'c1:'+b);const extended=S.solve(D.decode(D.encode(extension)));assert.equal(extended.diagnostics.length,0);near(extended.components[newDevice.id].current,.5+.001*6**3,'nonlinear extension hook');near(extended.components.c1.current,-1-.001*6**3,'multi-port extension KCL');
near(extended.components[newDevice.id].power, 6 * (1 + .001 * 6 ** 3), 'multi-port total power'); near(extended.components.c1.power + extended.components[newDevice.id].power, 0, 'multi-port energy');
console.log('Circuit registry: a new nonlinear multi-port device solves without changing solver or document code.');
// A valid local constitutive law with no finite DC equilibrium exercises the bounded failure path.
R.register('no-equilibrium',{name:'收斂診斷測試',icon:'T',ports:R.get('resistor').ports,params:{},dc:()=>[{from:'a',to:'b',kind:'nonlinear',law:v=>({current:Math.exp(v)+1,conductance:Math.exp(v)})}]});
const nonconvergent=simple().d;const failing=M.add(nonconvergent,'no-equilibrium',600,400);const failure=S.solve(D.decode(D.encode(nonconvergent)));assert(failure.diagnostics.some(d=>d.code==='convergence'),'bounded nonlinear failure is diagnosed');assert.equal(failure.components[failing.id].current,null);assert.equal(failure.components[failing.id].power,null);near(failure.components.c2.current,.5,'independent circuit survives nonlinear failure');
const repaired=M.history(nonconvergent);repaired.change(d=>M.remove(d,failing.id));assert.equal(S.solve(repaired.get()).diagnostics.length,0,'failed nonlinear work remains repairable');
console.log('Circuit nonlinear failure: iteration limit, unknown results, independent circuit and repair continuation passed.');
