'use strict';
const assert=require('node:assert/strict');
const M=require('./circuit-model'),R=require('./component-registry'),S=require('./circuit-solver'),D=require('./circuit-document'),V=require('./circuit-renderer'),N=require('./circuit-meter-motion');
let cases=0;
const test=(name,fn)=>{fn();cases++;};
const close=(a,b,tolerance=1e-8)=>assert(Math.abs(a-b)<=tolerance,`${a} != ${b}`);
function setup(type='ammeter',range=3){const d=M.empty(),c=M.add(d,type,200,200,{range}),states=new Map(),result={components:{[c.id]:{reading:null,range,meterStatus:'unconnected'}}};N.sync(states,d,result);return{d,c,states,result,state:states.get(c.id)};}
function aim(f,reading,range=f.c.params.range){f.result.components[f.c.id]={reading,range,meterStatus:reading<0?'reverse':'normal'};N.sync(f.states,f.d,f.result);}
function trace(f,seconds=2,fps=60){const out=[];for(let i=0;i<seconds*fps;i++){N.advance(f.states,1/fps);out.push(f.state.fraction);}return out;}
for(const type of ['ammeter','voltmeter']){
  test(type+' unconnected at zero without a fabricated numeric reading',()=>{const f=setup(type),solved=S.solve(f.d);assert.equal(solved.components[f.c.id].reading,null);N.sync(f.states,f.d,solved);close(f.state.fraction,0);assert.equal(f.state.target,0);const svg=V.dualDial(f.c,solved.components[f.c.id]);assert(svg.includes('data-angle="-120"'));assert(svg.includes('data-reading=""'));assert(!V.dualDial(f.c,solved.components[f.c.id],false).includes('data-meter-needle'));});
  test(type+' zero-to-reading overshoots, returns repeatedly and settles exactly',()=>{const f=setup(type);aim(f,.6);close(f.state.fraction,0);const p=trace(f);assert(Math.max(...p)>.24,'visible overshoot beyond 0.6 on the 3-unit range');let crossings=0;for(let i=1;i<p.length;i++)if((p[i]-.2)*(p[i-1]-.2)<0)crossings++;assert(crossings>=4,'several diminishing swings');assert(Math.max(...p.slice(60).map(v=>Math.abs(v-.2)))<.002,'motion is strongly damped');close(f.state.fraction,.2);close(f.state.velocity,0);});
  test(type+' changing target preserves angle and velocity',()=>{const f=setup(type);aim(f,.6);trace(f,.1);const before={...f.state};aim(f,-.3);assert.equal(f.state.fraction,before.fraction);assert.equal(f.state.velocity,before.velocity);close(f.state.target,-.1);N.advance(f.states,1/60);assert(Math.abs(f.state.fraction-before.fraction)<.04);trace(f);close(f.state.fraction,-.1);close(f.state.velocity,0);});
  test(type+' range changes retarget same physical needle',()=>{const f=setup(type);aim(f,.6);trace(f);aim(f,.6,.6);close(f.state.fraction,.2);close(f.state.target,1);const p=trace(f);assert(p.some(v=>v>1),'full scale has a small allowed overshoot');assert(p.every(v=>v<=N.maximum&&v>=N.minimum));close(f.state.fraction,1);});
  test(type+' positive and negative overloads cannot cross mechanical stops',()=>{for(const reading of [1000,-1000]){const f=setup(type);aim(f,reading);const p=trace(f);assert(p.every(v=>v<=N.maximum&&v>=N.minimum));close(f.state.fraction,reading>0?N.maximum:N.minimum);}});
  test(type+' unplug returns through zero while unknown results stay hidden',()=>{const f=setup(type);aim(f,.6);trace(f);f.result.components[f.c.id]={reading:null,range:3,meterStatus:'unconnected'};N.sync(f.states,f.d,f.result);close(f.state.fraction,.2);const p=trace(f);assert(Math.min(...p)<-.04);close(f.state.fraction,0);for(const meterStatus of ['unknown','dual-positive']){f.result.components[f.c.id]={reading:null,range:3,meterStatus};N.sync(f.states,f.d,f.result);assert.equal(f.state.target,null);assert(!V.dualDial(f.c,f.result.components[f.c.id]).includes('data-meter-needle'));}});
}
test('30/60/120 fps use the same oscillator trajectory',()=>{const finals=[];for(const fps of [30,60,120]){const f=setup();aim(f,.6);trace(f,.5,fps);finals.push({...f.state});}for(const f of finals){close(f.fraction,finals[0].fraction);close(f.velocity,finals[0].velocity);}});
test('pause, invalid time and reduced motion',()=>{const f=setup();aim(f,.6);trace(f,.15);const before={...f.state};for(const dt of [0,-1,NaN,Infinity]){assert.equal(N.advance(f.states,dt),false);assert.deepEqual(f.state,before);}N.sync(f.states,f.d,f.result,true);close(f.state.fraction,.2);close(f.state.velocity,0);const a=setup(),b=setup();aim(a,.6);aim(b,.6);N.advance(a.states,20);N.advance(b.states,.05);assert.deepEqual(a.state,b.state,'long background interval is capped');});
test('motion is transient and deletion/loading cannot leak old velocity',()=>{const f=setup(),saved=D.encode(f.d);aim(f,.6);trace(f,.1);assert.equal(D.encode(f.d),saved);const restored=D.decode(saved);restored.components[0].params.range=.6;M.validate(restored);N.sync(f.states,{...f.d,components:[]},{components:{}});assert.equal(f.states.size,0);N.sync(f.states,restored,{components:{c1:{reading:.3,range:.6,meterStatus:'normal'}}});close(f.states.get('c1').fraction,0);close(f.states.get('c1').velocity,0);assert.equal(f.states.get('c1').target,.5);});
test('non AV meters retain their existing rendering and stable SVG uses exact target',()=>{const d=M.empty();M.add(d,'galvanometer',0,0);M.add(d,'wattmeter',200,0);const states=new Map();N.sync(states,d,S.solve(d));assert.equal(states.size,0);const f=setup('voltmeter',15);aim(f,3);const svg=V.dualDial(f.c,f.result.components.c1);assert(svg.includes('data-target-fraction="0.2"'));assert(svg.includes('data-angle="-102"'));});
console.log(`Meter motion: ${cases} focused cases passed; zero, overshoot/damping, continuous retargeting, ranges/stops, timing, pause/reduced motion and transient state.`);
