const assert=require('node:assert/strict'),M=require('./circuit-model'),O=require('./circuit-observation'),T=require('./circuit-transient'),P=require('./circuit-ac-presets'),F=require('./circuit-profile'),G=require('./circuit-routing');
const doc=P.create('resistive'),session=new T.Session(doc);session.advance(.125);const result=session.read(),profile=F.compile({role:'teacher',analysis:'transient',palette:[],initialDocument:doc}),probe=target=>({position:{x:100,y:200},target,bends:[]}),tool=(kind,probes)=>({id:'scope-1',kind,x:32,y:8,width:260,height:210,range:10,span:2,probes});
const voltage=tool('voltage',[probe({kind:'endpoint',id:'c1:a'}),probe({kind:'endpoint',id:'c1:b'})]),current=tool('current',[probe({kind:'wire',id:'w1',fraction:.4})]);
assert(O.validateTools([voltage],doc,profile));assert(Math.abs(O.signal(voltage,result,doc)-result.components.c1.voltage)<1e-10);assert.equal(O.signal(current,result,doc),result.wires.w1.current);assert.equal(O.signal({...voltage,probes:[probe(null),voltage.probes[1]]},result,doc),null);
const before=session.capture();const snapshot=JSON.parse(JSON.stringify([voltage,current].map((t,i)=>({...t,id:'scope-'+(i+1)}))));assert.deepEqual(O.validateTools(snapshot,doc,profile),snapshot);for(const edit of [t=>t[0].probes[0].target.id='missing',t=>t[0].width=10,t=>t[0].span=0,t=>t[0].unknown=true,t=>t[1].id=t[0].id,t=>t.push({...t[0],id:'scope-3'}),t=>t[0].probes[0].bends=Array(33).fill({x:0,y:0}),t=>t[0].probes[0].position.x=NaN]){const bad=M.clone(snapshot);edit(bad);assert.equal(O.validateTools(bad,doc,profile),null);}assert.deepEqual(session.capture(),before);
const fixed=F.compile({role:'student',analysis:'transient',palette:[],initialDocument:doc,ui:{waveform:true},observationChannels:[{id:'c1',quantity:'voltage'},{id:'c3',quantity:'voltage'}],observationLimit:1});assert(O.validateTools([voltage],doc,fixed));assert.equal(O.validateTools([current],doc,fixed),null);const mixed=M.clone(voltage);mixed.probes[1].target.id='c3:b';assert.equal(O.validateTools([mixed],doc,fixed),null);assert.equal(O.validateTools([voltage],doc,{...fixed,ui:{waveform:false}}),null);for(const observationLimit of [-1,5,1.2,'2'])assert.throws(()=>F.compile({observationLimit}));
const td=P.create('transformer'),ts=new T.Session(td),isolated=tool('voltage',[probe({kind:'endpoint',id:'c2:a'}),probe({kind:'endpoint',id:'c2:c'})]);assert.equal(O.signal(isolated,ts.read(),td),null);const unknown=M.clone(result);unknown.wires.w1.current=null;assert.equal(O.signal(current,unknown,doc),null);
const paths=Object.fromEntries(doc.wires.map(w=>[w.id,G.route(doc,w)])),position=O.probePosition(current.probes[0],doc,paths),snap=O.snapProbe({...current,probes:[probe(null)]},0,position,doc,paths,1,null);assert(snap);assert.equal(snap.target.kind,'wire');assert.equal(O.snapProbe({...current,probes:[probe(null)]},0,position,doc,paths,1,fixed.observationChannels),null);const distant=M.clone(voltage);distant.probes[0].position={x:9999,y:-9999};distant.probes[0].target=null;distant.probes[0].bends=[{x:3000,y:2000}];assert(O.validateTools([distant],doc,profile),'probe cables are not limited by electrical cable stock or length');
const trace=new O.Trace(2);for(let i=0;i<20000;i++)trace.sample(i/10000,i===19001?100:Math.sin(i/100));assert(trace.bins.length<=1025);assert(trace.points().some(p=>p.value===100),'display bins must retain sampled spikes');trace.sample(2,null);trace.sample(2.1,1);assert(trace.points().some(p=>p.value===null));trace.sample(.1,3);assert.equal(trace.points().at(-1).value,3);assert(trace.points().every(p=>p.time<=.1),'time reset discards old history');const event=new O.Trace(1);event.sample(.5,1);event.sample(.5,2);assert(event.points().some(p=>p.value===1)&&event.points().some(p=>p.value===2),'same-time switching events keep the jump');
console.log('Scope probes: voltage/current truth, isolation/unknowns, stock-independent cables, snap permissions, atomic configuration round-trip, bounded extrema/gaps and event timing passed');

const cap=P.create('lc'),energy={...voltage,kind:'energy',probes:[],channel:{id:'c4'}},capProfile=F.compile({role:'teacher',analysis:'transient',palette:[],initialDocument:cap});assert(O.validateTools([energy],cap,capProfile));assert.equal(O.validateTools([{...energy,probes:Array(100).fill(probe(null))}],cap,capProfile),null);

assert.equal(O.timeInterval(5),2);assert.equal(O.timeInterval(1),.5);assert.equal(O.timeInterval(.01),.005);for(const span of [.00001,.03,2,20,1000])assert(O.timeInterval(span)>0&&O.timeInterval(span)<=span/2*(1+1e-12));
for(const view of ['real','schematic']){const d=P.create('resistive');d.display.view=view;for(const id of ['c2','c3']){const V=require('./circuit-renderer'),path=V.componentFlowPaths(d,{components:{}}).find(p=>p.component===id),at=G.along(path.points,G.length(path.points)*.5),bound=O.snapProbe({...current,probes:[probe(null)]},0,at,d,{},1,null);assert.equal(bound.target.kind,'component');assert.equal(bound.target.id,id);assert(bound.target.fraction>0&&bound.target.fraction<1);assert(Math.hypot(O.probePosition({target:bound.target},d).x-at.x,O.probePosition({target:bound.target},d).y-at.y)<1e-8);}}

// Rescaling restores older observations rather than stretching only the last small window.
{const t=new O.Trace(2);for(let n=0;n<=3000;n++)t.sample(n/100,Math.sin(n/100));t.setSpan(20);assert(t.points()[0].time<=10.02);assert(t.points().at(-1).time===30);t.setSpan(.5);t.setSpan(20);assert(t.points()[0].time<=10.02);const before=t.points(),copy=t.copy();copy.sample(30.1,99);assert.deepEqual(t.points(),before);assert(copy.points().some(p=>p.value===99));}
{const t=new O.Trace(.02);for(let n=0;n<=100000;n++)t.sample(n/1000,n===5001?100:Math.sin(n/100));assert(t.history.length<=8192);t.setSpan(100);assert(t.points()[0].time===0);assert(t.points().some(p=>p.value===100));assert(t.points().length<=4100);t.sample(101,null);t.setSpan(100);assert(t.points().some(p=>p.value===null));t.sample(.1,3);assert(t.history.every(b=>b.last.time<=.1));assert.deepEqual(t.points(),[{time:.1,value:3}]);}

{const t=new O.Trace(2);for(let n=0;n<=1100;n++)t.sample(n,Math.sin(n));assert(t.history[0].last.time>=100);assert(t.history.length<=8192);t.setSpan(1000);assert(t.points()[0].time>=100);}

// Peak observations retain pulse maxima and signs without changing RMS integration.
{const t=new O.Tracker(1),sample=(time,i)=>t.sample({time,components:{c1:{voltage:2,current:i}},wires:{}});sample(0,0);sample(.25,3);sample(.5,-4);sample(.75,0);sample(1,0);assert.equal(t.measure('c1').currentPeak,4);sample(2,0);sample(2.1,0);assert.equal(t.measure('c1').currentPeak,0);assert.equal(t.measure('c1').currentRms,0);}
