'use strict';
const assert=require('node:assert/strict'),M=require('./circuit-model'),S=require('./circuit-solver'),T=require('./circuit-transient'),AC=require('./circuit-ac-components'),O=require('./circuit-observation');
const close=(actual,expected,absolute=1e-8,relative=.005)=>assert.ok(Number.isFinite(actual)&&Math.abs(actual-expected)<=Math.max(absolute,Math.abs(expected)*relative),`${actual} != ${expected}`);
function fixture(){const d=M.empty('transient');return {d,add:(type,params={},x=100+d.components.length*160,y=180)=>M.add(d,type,x,y,params),link:(a,b,ap='a',bp='b')=>M.connect(d,a.id+':'+ap,b.id+':'+bp)};}
function series(type,resistance,params={}){const f=fixture(),b=f.add('battery'),r=f.add('resistor',{resistance}),c=f.add(type,{...(type==='capacitor'?{capacitance:.001}:{}),...params});f.link(b,r,'a','a');f.link(r,c,'b','a');f.link(c,b,'b','b');return {...f,b,r,c};}
function lc(resistance=0){const f=fixture(),c=f.add('capacitor',{capacitance:.001,initialVoltage:6}),l=f.add('inductor',{resistance});f.link(c,l,'a','a');f.link(c,l,'b','b');return {...f,c,l};}
function ac(waveform='sine',type='resistor',params={}){const f=fixture(),source=f.add('ac-source',{frequency:5,waveform}),load=f.add(type,{...(type==='resistor'?{resistance:12}:{}),...params});f.link(source,load,'a','a');f.link(source,load,'b','b');return {...f,source,load};}

// Analytic RC and RL, followed by production checkpoint restore and a legal parameter event.
for(const type of ['capacitor','inductor']){const f=series(type,type==='capacitor'?1000:12),s=new T.Session(f.d),tau=type==='capacitor'?1:1/13;s.advance(tau);assert.equal(s.fault,null);close(s.read().components[f.c.id][type==='capacitor'?'voltage':'current'],(type==='capacitor'?6:6/13)*(1-Math.exp(-1)));
  const restored=T.Session.restore(JSON.parse(JSON.stringify(s.capture())));assert.equal(restored.state.time,s.state.time);assert.deepEqual(restored.state.dynamic,s.state.dynamic);const next=M.clone(f.d);next.components.find(c=>c.id===f.r.id).params.resistance*=2;s.update(next);restored.update(next);s.advance(tau/2);restored.advance(tau/2);close(restored.read().components[f.c.id].current,s.read().components[f.c.id].current,1e-10,1e-8);}

// LC quarter-cycle values, long-run energy, frame chunking, damping and passive energy balance.
// Expanded teaching limits still obey analytic time constants and recover stored energy.
{const f=series('capacitor',5,{capacitance:.2}),s=new T.Session(f.d);s.advance(1);assert.equal(s.fault,null);close(s.read().components[f.c.id].voltage,6*(1-Math.exp(-1)));const restored=T.Session.restore(s.capture());s.advance(1);restored.advance(1);close(restored.read().components[f.c.id].voltage,s.read().components[f.c.id].voltage,1e-10,1e-8);
 const g=lc();g.c.params.capacitance=.2;g.l.params.inductance=10;const oscillation=new T.Session(g.d),energy=oscillation.read().energy;oscillation.advance(2*Math.PI*Math.sqrt(2)/4);assert.equal(oscillation.fault,null);close(oscillation.read().components[g.c.id].voltage,0,.001);close(oscillation.read().components[g.l.id].current,6*Math.sqrt(.2/10));close(oscillation.read().energy,energy,1e-8,.005);}
{const f=lc(),period=2*Math.PI*Math.sqrt(.001),s=new T.Session(f.d),initial=s.read().energy;s.advance(period/4);close(s.read().components[f.l.id].current,6*Math.sqrt(.001));close(s.read().components[f.c.id].voltage,0,.001);const checkpoint=s.capture(),restored=T.Session.restore(checkpoint);s.advance(period*99.75);assert.equal(s.fault,null);close(s.read().energy,initial,1e-10,.005);restored.advance(period/4);assert.ok(restored.read().components[f.c.id].voltage< -5.99);
  const direct=new T.Session(f.d),chunks=new T.Session(f.d);direct.advance(period*2);for(let i=0;i<120;i++)chunks.advance(period*2/120);close(chunks.read().components[f.c.id].voltage,direct.read().components[f.c.id].voltage,1e-4,.001);close(chunks.read().energy,direct.read().energy,1e-7,.001);
  for(const resistance of [1,2*Math.sqrt(1/.001),100]){const damped=new T.Session(lc(resistance).d);damped.advance(period*3);assert.equal(damped.fault,null);assert.ok(damped.read().energy<initial);close(damped.read().energy+damped.read().dissipatedEnergy,initial,1e-6,.005);}}

// Source RMS comes from integration, including discontinuous waveforms and average power.
for(const waveform of ['sine','square','triangle']){const f=ac(waveform),s=new T.Session(f.d);s.advance(.6);assert.equal(s.fault,null);const q=s.read().measurements[f.load.id];assert.equal(q.status,'ready');close(q.voltageRms,6);close(q.currentRms,.5);close(q.averagePower,3);}
{const f=ac(),s=new T.Session(f.d);s.advance(.037);const before=s.state.sources[f.source.id],changed=M.clone(f.d);changed.components[0].params.frequency=10;s.update(changed);close(s.state.sources[f.source.id],before,1e-12,0);assert.equal(s.read().measurements[f.load.id].status,'collecting');}

// Phase tests use explicitly compatible sinusoidal initial states, not a lossless circuit's arbitrary start-up offset.
for(const type of ['capacitor','inductor']){const frequency=5,w=2*Math.PI*frequency,peak=6*Math.sqrt(2),f=ac('sine',type,type==='capacitor'?{capacitance:.001,initialVoltage:0}:{inductance:1,resistance:0,initialCurrent:-peak/w}),s=new T.Session(f.d),buffer=new O.Buffer(4096);s.subscribe(r=>buffer.sample(r));s.advance(.6);assert.equal(s.fault,null);const delta=O.phase(buffer.points,{id:f.source.id,quantity:'voltage'},{id:f.load.id,quantity:'current'},frequency);close(delta,type==='capacitor'?90:-90,1,.005);}

// Ideal transformer load, power and the electrical isolation of the two references.
{const f=fixture(),source=f.add('ac-source',{frequency:5}),t=f.add('transformer'),r=f.add('resistor',{resistance:12});f.link(source,t,'a','a');f.link(source,t,'b','b');f.link(t,r,'c','a');f.link(t,r,'d','b');const s=new T.Session(f.d);s.advance(.6);assert.equal(s.fault,null);close(s.read().measurements[r.id].voltageRms,3);close(s.read().measurements[t.id].currentRms,.125);close(s.read().measurements[r.id].averagePower,.75);assert.equal(s.read().voltage(t.id+':a',t.id+':c'),null);const d=M.clone(f.d);d.components[0].type='battery';d.components[0].params=RDefaults('battery');const invalid=new T.Session(d);assert.equal(invalid.fault,'dc-transformer');}
function RDefaults(type){return require('./component-registry').defaults(type);}

// Coupled coils: switch-off retains both currents, has a visible discharge loop, reverses induced voltage.
{const f=fixture(),source=f.add('battery'),sw=f.add('switch',{closed:false}),t=f.add('transformer',{model:'coupled',primaryResistance:12,secondaryResistance:1}),primary=f.add('resistor',{resistance:100}),secondary=f.add('resistor',{resistance:100});f.link(source,sw,'a','a');f.link(sw,t,'b','a');f.link(source,t,'b','b');f.link(t,primary,'a','a');f.link(t,primary,'b','b');f.link(t,secondary,'c','a');f.link(t,secondary,'d','b');const s=new T.Session(f.d),on=M.clone(f.d);on.components.find(c=>c.id===sw.id).params.closed=true;s.update(on);s.advance(.001);const onVoltage=s.read().components[t.id].secondaryVoltage;s.advance(2);assert.equal(s.fault,null);assert.ok(Math.abs(s.read().components[t.id].secondaryVoltage)<.001);const currents=M.clone(s.state.dynamic),off=M.clone(on);off.components.find(c=>c.id===sw.id).params.closed=false;s.update(off);for(const k of Object.keys(currents))close(s.state.dynamic[k].i,currents[k].i,1e-10,1e-8);s.advance(.001);assert.equal(s.fault,null);assert.ok(s.read().components[t.id].secondaryVoltage*onVoltage<0);s.advance(1);assert.ok(s.read().energy<1e-5);}

// SPDT charges then oscillates with charge continuity. Events run through the same production Session.
{const f=fixture(),b=f.add('battery'),r=f.add('resistor',{resistance:10}),sw=f.add('spdt'),c=f.add('capacitor',{capacitance:.001}),l=f.add('inductor',{resistance:0});f.link(b,r,'a','a');f.link(r,sw,'b','b');f.link(sw,c,'a','a');f.link(sw,l,'c','a');f.link(c,l,'b','b');f.link(b,c,'b','b');const s=T.run(f.d,{events:[{time:.1,command:{type:'toggleSwitch',id:sw.id}}],until:.15});assert.equal(s.fault,null);assert.ok(s.read().components[l.id].current>.18);assert.equal(s.doc.components.find(c=>c.id===sw.id).params.closed,'c');}

// LED direction and generator emf/flux use actual branch equations.
// LED discharge needs a forward path and series resistance; a reversed LED blocks it.
{for(const reverse of [false,true]){const f=fixture(),c=f.add('capacitor',{capacitance:.02,initialVoltage:6}),r=f.add('resistor',{resistance:220}),led=f.add('led');f.link(c,r,'a','a');f.link(r,led,'b',reverse?'b':'a');f.link(led,c,reverse?'a':'b','b');const s=new T.Session(f.d);s.advance(.05);assert.equal(s.fault,null);if(reverse){close(s.read().components[led.id].current,0);s.advance(5);close(s.read().components[c.id].voltage,6);}else{close(s.read().components[led.id].current,(6-1.8)/230*Math.exp(-.05/(230*.02)));s.advance(4.95);close(s.read().components[led.id].current,(6-1.8)/230*Math.exp(-5/(230*.02)));s.advance(30);close(s.read().components[c.id].voltage,1.8,.005);assert(s.read().components[led.id].current<.00001,'LED fades before the capacitor reaches zero voltage');}}}
{const f=ac('sine','resistor',{resistance:100}),red=f.add('led'),green=f.add('led',{colour:'green'});const d=f.d;d.wires=d.wires.filter(w=>w.id!=='w2');f.link(f.load,red,'b','a');f.link(red,f.source,'b','b');f.link(green,red,'b','a');f.link(green,red,'a','b');const s=new T.Session(d);s.advance(.05);assert.equal(s.fault,null);assert.ok(s.read().components[red.id].current>0);close(s.read().components[green.id].current,0);s.advance(.1);assert.ok(s.read().components[green.id].current>0);close(s.read().components[red.id].current,0);}
{const f=fixture(),g=f.add('generator'),r=f.add('resistor');f.link(g,r,'a','a');f.link(g,r,'b','b');const s=new T.Session(f.d);close(s.read().components[g.id].sourceEmf,0);close(s.read().components[g.id].flux,.004);s.advance(.125);close(s.read().components[g.id].sourceEmf,200*.2*.02*4*Math.PI);close(s.read().components[g.id].flux,0,1e-10);}

// Partial work is valid; singular physics and malformed snapshots fail without fake readings.
{const f=lc(),s=new T.Session(f.d);s.advance(.01);const original=s.capture();for(const mutate of [x=>x.version=2,x=>x.physics.time=-1,x=>x.physics.extra=1,x=>x.physics.dynamic.bad={i:0,v:0},x=>x.physics.dynamic[f.c.id+':a'].v=Infinity,x=>x.physics.dynamic[f.l.id+':a'].v+=10,x=>x.document.modelRevision=2]){const bad=M.clone(original);mutate(bad);assert.throws(()=>T.Session.restore(bad));}assert.deepEqual(s.capture(),original);
  const short=M.clone(f.d);M.connect(short,f.c.id+':a',f.c.id+':b');const failed=new T.Session(short);assert.equal(failed.fault,'inconsistent');assert.equal(failed.read().components[f.c.id].current,null);const restored=T.Session.restore(failed.capture());assert.equal(restored.fault,'inconsistent');
  const empty=new T.Session(M.empty('transient'));empty.advance(.1);assert.equal(empty.fault,null);assert.equal(empty.read().time,.1);assert.throws(()=>S.solve(f.d));assert.throws(()=>M.validate({...f.d,version:6}));assert.throws(()=>AC.toAC({...M.empty(),components:[M.component(M.empty(),'relay',100,100)]}));}
console.log('AC transient: analytic physics, integration, events, phase, transformer isolation, energy, snapshots and failure cases passed');
{const f=series('capacitor',1000),second=f.add('capacitor',{capacitance:.002});f.link(f.c,second,'a','a');f.link(f.c,second,'b','b');const s=new T.Session(f.d);s.advance(.123);const saved=s.capture(),restored=T.Session.restore(saved);for(const c of [f.c,second])close(restored.read().components[c.id].current,s.read().components[c.id].current,1e-10,1e-8);s.advance(.1);restored.advance(.1);close(restored.read().components[second.id].voltage,s.read().components[second.id].voltage,1e-9,1e-8);}
{const f=series('inductor',12,{initialCurrent:.1}),led=f.add('led');f.d.wires=f.d.wires.filter(w=>w.id!=='w3');f.link(f.c,led,'b','a');f.link(led,f.b,'b','b');const s=new T.Session(f.d);assert.equal(s.fault,null);s.advance(.01);const restored=T.Session.restore(s.capture());assert.equal(restored.fault,null);const next=M.clone(s.doc);next.components.find(c=>c.id===f.r.id).params.resistance=20;restored.update(next);assert.equal(restored.fault,null);restored.advance(.01);assert.equal(restored.fault,null);}
{const f=ac(),d=M.clone(f.d);d.components[0].params.voltage=220;const s=new T.Session(d);s.advance(.4);close(s.read().measurements[f.load.id].voltageRms,220);close(s.read().components[f.source.id].sourceEmf,0,1e-8);}
{const P=require('./circuit-ac-presets'),normal=new T.Session(P.create('mains'));normal.advance(.04);assert.equal(normal.read().hazards.overload,false);const lamp=normal.doc.components.find(c=>c.type==='lamp');close(normal.read().components[lamp.id].displayPower,3);const hot=M.clone(normal.doc);hot.components[0].params.voltage=12;normal.update(hot);normal.advance(.04);assert.equal(normal.read().hazards.components[lamp.id],'overload');
 const self=new T.Session(P.create('self')),closed=M.clone(self.doc);closed.components.find(c=>c.type==='switch').params.closed=true;self.update(closed);self.advance(.03);assert.ok(self.read().components[closed.components.find(c=>c.type==='lamp').id].displayPower>0,'DC transient lamp becomes visible before one second');
 assert.throws(()=>T.run(lc().d,{events:[{time:.01,command:{type:'setParam',id:'c1',key:'capacitance',value:.002}}],until:.02}));}
