"use strict";
const assert=require("node:assert/strict"),P=require("./persistence.js"),U=require("./ui-policy.js"),App=require("./main.js"),G=require("./generator.js"),S=require("./scoring.js"),Flow=require("../shared/activity-flow.js");
for(const key of ["review","editable","frozen","load-error"])assert.equal(P.lifecyclePolicy("startup",key).editable,key==="editable");
assert.deepEqual(U.startupView("frozen"),{editable:false,locked:true,mode:"pending"});
for(const activityState of ["success","committed","frozen","retry"]){const outcome={activityState,retryable:true},view=U.submissionView(outcome);assert.equal(view.showScore,["success","committed"].includes(activityState));assert.equal(view.locked,activityState!=="retry");}
let state=P.initial(9),problem=G.generate(9);state=P.release(state,problem.part1.xCm);state=P.markPart1(state,problem.part1.xCm);state=P.switchPart(state,2);for(const key of ["h1","h2"]){state=P.settleHole(state,key);state=P.traceVertical(state);state=P.detachActiveHole(state);}state=P.markPart2(state,problem.part2.centre);state=P.switchPart(state,3);state=P.setView(state,{yaw10:650,pitch10:-180});state=P.setView(state,{yaw10:1100,pitch10:220});state=P.selectPart3(state,problem.part3.correctKey);state=P.enterCheck(state);const answer=P.makeReview(state),result=S.score(answer),snapshot={version:1,activity:App.ACTIVITY,kind:"review",answer,score:result.score,passed:result.passed},payload={reviewJson:JSON.stringify(snapshot),score:result.score,maxScore:100,passed:result.passed};assert.equal(App.reviewMatches(snapshot,payload,result),true);const changed=structuredClone(snapshot);changed.answer.part1.markX+=.001;assert.equal(App.reviewMatches(changed,payload,result),false,"canonical pending rejects same aggregate with changed answer");
const legacyAnswer={...structuredClone(answer),v:1,variant:"submitted",returnToCheck:false},legacySnapshot={...snapshot,answer:legacyAnswer},legacyPayload={...payload,reviewJson:JSON.stringify(legacySnapshot)};assert.equal(P.fromReview(legacyAnswer).v,2);assert.equal(App.reviewMatches(legacySnapshot,legacyPayload,result),true,"strict legacy review is accepted after migration and rescoring");assert.equal(App.reviewMatches(legacySnapshot,{...legacyPayload,reviewJson:` ${legacyPayload.reviewJson}`},result),false,"legacy nested review JSON must remain byte-for-byte canonical");const corruptLegacy=structuredClone(legacySnapshot);corruptLegacy.answer.returnToCheck=true;assert.equal(P.fromReview(corruptLegacy.answer),null);assert.equal(App.reviewMatches(corruptLegacy,{...legacyPayload,reviewJson:JSON.stringify(corruptLegacy)},result),false,"invalid legacy pending review is quarantinable");
const numericPassed=structuredClone(snapshot);numericPassed.passed=1;assert.equal(App.reviewMetadataValid(numericPassed),false);assert.equal(App.reviewMatches(numericPassed,{...payload,reviewJson:JSON.stringify(numericPassed),passed:1},result),false,"numeric passed is not canonical boolean");const stringScore=structuredClone(snapshot);stringScore.score=String(result.score);assert.equal(App.reviewMetadataValid(stringScore),false);
assert.equal(Flow.reviewResult(result,{...snapshot,score:result.score+1},{score:String(result.score),status:result.passed?"passed":"failed"}).trusted,false,"saved metadata mismatch is untrusted");assert.equal(Flow.reviewResult(result,snapshot,{score:String(result.score-1),status:result.passed?"passed":"failed"}).trusted,false,"Moodle score mismatch is untrusted");assert.equal(Flow.reviewResult(result,snapshot,{score:String(result.score),status:"completed"}).trusted,false,"unknown Moodle pass status is untrusted");
console.log("Centre-of-mass lifecycle checks passed");
