"use strict";
const assert=require("node:assert/strict"),G=require("./generator.js"),P=require("./persistence.js"),S=require("./scoring.js");
const seed=11,p=G.generate(seed),fixtures=[];let s=P.initial(seed);fixtures.push(s);s=P.release(s,p.part1.xCm);fixtures.push(s);s=P.markPart1(s,p.part1.xCm);fixtures.push(s);s=P.confirmPart1(s);fixtures.push(s);s=P.settleHole(s,"h1");fixtures.push(s);s=P.traceVertical(s);fixtures.push(s);s=P.settleHole(s,"h2");fixtures.push(s);s=P.traceVertical(s);fixtures.push(s);s=P.markPart2(s,p.part2.centre);fixtures.push(s);s=P.confirmPart2(s);fixtures.push(s);s=P.setView(s,{yaw10:650,pitch10:-180});fixtures.push(s);s=P.setView(s,{yaw10:1100,pitch10:220});fixtures.push(s);s=P.selectPart3(s,p.part3.correctKey);fixtures.push(s);s=P.confirmPart3(s);fixtures.push(s);
for(const item of fixtures){const decoded=P.decode(P.encode(item));assert.deepEqual(decoded,item);assert.equal(S.score(decoded).score,S.score(item).score);}
for(const part of [1,2,3]){let redo=P.redo(s,part);assert.equal(redo.returnToCheck,true);assert.equal(redo.phase,`part${part}`);if(part===1){redo=P.release(redo,p.part1.xCm);redo=P.markPart1(redo,p.part1.xCm);redo=P.confirmPart1(redo);}if(part===2){for(const key of ["h1","h2"]){redo=P.settleHole(redo,key);redo=P.traceVertical(redo);}redo=P.markPart2(redo,p.part2.centre);redo=P.confirmPart2(redo);}if(part===3){redo=P.setView(redo,{yaw10:650,pitch10:-180});redo=P.setView(redo,{yaw10:1100,pitch10:220});redo=P.selectPart3(redo,p.part3.correctKey);redo=P.confirmPart3(redo);}assert.equal(redo.phase,"check");assert.equal(P.validate(redo),true);}
const review=P.makeReview(s);assert.equal(P.validate(review,true),true);assert.deepEqual(P.fromReview(review),review);
assert.equal(P.decode(undefined),null);const injectedFuture=P.initial(seed);injectedFuture.part3.observations=[{yaw10:650,pitch10:-180}];assert.equal(P.decode(injectedFuture),null,"normal part1 rejects future evidence");
const danglingBetweenOne=structuredClone(fixtures[5]);danglingBetweenOne.part2.hangRecords.push({holeKey:"h2"});assert.equal(P.decode(danglingBetweenOne),null,"between-one requires exactly one matching hang and line");const linedActive=structuredClone(fixtures[6]);linedActive.part2.activeHoleKey="h1";assert.equal(P.decode(linedActive),null,"settled-next active hole must be new and unlined");
const restoredSettled=P.decode(P.encode(fixtures[4])),restoredHole=p.part2.holes.find(h=>h.key===restoredSettled.part2.activeHoleKey),dx=p.part2.centre.x-restoredHole.x,dy=p.part2.centre.y-restoredHole.y,norm=Math.hypot(dx,dy),continuation=P.recordLine(restoredSettled,{holeKey:restoredHole.key,a:[restoredHole.x-dx/norm*.02,restoredHole.y-dy/norm*.02],b:[restoredHole.x+dx/norm*.55,restoredHole.y+dy/norm*.55]});assert.ok(continuation&&continuation.variant==="between-one-normal"&&P.validate(continuation),"restored settled state accepts one legal traced-line continuation");
const bad=[()=>{const x=structuredClone(s);x.seed=NaN;return x},()=>{const x=structuredClone(s);x.part3.view.yaw10=1800;return x},()=>{const x=structuredClone(s);x.part2.lines[1].holeKey="h1";return x},()=>{const x=structuredClone(s);x.part1.supportEpisodes[0].outcome="left-fall";return x},()=>{const x=structuredClone(s);x.variant="between-multi-normal";return x}];for(const make of bad)assert.equal(P.decode(make()),null);
assert.ok(Buffer.byteLength(JSON.stringify(review),"utf8")<4000);
console.log("Centre-of-mass persistence matrix checks passed");
