"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),U=require("./ui-policy.js"),App=require("./main.js"),G=require("./generator.js"),P=require("./persistence.js"),M=require("./model.js");
assert.equal(U.activation({x:0,y:0},{x:3,y:4}),true);assert.equal(U.activation({x:0,y:0},{x:2,y:2}),false);assert.equal(U.previewCorner({x:10,y:10},{left:0,top:0,width:100,height:100}),"bottom-right");
const direct={closest:(selector)=>selector==="[data-direct-target]"?{}:null},panel={closest:(selector)=>selector==="#controlPanel"?{}:null},blank={closest:()=>null};assert.equal(U.pointerOwner(direct),"simulation");assert.equal(U.pointerOwner(panel),"panel");assert.equal(U.pointerOwner(blank),"host");
const source=fs.readFileSync(__dirname+"/main.js","utf8");assert.match(source,/setPointerCapture/);assert.match(source,/pointercancel/);assert.match(source,/lostpointercapture/);assert.match(source,/pointerType\s*!==\s*"mouse"/);assert.match(source,/Model\.canonicalView|Persistence\.setView/);assert.doesNotMatch(source,/innerHTML\s*=.*directLayer/);
const html=fs.readFileSync(__dirname+"/index.html","utf8"),css=fs.readFileSync(__dirname+"/styles.css","utf8");assert.equal((html.match(/data-part-tab=/g)||[]).length,3,"three always-available experiment tabs");assert.doesNotMatch(html,/formula|x<sub|Σ|力矩為零/,"learner UI has no centre-of-mass formula");assert.match(css,/\.orbit-target:hover[^}]*background:transparent!important/,"orbit hover cannot paint the stage white");
assert.doesNotMatch(html,/data-reset-part|a11y-actions|id="(?:testSupport|placePart1Mark|holeButtons|hangHole|traceLine|placePart2Mark)"/,"normal part panels contain no reset or redundant operational button wall");
for(const target of ["support","mark1","plate","hole-","rotate","draw","mark2","orbit","candidate-"])assert.ok(source.includes(target),`direct target inventory includes ${target}`);assert.match(source,/Persistence\.recordLine/);assert.match(source,/clipPath\s*=\s*`polygon/);
const clusters=[GeneratorCluster(350,230),GeneratorCluster(84,54),[{key:"A",x:330,y:210,depth:4},{key:"B",x:351,y:212,depth:3},{key:"C",x:345,y:232,depth:2},{key:"D",x:352,y:230,depth:1},{key:"E",x:348,y:229,depth:0}]],sizes=[[320,192],[390,258],[390,340],[700,460],[1280,690]];function GeneratorCluster(x,y){return G.LABELS.map((key,index)=>({key,x,y,depth:4-index}));}for(const [width,height] of sizes)for(const cluster of clusters){const arranged=App.layoutCandidateTargets(cluster,width,height);assert.deepEqual(arranged.map(item=>item.key).sort(),G.LABELS);for(let i=0;i<arranged.length;i+=1)for(let j=i+1;j<arranged.length;j+=1){const a=arranged[i],b=arranged[j],dx=Math.abs((a.x-b.x)*width/700),dy=Math.abs((a.y-b.y)*height/460);assert.ok(dx>=44||dy>=44,`candidate CSS rectangles do not overlap at ${width}x${height}`);}}
assert.match(source,/Model\.createSwing/);assert.match(source,/Model\.stepSwing/);assert.match(source,/requestAnimationFrame\(animate\)/);assert.match(source,/renderSvgPreview\(previewFocus\(\)\)/);assert.match(source,/syncPart2Targets\(\)/);
let restored=P.initial(31),problem=G.generate(31);restored=P.switchPart(restored,2);restored=P.settleHole(restored,"h1");const pose=App.restoredPlatePose(restored,problem),hole=problem.part2.holes[0],toWorld=(point)=>({x:pose.x+(point.x*Math.cos(pose.angle)-point.y*Math.sin(pose.angle))*245,y:pose.y+(point.x*Math.sin(pose.angle)+point.y*Math.cos(pose.angle))*245}),pivot=toWorld(hole),com=toWorld(problem.part2.centre);assert.ok(Math.hypot(pivot.x-350,pivot.y-42)<1e-10,"restored active hole is exactly on nail");assert.ok(Math.abs(com.x-pivot.x)<1e-10&&com.y>pivot.y,"restored COM is vertically below pivot");assert.equal(App.restoredPlatePose(P.initial(31),problem),null);
console.log("Centre-of-mass UI runtime checks passed");
