"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const App = require("./main.js");
const G = require("./generator.js");
const P = require("./persistence.js");

const source = fs.readFileSync(path.join(__dirname, "main.js"), "utf8");
const html = fs.readFileSync(path.join(__dirname, "index.html"), "utf8");
const css = fs.readFileSync(path.join(__dirname, "styles.css"), "utf8");
for (const phase of ["investigate", "model", "predict", "design", "review"]) assert.match(source, new RegExp(`state\.phase === ["']${phase}["']`));
for (const transition of ["replaceCalibration", "replaceMeasurement", "replaceModel", "replacePrediction", "replaceDesign", "setPhase", "editSection", "clearCalibration"]) assert.match(source + fs.readFileSync(path.join(__dirname, "persistence.js"), "utf8"), new RegExp(transition));
assert.match(source, /Animation.createAnimator/);
assert.match(source, /animationToken/);
assert.match(source, /visibilitychange/);
assert.match(source, /resize/);
assert.match(source, /setDraftProvider/);
assert.match(source, /loadAttempt\(ACTIVITY\)/);
assert.match(source, /submitWithCallbacks/);
assert.match(source, /activityState: outcome/);
assert.match(source, /quarantinePending/);
assert.match(html, /data-action="record-calibration"/);
assert.match(html, /data-action="record-measurement"/);
assert.match(html, /data-action="submit"/);
assert.match(html, /id="debugPanel"/);
assert.match(html, /id="debugCompleteInvestigation"/);
assert.match(html, /id="debugCompleteModel"/);
assert.match(html, /data-action="navigate-phase" data-phase="model"[^>]*>返回第二階段查看線性關係/);
assert.match(html, /彈簧和重物一起伸長或縮短/);
assert.match(html, /自然長度加上伸長量/);
assert.match(source, /選擇題目 \$\{index \+ 1\}/);
assert.match(source, /button\.setAttribute\("aria-label", `選擇預測題目/);
assert.doesNotMatch(source, /目前編輯/);
assert.match(source, /const PREDICTION_STAGE = Object\.freeze/);
assert.match(source, /const PREDICTION_LOAD_VISUALS = Object\.freeze/);
assert.match(source, /const PREDICTION_SNAP_STEP_M = 0\.01/);
assert.match(source, /function snapPredictionValue\(value\)/);
assert.match(source, /mathLength\(extensionM, 0\)/);
assert.match(source, /toFixed\(0\), class: "math-number"/);
assert.match(source, /function predictionSpringEndY\(extensionM\)/);
assert.match(source, /function predictionLoadVisual\(forceN\)/);
assert.match(source, /const predictionLabelY = Math\.min\(458, loadBottomY \+ 24\)/);
assert.match(source, /沒有更改已記錄的後續答案/);
assert.match(source, /action === "navigate-phase"/);
assert.match(css, /grid-template-areas[^;]*"stage"[^;]*"controls"/);
assert.match(css, /grid-template-areas[^;]*"controls stage"/);
assert.match(css, /overflow-y[^;]*auto/);
assert.match(css, /overscroll-behavior[^;]*contain/);

const scenario = G.generateScenario({ seed: 19 });
const state = P.freshState(19);
const view = App.buildEditableViewModel(state, scenario);
assert.equal(view.phase, "investigate");
assert.equal(view.measurements.A.length, 3);
assert.equal(view.measurements.A[0].extensionM, null);
assert.equal(Object.keys(view).includes("optimal"), false);
assert.equal(App.investigationEndpointM(state, scenario.springs.A, 0.21), scenario.springs.A.naturalLengthM, "unloaded spring stays at its generated natural length");
assert.equal(App.investigationEndpointM({ activeLoadKey: "F1" }, scenario.springs.A, 0.21), 0.21, "loaded spring uses its animated equilibrium position");
assert.equal(App.INVESTIGATION_DRAG_HANDLE_X, 650, "investigation drag handles stay beside the spring");
assert.equal(App.INVESTIGATION_GUIDE_LABEL_X, 596, "investigation guide labels stay left of the drag handles");
assert.equal(App.debugQueryEnabled("?debug=1"), true, "debug shortcut accepts debug=1");
assert.equal(App.debugQueryEnabled("?debug=0"), false, "debug shortcut stays off by default");
assert.equal(App.PHASE_LABELS.model, "找出 F–x 線性關係", "model phase is learner-facing as a linear-relationship investigation");
assert.equal(App.INVESTIGATION_RULER_TOP, 42, "the ruler origin is the ceiling anchor");
assert.equal(App.INVESTIGATION_RULER_BOTTOM, 455, "the ruler remains inside the stage");
assert.equal(App.MEASUREMENT_SNAP_THRESHOLD_M, 0.003, "measurement snapping is limited to 0.3 cm");
assert.equal(App.GRAPH_X_AXIS_LABEL_X, 414.5, "graph x-axis label is centered under the plot");
assert.equal(App.GRAPH_X_AXIS_LABEL_Y, 460, "graph x-axis label has its own row below the tick labels");
assert.equal(App.PREDICTION_SNAP_STEP_M, 0.01, "prediction snapping supports 1 cm increments");
assert.equal(App.snapPredictionValue(0.03749), 0.04, "prediction snapping rounds to an integer centimetre");
assert.equal(App.snapMeasurementValue(0.099, 0.1), 0.1, "nearby measurement values snap to the target");
assert.equal(App.snapMeasurementValue(0.096, 0.1), 0.096, "values outside the snap threshold remain unchanged");
assert.ok(App.LOAD_VISUALS.F1.width < App.LOAD_VISUALS.F2.width && App.LOAD_VISUALS.F2.width < App.LOAD_VISUALS.F3.width, "heavier loads use larger blocks");
assert.notEqual(App.LOAD_VISUALS.F1.fill, App.LOAD_VISUALS.F2.fill, "load weights use different colors");
assert.notEqual(App.predictionLoadVisual(1.05).width, App.predictionLoadVisual(3.85).width, "random prediction forces use different-sized load blocks");
assert.notEqual(App.predictionLoadVisual(1.05).fill, App.predictionLoadVisual(3.85).fill, "random prediction forces use different load colors");
assert.match(source, /mathForceValue\(spec\.forceN, 2\)/);
assert.match(source, /n\(spec\.forceN, 2\)/);
assert.match(source, /const label = cmValue === 0 \? "0" : `\$\{cmValue\} cm`/);
assert.match(source, /drawSvgAxisLabel\(118, 72, "位置", "", "cm"/);
assert.match(source, /drawMathText\(GRAPH\.left - 34, GRAPH\.top \+ GRAPH\.height \+ 6, \[\{ text: "0", class: "math-number" \}\]/);
assert.match(source, /drawSvgAxisLabel\(GRAPH_X_AXIS_LABEL_X, GRAPH_X_AXIS_LABEL_Y, "伸長", "x", "cm", \{[\s\S]*"text-anchor": "middle"/);
assert.match(source, /drawSvgAxisLabel\(GRAPH\.left - 50, GRAPH\.top \+ 8, "", "F", "N", \{[\s\S]*"text-anchor": "end"/);
assert.match(source, /node\.textContent = String\(text \?\? ""\)/);
assert.match(source, /const top = INVESTIGATION_RULER_TOP/);
assert.match(source, /if \(loadVisual\)/);
assert.match(source, /固定端／天花板/);
assert.match(source, /point\.y - INVESTIGATION_RULER_TOP/);
assert.match(source, /drawSvgQuantity\(74, y \+ 6, cmValue, "cm", \{[\s\S]*"text-anchor": "end"/);
assert.match(source, /drawSvgAxisLabel\(98, 480, "讀尺位置", "", "cm"/);
assert.match(source, /drawText\(INVESTIGATION_GUIDE_LABEL_X, calibrationY - 8, "零位", \{ \.\.\.guideLabelAttributes, fill: "#6d28d9" \}\)/);
assert.match(source, /drawText\(INVESTIGATION_GUIDE_LABEL_X, cursorY - 8, "游標", \{ \.\.\.guideLabelAttributes, fill: "#b91c1c" \}\)/);
assert.match(source, /const guideLabelAttributes = \{[\s\S]*"text-anchor": "end"[\s\S]*"paint-order": "stroke"/);
assert.doesNotMatch(source, /真實探究現象/);
assert.match(source, /function mathQuantity\(value, unit\)/);
assert.match(source, /function formatMathSentence\(value\)/);
assert.match(source, /function drawMathText\(x, y, parts/);
assert.match(source, /setMathContent\(dom\.zeroReadout, \["位置 ", mathLength/);
assert.match(source, /mathKFormula\(Model\.kFromModelHandle/);
assert.match(source, /function measurementSnapTarget\(kind\)/);
assert.match(source, /snapMeasurementPosition\(drag\.kind, rawValue\)/);
assert.match(source, /snapMeasurementPosition\(kind, rawValue\)/);
assert.match(source, /function completeInvestigationForDebug\(\)/);
assert.match(source, /Persistence\.transitions\.setPhase\(next, "model", scenario\)/);
assert.match(source, /function completeModelForDebug\(\)/);
assert.match(source, /Persistence\.transitions\.setPhase\(next, "predict", scenario\)/);
assert.match(source, /Model\.MODEL_HANDLE_FORCE_N \/ spring\.kNPerM/);
assert.match(source, /const debugAvailable = debugQueryEnabled\(host\.location\?\.search \|\| ""\)/);
assert.match(source, /function modelDraftPoint\(\)/);
assert.match(source, /function modelValueFromPoint\(point\)/);
assert.match(source, /modelDraftForceN/);
assert.match(html, /直線的斜率/);
assert.match(html, /彈簧的彈力與伸長量成正比/);
assert.match(html, /id="modelDragHelp"[^>]*>[^<]*「線」標記/);
assert.match(css, /\.math-inline, \.math-quantity/);
assert.match(css, /\.debug-toggle/);
assert.match(css, /\.phase-navigation/);
assert.match(css, /\.math-number/);
assert.match(css, /\.readout-row strong\.math-readout, output\.math-readout/);
assert.match(css, /#stageSvg \.math-svg/);
assert.match(css, /\.readout-row \+ #recordMeasurement \{ margin-top: \.45rem; \}/);

console.log("Hooke's law UI runtime checks passed");
