"use strict";
const assert = require("assert");
const fs = require("fs");
const path = require("path");
const html = fs.readFileSync(path.join(__dirname, "index.html"), "utf8");
const css = fs.readFileSync(path.join(__dirname, "styles.css"), "utf8");

for (const text of ["aria-roledescription=\"可移動直尺\"", "aria-describedby=\"rulerHelp\"", "aria-live=\"polite\"", "role=\"alert\""]) assert.ok(html.includes(text), text);
for (const id of ["rulerHandle", "controlPanel", "readingInput", "submitButton"]) assert.ok(html.includes(`id="${id}"`));
assert.ok(css.includes("touch-action: pan-y"));
assert.ok(css.includes(".ruler-handle"));
assert.ok(css.includes("touch-action: none"));
assert.ok(css.includes("overscroll-behavior: contain"));
assert.ok(css.includes("prefers-reduced-motion"));
assert.ok(css.includes("height: 100dvh"));
assert.ok(css.includes("min-height: 0"));
assert.ok(!html.includes("magnifier"));
assert.ok(!css.includes(".magnifier"));
assert.ok(html.includes("preserveAspectRatio=\"none\""));
assert.ok(html.includes("data-ruler-drag-owner"));
assert.ok(html.includes("<var>g</var>"));
assert.ok(html.includes("<var>t</var><sup>2</sup>"));
assert.ok(html.includes("<var>P</var><sub>0</sub>"));
assert.ok(html.includes("<span class=\"unit\">cm</span>"));
assert.ok(!html.includes("⋮⋮"));
assert.match(css, /\.ruler-handle\s*\{[^}]*border:\s*0[^}]*background:\s*transparent/s);
assert.ok(html.includes("id=\"replayPreviewButton\""));
assert.ok(html.includes("id=\"animationStatus\""));
assert.ok(html.includes("直接拖動直尺"));
assert.ok(!html.includes("data-nudge"));
assert.ok(!html.includes("nudge-grid"));
assert.ok(!css.includes(".nudge-grid"));
assert.ok((html.match(/<label><input type="radio"/g) || []).length >= 11, "every radio option has a real label element");
console.log("free-fall accessibility contract tests passed");
