"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const html = fs.readFileSync(path.join(__dirname, "index.html"), "utf8");
const css = fs.readFileSync(path.join(__dirname, "styles.css"), "utf8");
const main = fs.readFileSync(path.join(__dirname, "main.js"), "utf8");

assert.equal((html.match(/aria-live=/g) || []).length, 1);
assert.match(html, /id="liveRegion"[^>]*aria-live="polite"/);
assert.match(html, /id="submissionNotice"[^>]*role="status"[^>]*tabindex="-1"/);
assert.match(html, /id="throttleButton"[^>]*aria-keyshortcuts="Q W E ArrowUp"/);
assert.match(html, /id="brakeButton"[^>]*aria-keyshortcuts="A S D ArrowDown"/);
assert.doesNotMatch(html, /name="intensity"/);
assert.match(html, /class="pedal-scale"[^>]*aria-hidden="true"/);
assert.match(html, /data-intensity="1">輕/);
assert.match(html, /data-intensity="2">中/);
assert.match(html, /data-intensity="3">盡/);
assert.match(css, /\.pedal \{[^}]*min-height: 78px/);
assert.match(css, /\.driving-stage[^}]*touch-action: pan-y/);
assert.match(css, /\.driving-panel[^}]*overscroll-behavior: contain/);
assert.match(css, /\.pedal[^}]*touch-action: none/);
assert.match(css, /\.scrub-row input \{[^}]*min-height: 44px[^}]*touch-action: none/);
assert.match(css, /minmax\(13rem, 44vh\) minmax\(0,1fr\)/);
assert.match(css, /minmax\(13rem, 44dvh\) minmax\(0,1fr\)/);
assert.match(main, /setPointerCapture/);
assert.match(main, /pointercancel/);
assert.match(main, /操作中斷；踏板已安全回到空檔/);
assert.match(main, /visibilitychange/);
assert.match(main, /shouldHandleGlobalShortcut\(event\.target\)/);
assert.match(main, /event\.code === "Space"/);
assert.match(main, /canOpenReviewItem\(state, level\.id, locked\)/);
assert.equal((html.match(/data-pick-level="level[1-5]"/g) || []).length, 5);
assert.match(html, /id="levelPicker"/);
assert.match(html, /id="reviewProgressButton"/);
assert.match(css, /\.level-picker button \{[^}]*min-height: 48px/);
assert.match(main, /elements\.reviewList\.addEventListener\("click", \(event\) => \{\s*if \(locked\) return;/);
assert.match(html, /id="analysisZoneTabs"/);
assert.match(html, /id="checkpointScrubRange"[^>]*type="range"[^>]*aria-label="圖像證據回放時間游標"/);
assert.equal((html.match(/id="checkpointScrubRange"/g) || []).length, 1);
assert.equal((html.match(/id="checkpointXtCanvas"/g) || []).length, 1);
assert.equal((html.match(/id="checkpointVtCanvas"/g) || []).length, 1);
assert.match(html, /id="checkpointXtCanvas"[^>]*role="img"[^>]*aria-label="同一試車記錄的位置對時間圖"/);
assert.match(html, /id="checkpointVtCanvas"[^>]*role="img"[^>]*aria-label="同一試車記錄的速度對時間圖"/);
assert.match(html, /id="checkpointDualGraphs"[^>]*aria-label="同一試車記錄的兩幅同步圖像"/);
assert.match(css, /\.checkpoint-plot \{[^}]*width: min\(100%, 14rem\)/);
assert.match(css, /\.checkpoint-plot canvas \{[^}]*width: 100%[^}]*aspect-ratio: 1\.35/);
assert.match(main, /paintGraph\(checkpointXtCtx, checkpointXtView, "xt", run\.samples, cursorSample, zone, true\)/);
assert.match(main, /paintGraph\(checkpointVtCtx, checkpointVtView, "vt", run\.samples, cursorSample, zone, true\)/);
assert.doesNotMatch(
  main.match(/function viewCheckpoint\(mode\) \{[\s\S]*?\n  \}/)?.[0] || "",
  /state\.graphMode\s*=/
);
assert.match(main, /同步比較車輛、x–t 圖與 v–t 圖/);
assert.match(html, /id="resultReviewTools"[^>]*aria-labelledby="resultReviewToolsTitle"/);
assert.match(html, /id="resultRunPicker"[^>]*role="group"[^>]*aria-label="選擇已提交的試車記錄"/);
assert.equal((html.match(/id="resultScrubRange"/g) || []).length, 1);
assert.match(html, /id="resultScrubRange"[^>]*type="range"[^>]*aria-label="已提交試車只讀回放時間游標"/);
assert.equal((html.match(/name="resultGraphMode"/g) || []).length, 2);
assert.match(css, /\.result-run-picker button \{[^}]*min-height: 44px/);
assert.match(main, /let resultReviewGraphMode = "vt"/);
assert.match(main, /function trustedResultReviewAvailable\(\)/);
assert.match(main, /elements\.resultReviewTools\.classList\.toggle\("is-hidden", !available\)/);
assert.match(main, /resultReviewGraphMode = input\.value;\s*draw\(\);/);
assert.match(main, /state = reviewState;\s*pendingExpected = \{ reviewState, computed \}/);
assert.match(main, /你的答案：\$\{chosenAnswer\}/);
assert.match(main, /正確解釋：勻速的 v–t 圖是水平直線/);
assert.match(main, /const replacing = Boolean\(state\.selectedRuns\[state\.currentItem\]\)/);
assert.match(main, /if \(returning\) return enterReview\(\);\s*state\.variant = "accepted"/);
assert.doesNotMatch(html, /id="graphTitle"/);
assert.match(main, /function drawRoadBoundary\(/);
assert.match(main, /drawRoadBoundary\(x, y, roadDepth\);\s*drawTargetSign\(x, y - 12, segment\.target\);/);
assert.doesNotMatch(main, /setLineDash/);
assert.doesNotMatch(main, /function drawUpcomingSign\(/);
assert.doesNotMatch(main, /function drawBoundarySign\(/);
assert.match(main, /Visuals\.stageTargetLabel\(/);
assert.match(main, /font = "italic 18px 'STIX Two Math', 'Cambria Math', 'Times New Roman', serif"/);
assert.match(html, /class="math-expression"><var>v<\/var><span class="math-operator">−<\/span><var>t<\/var>/);
assert.match(html, /class="math-expression"><var>x<\/var><span class="math-operator">−<\/span><var>t<\/var>/);
assert.match(main, /function physicsHtml\(value\)/);
assert.match(main, /elements\.instruction\.innerHTML = physicsHtml\(level\.instruction\)/);
assert.match(css, /\.math-expression var \{[^}]*font-style: italic/);
assert.match(main, /function drawFarLandmark\(/);
assert.match(main, /function drawRoadsideLandmark\(/);
assert.match(main, /function fillRoadStrip\(/);
assert.match(main, /drawCar\(anchorX, baseY \+ roadDepth \* \.55/);
assert.match(main, /ctx\.translate\(-83, 0\)/);
assert.doesNotMatch(html, /m\/s|m\/s²|m\/s<sup>2/);
assert.doesNotMatch(html, /type="number"/);
assert.match(css, /\.driving-panel \{ width: 100%; min-width: 0; max-width: 100%; \}/);
assert.doesNotMatch(css, /\.driving-panel \{[^}]*width:\s*min\(/);
assert.match(css, /\.progress li\.is-done:not\(\.is-current\)/);
assert.match(main, /window\.SimScorm\.quarantinePending\(\)/);

console.log("Kinematics driving accessibility checks passed");
