"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const html = fs.readFileSync(path.join(__dirname, "index.html"), "utf8");
const css = fs.readFileSync(path.join(__dirname, "styles.css"), "utf8");
const main = fs.readFileSync(path.join(__dirname, "main.js"), "utf8");

assert.equal((html.match(/aria-live=/g) || []).length, 1);
assert.match(html, /id="liveRegion"[^>]*aria-live="polite"/);
assert.match(html, /id="throttleButton"[^>]*aria-keyshortcuts="Q W E ArrowUp"/);
assert.match(html, /id="brakeButton"[^>]*aria-keyshortcuts="A S D ArrowDown"/);
assert.doesNotMatch(html, /name="intensity"/);
assert.match(html, /class="pedal-scale"[^>]*aria-hidden="true"/);
assert.match(html, /data-intensity="1">輕/);
assert.match(html, /data-intensity="2">中/);
assert.match(html, /data-intensity="3">盡/);
assert.match(css, /\.pedal \{[^}]*min-height: 78px/);
assert.match(css, /\.driving-stage[^}]*touch-action: pan-y/);
assert.match(css, /\.driving-panel[^}]*overscroll-behavior: contain/);
assert.match(css, /\.pedal[^}]*touch-action: none/);
assert.match(css, /minmax\(13rem, 44vh\) minmax\(0,1fr\)/);
assert.match(css, /minmax\(13rem, 44dvh\) minmax\(0,1fr\)/);
assert.match(main, /setPointerCapture/);
assert.match(main, /pointercancel/);
assert.match(main, /visibilitychange/);
assert.match(main, /shouldHandleGlobalShortcut\(event\.target\)/);
assert.match(main, /event\.code === "Space"/);
assert.match(main, /canOpenReviewItem\(state, level\.id, locked\)/);
assert.equal((html.match(/data-pick-level="level[1-5]"/g) || []).length, 5);
assert.match(html, /id="levelPicker"/);
assert.match(html, /id="reviewProgressButton"/);
assert.match(css, /\.level-picker button \{[^}]*min-height: 48px/);
assert.match(main, /elements\.reviewList\.addEventListener\("click", \(event\) => \{\s*if \(locked\) return;/);
assert.match(html, /id="analysisZoneTabs"/);
assert.doesNotMatch(html, /id="graphTitle"/);
assert.match(main, /function drawRoadBoundary\(/);
assert.match(main, /setLineDash\(transition \? \[8, 6\] : \[\]\)/);
assert.match(main, /function drawUpcomingSign\(/);
assert.match(main, /Visuals\.stageTargetLabel\(/);
assert.match(main, /font = "italic 18px 'STIX Two Math', 'Cambria Math', 'Times New Roman', serif"/);
assert.match(html, /class="math-expression"><var>v<\/var><span class="math-operator">−<\/span><var>t<\/var>/);
assert.match(html, /class="math-expression"><var>x<\/var><span class="math-operator">−<\/span><var>t<\/var>/);
assert.match(main, /function physicsHtml\(value\)/);
assert.match(main, /elements\.instruction\.innerHTML = physicsHtml\(level\.instruction\)/);
assert.match(css, /\.math-expression var \{[^}]*font-style: italic/);
assert.match(main, /function drawFarLandmark\(/);
assert.match(main, /function drawRoadsideLandmark\(/);
assert.match(main, /function fillRoadStrip\(/);
assert.match(main, /drawCar\(anchorX, baseY \+ roadDepth \* \.55/);
assert.doesNotMatch(html, /m\/s|m\/s²|m\/s<sup>2/);
assert.doesNotMatch(html, /type="number"/);

console.log("Kinematics driving accessibility checks passed");
