"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const html = fs.readFileSync(path.join(__dirname, "index.html"), "utf8");
const css = fs.readFileSync(path.join(__dirname, "styles.css"), "utf8");
const main = fs.readFileSync(path.join(__dirname, "main.js"), "utf8");
for (const target of ["force-grip", "balance-origin", "prediction-friction", "breakaway-marker", "static-start", "static-end"]) assert.match(html, new RegExp(`data-drag-target="${target}"`));
for (const id of ["zeroTask", "zeroFrictionType", "zeroFrictionDirection", "zeroFrictionMagnitude", "zeroValidationStatus", "staticTask", "staticPullPrompt", "staticAppliedReadout", "staticFrictionReadout", "staticValidationStatus", "breakawayTask", "breakawayMotionStatus", "breakawayAnswer", "breakawayValidationStatus"]) assert.match(html, new RegExp(`id="${id}"`));
const blankOptions = html.match(/<option value="" selected disabled>請選擇<\/option>/g) || [];
assert.equal(blankOptions.length, 2, "A1 type and direction both start at 請選擇");
assert.doesNotMatch(html, /SimLab/);
assert.doesNotMatch(html, /先用受力圖建立靜摩擦力概念/);
assert.match(html, /Part A 不使用測力計或歸零操作/);
assert.doesNotMatch(html, /id="recordBalance"|id="balanceObservations"|data-action="record-balance"|data-action="save-balance-answer"/);
assert.doesNotMatch(html, /data-action="pull-left"|data-action="pull-right"|data-action="reset-breakaway"/);
assert.match(html, /id="liveReadouts"[^>]*aria-live="off"/);
assert.match(html, /id="liveRegion"[^>]*aria-live="polite"/);
assert.match(html, /type="range"/);
assert.match(html, /id="traceTable"/);
assert.match(html, /id="intervalStats"/);
for (const id of ["previousExtremum", "nextExtremum", "jumpSelectionStart", "jumpSelectionEnd"]) assert.match(html, new RegExp(`id="${id}"`));
assert.ok(html.indexOf('id="stageGraph"') < html.indexOf('id="controlPanel"'), "graph must live in the fixed stage, not the scrolling control panel");
assert.match(html, /id="redoExperimentConfirm"[^>]*role="group"/);
assert.match(html, /id="validationStatus"[^>]*tabindex="-1"[^>]*aria-live="off"/);
assert.match(html, /class="save-action-row"/);
for (const phase of ["balance", "experiment", "analysis", "predict"]) assert.match(html, new RegExp(`data-action="navigate-phase"[^>]*data-phase="${phase}"`));
assert.match(html, /活動任務，可自由切換/);
assert.doesNotMatch(html, /id="balanceNetForce"|水平合力/);
assert.match(html, /id="predictionReadout"[^>]*aria-live="off"/);
assert.match(html, /<var>F<\/var><sub>拉<\/sub>/);
assert.match(css, /\.stage[^}]*touch-action:\s*pan-y/);
assert.match(css, /\.drag-target[^}]*touch-action:\s*none/);
assert.match(css, /\.balance-origin-target[^}]*width:\s*48px/);
assert.match(css, /\.balance-origin-target::after[^}]*width:\s*8px/);
assert.match(css, /\.control-panel[^}]*overflow-y:\s*auto/);
assert.match(css, /overscroll-behavior:\s*contain/);
assert.match(css, /html,[\s\S]*body[\s\S]*overflow:\s*hidden/);
assert.match(css, /--header-track:\s*clamp\(4\.5rem, 8vh, 5\.5rem\)/);
assert.match(css, /\.answer-card input\[type="number"\][\s\S]*min-height:\s*44px/);
assert.match(main, /setPointerCapture/);
assert.match(main, /pointercancel/);
assert.match(main, /event\.isPrimary === false/);
assert.match(main, /hostSwipe/);
assert.match(main, /intervalStatsList/);
assert.match(main, /aria-describedby/);
assert.match(main, /localExtremaIndices/);
assert.match(main, /focusAfterAction/);
assert.match(main, /navigateToPhase/);
assert.match(main, /selectAnalysisTask/);
assert.match(main, /selectPrediction/);
assert.match(main, /prediction-friction-arrow/);
assert.match(main, /balance-origin/);
assert.match(main, /const comY = groundY - 27/);
assert.match(main, /clearZeroForceControls/);
assert.match(html, /data-action="reset-balance-object"/);
assert.match(main, /stepDirectForce/);
assert.match(main, /balanceCurrentForceN/);
assert.doesNotMatch(html, /受力圖由重心出發/);
assert.doesNotMatch(main, /受力圖由重心出發/);
assert.doesNotMatch(main, /預測情境中的物體|\[x \+ 46, groundY \+ 62, "物體"/);
assert.doesNotMatch(main, /水平粗糙面/);
assert.doesNotMatch(main, /Part A：只看水平力的大小和方向/);
assert.doesNotMatch(main, /balanceNetForce|水平合力/);
assert.doesNotMatch(main, /balanceFriction/);
assert.match(main, /\[data-action\], input, select, \.drag-target/);
console.log("Static/kinetic friction accessibility checks passed");
