"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const html = fs.readFileSync(path.join(__dirname, "index.html"), "utf8");
const css = fs.readFileSync(path.join(__dirname, "styles.css"), "utf8");
const main = fs.readFileSync(path.join(__dirname, "main.js"), "utf8");
const physics = fs.readFileSync(path.join(__dirname, "physics.js"), "utf8");
for (const target of ["experiment-origin", "balance-origin", "prediction-friction", "breakaway-marker", "static-start", "static-end"]) assert.match(html, new RegExp(`data-drag-target="${target}"`));
for (const id of ["zeroTask", "zeroFrictionType", "zeroFrictionDirection", "zeroFrictionMagnitude", "zeroValidationStatus", "staticTask", "staticPullPrompt", "staticAppliedReadout", "staticFrictionReadout", "staticValidationStatus", "breakawayTask", "breakawayMotionStatus", "breakawayAnswer", "breakawayValidationStatus"]) assert.match(html, new RegExp(`id="${id}"`));
const blankOptions = html.match(/<option value="" selected disabled>請選擇<\/option>/g) || [];
assert.equal(blankOptions.length, 2, "A1 type and direction both start at 請選擇");
assert.doesNotMatch(html, /SimLab/);
assert.doesNotMatch(html, /先用受力圖建立靜摩擦力概念/);
assert.match(html, /Part A 不使用測力計或歸零操作/);
assert.doesNotMatch(html, /id="recordBalance"|id="balanceObservations"|data-action="record-balance"|data-action="save-balance-answer"/);
assert.doesNotMatch(html, /data-action="pull-left"|data-action="pull-right"|data-action="reset-breakaway"/);
assert.doesNotMatch(html, /id="liveReadouts"/);
assert.match(html, /id="experimentOrigin"[^>]*data-drag-target="experiment-origin"/);
assert.doesNotMatch(html, /experimentForceSlider|拉力滑桿/);
assert.match(html, /id="liveRegion"[^>]*aria-live="polite"/);
assert.match(html, /開始 30 秒記錄/);
assert.match(html, /活動簡介/);
assert.match(html, /學生只需要逐漸增加拉力，直到物體啱啱開始移動/);
assert.match(html, /只重看 Part B 同一張「<var>F<\/var><sub>拉<\/sub>–<var>t<\/var> 圖/);
assert.doesNotMatch(html, /速度—時間圖/);
assert.match(html, /type="range"/);
assert.match(html, /id="traceTable"/);
assert.match(html, /id="intervalStats"/);
for (const id of ["previousExtremum", "nextExtremum", "jumpSelectionStart", "jumpSelectionEnd"]) assert.match(html, new RegExp(`id="${id}"`));
assert.ok(html.indexOf('id="stageGraph"') < html.indexOf('id="controlPanel"'), "graph must live in the fixed stage, not the scrolling control panel");
assert.doesNotMatch(html, /redoExperimentConfirm|confirm-redo-experiment|cancel-redo-experiment/);
assert.match(html, /id="validationStatus"[^>]*tabindex="-1"[^>]*aria-live="off"/);
assert.match(html, /class="save-action-row"/);
for (const phase of ["balance", "experiment", "analysis", "predict"]) assert.match(html, new RegExp(`data-action="navigate-phase"[^>]*data-phase="${phase}"`));
assert.match(html, /活動任務，可自由切換/);
assert.doesNotMatch(html, /id="balanceNetForce"|水平合力/);
assert.match(html, /id="predictionReadout"[^>]*aria-live="off"/);
assert.match(html, /<var>F<\/var><sub>拉<\/sub>/);
assert.match(css, /\.stage[^}]*touch-action:\s*pan-y/);
assert.match(css, /\.drag-target[^}]*touch-action:\s*none/);
assert.match(css, /\.balance-origin-target[^}]*width:\s*48px/);
assert.match(css, /\.balance-origin-target::after[^}]*width:\s*8px/);
assert.match(css, /\.control-panel[^}]*overflow-y:\s*auto/);
assert.match(css, /overscroll-behavior:\s*contain/);
assert.match(css, /html,[\s\S]*body[\s\S]*overflow:\s*hidden/);
assert.match(css, /--header-track:\s*clamp\(4\.5rem, 8vh, 5\.5rem\)/);
assert.match(css, /\.answer-card input\[type="number"\][\s\S]*min-height:\s*44px/);
assert.doesNotMatch(css, /experiment-force-slider|experiment-force-control/);
assert.match(css, /\.graph-axis-label[^}]*font-size:\s*28px/);
assert.doesNotMatch(css, /experiment-graph-title/);
assert.match(main, /setPointerCapture/);
assert.match(main, /pointercancel/);
assert.match(main, /event\.isPrimary === false/);
assert.match(main, /hostSwipe/);
assert.match(main, /intervalStatsList/);
assert.match(main, /aria-describedby/);
assert.match(main, /localExtremaIndices/);
assert.match(main, /focusAfterAction/);
assert.match(main, /navigateToPhase/);
assert.match(main, /selectAnalysisTask/);
assert.match(main, /selectPrediction/);
assert.match(main, /prediction-friction-arrow/);
assert.match(main, /balance-origin/);
assert.match(main, /const comY = groundY - 27/);
assert.match(main, /clearZeroForceControls/);
assert.match(html, /data-action="reset-balance-object"/);
assert.match(main, /stepDirectForce/);
assert.match(main, /experimentAppliedForceN/);
assert.doesNotMatch(main, /experimentForceSlider/);
assert.match(main, /renderExperimentForceGraph/);
assert.match(main, /experimentOrigin/);
assert.match(main, /experiment-pull/);
assert.doesNotMatch(main, /kineticFollow|kinetic-follow/);
assert.doesNotMatch(main, /experiment-graph-title/);
assert.match(main, /EXPERIMENT_START_POSITION_M = 0/);
assert.match(main, /EXPERIMENT_FORCE_SCALE_PX_PER_N = 30/);
assert.match(main, /clamp\(.*0, EXPERIMENT_MAX_FORCE_N\)/);
assert.match(main, /timeoutExperiment/);
assert.match(main, /時間已經超時/);
assert.match(main, /系統正維持接近勻速/);
assert.doesNotMatch(main, /細力啲/);
assert.doesNotMatch(main, /大力啲/);
assert.match(main, /balanceCurrentForceN/);
assert.doesNotMatch(html, /受力圖由重心出發/);
assert.doesNotMatch(main, /受力圖由重心出發/);
assert.doesNotMatch(main, /預測情境中的物體|\[x \+ 46, groundY \+ 62, "物體"/);
assert.doesNotMatch(main, /水平粗糙面/);
assert.doesNotMatch(main, /Part A：只看水平力的大小和方向/);
assert.doesNotMatch(main, /balanceNetForce|水平合力/);
assert.doesNotMatch(main, /balanceFriction/);
assert.match(physics, /const HANDLE_SPEED_LIMIT_MPS = 0\.06/);
assert.doesNotMatch(physics, /kineticFollow|kinetic-follow/);
assert.match(main, /\[data-action\], input, select, \.drag-target/);
console.log("Static/kinetic friction accessibility checks passed");
