"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const html = fs.readFileSync(path.join(__dirname, "index.html"), "utf8");
const css = fs.readFileSync(path.join(__dirname, "styles.css"), "utf8");
const main = fs.readFileSync(path.join(__dirname, "main.js"), "utf8");
for (const target of ["force-grip", "balance-origin", "prediction-friction", "breakaway-marker", "static-start", "static-end"]) assert.match(html, new RegExp(`data-drag-target="${target}"`));
for (const id of ["zeroTask", "zeroFrictionType", "zeroFrictionDirection", "zeroFrictionMagnitude", "staticTask", "staticPullPrompt", "staticAppliedReadout", "staticFrictionReadout", "breakawayTask", "breakawayMotionStatus", "breakawayAnswer"]) assert.match(html, new RegExp(`id="${id}"`));
assert.match(html, /Part A 不使用測力計或歸零操作/);
assert.doesNotMatch(html, /id="recordBalance"|id="balanceObservations"|data-action="record-balance"|data-action="save-balance-answer"/);
assert.match(html, /id="liveReadouts"[^>]*aria-live="off"/);
assert.match(html, /id="liveRegion"[^>]*aria-live="polite"/);
assert.match(html, /type="range"/);
assert.match(html, /id="traceTable"/);
assert.match(html, /id="intervalStats"/);
for (const id of ["previousExtremum", "nextExtremum", "jumpSelectionStart", "jumpSelectionEnd"]) assert.match(html, new RegExp(`id="${id}"`));
assert.ok(html.indexOf('id="stageGraph"') < html.indexOf('id="controlPanel"'), "graph must live in the fixed stage, not the scrolling control panel");
assert.match(html, /id="redoExperimentConfirm"[^>]*role="group"/);
assert.match(html, /id="validationStatus"[^>]*tabindex="-1"[^>]*aria-live="off"/);
assert.match(html, /id="predictionReadout"[^>]*aria-live="off"/);
assert.match(html, /<var>F<\/var><sub>拉<\/sub>/);
assert.match(css, /\.stage[^}]*touch-action:\s*pan-y/);
assert.match(css, /\.drag-target[^}]*touch-action:\s*none/);
assert.match(css, /\.control-panel[^}]*overflow-y:\s*auto/);
assert.match(css, /overscroll-behavior:\s*contain/);
assert.match(css, /html,[\s\S]*body[\s\S]*overflow:\s*hidden/);
assert.match(main, /setPointerCapture/);
assert.match(main, /pointercancel/);
assert.match(main, /event\.isPrimary === false/);
assert.match(main, /hostSwipe/);
assert.match(main, /intervalStatsList/);
assert.match(main, /aria-describedby/);
assert.match(main, /localExtremaIndices/);
assert.match(main, /focusAfterAction/);
assert.match(main, /prediction-friction-arrow/);
assert.match(main, /balance-origin/);
assert.doesNotMatch(main, /balanceFriction/);
assert.match(main, /\[data-action\], input, select, \.drag-target/);
console.log("Static/kinetic friction accessibility checks passed");
