"use strict";
const assert = require("node:assert/strict");
const G = require("./generator.js");
const P = require("./physics.js");
const M = require("./measurement.js");
const scenario = G.generateScenario({ seed: 42 });
let state = M.createMeasurementState(scenario);
const physical = P.createInitialState(scenario);
for (let i = 0; i < 120; i += 1) state = M.step(state, physical, scenario, 1 / 240).state;
const before = M.liveReading(state);
state = M.tare(state);
assert.equal(state.tared, true);
assert.equal(state.tareCorrectionCN, Math.round((state.forceFilteredN + state.forceBiasN) * 100));
const samples = [];
for (let i = 0; i <= 300; i += 1) samples.push({ timeS: i * .04, pullCN: Math.min(1100, i * 3), velocityMMps: i > 80 ? Math.min(250, i - 80) : 0 });
const trace = M.packTrace({ regularSamples: samples, breakaway: { timeMs: 3200, measuredPullCN: 720, measuredVelocityMMps: 4, preBreakPeakGridIndex: 80 } });
const unpacked = M.unpackTrace(trace);
assert.equal(unpacked.regularSampleCount, 301);
assert.equal(unpacked.merged.length, 301);
assert.equal(unpacked.breakaway.timeMs, 3200);
assert.equal(unpacked.visibleBreakawayPeakCN, 720);
assert.ok(M.assessTrial(trace).candidates);
assert.ok(M.FORCE_SENSOR_NOISE_MAX_ABS_N >= .045 && M.VELOCITY_NOISE_MAX_ABS_MPS >= .0075);
assert.ok(Number.isFinite(before.forceN));
assert.throws(() => M.unpackTrace({ ...trace, forceVelocityBase64: "bad" }), /trace|base64/);
console.log("Static/kinetic friction measurement checks passed");
