"use strict";
const assert = require("node:assert/strict");
const G = require("./generator.js");
const M = require("./measurement.js");
const S = require("./scoring.js");
const P = require("./persistence.js");
const scenario = G.generateScenario({ seed: 9 });
const samples = Array.from({ length: 301 }, (_, i) => ({ timeS: i * .04, pullCN: i < 50 ? i * 12 : 500, velocityMMps: i < 50 ? 0 : i < 90 ? 100 : i < 110 ? 100 + (i - 90) * 6 : 220 }));
const trial = M.packTrace({ regularSamples: samples, breakaway: { timeMs: 2000, measuredPullCN: 600, measuredVelocityMMps: 4, preBreakPeakGridIndex: 49 } });
let state = P.freshState(scenario.seed);
state = P.transitions.setTare(state, 3);
state = P.transitions.recordObservation(state, { id: "zero-pull", measuredPullCN: 0, measuredVelocityMMps: 0, learnerForce: null });
state = P.transitions.setObservationAnswer(state, "zero-pull", { frictionType: "none", direction: "none", frictionMagnitudeCN: 0, operationDeltaCN: 0, committed: true });
state = P.transitions.recordObservation(state, { id: "static-1", measuredPullCN: 220, measuredVelocityMMps: 0, learnerForce: null });
state = P.transitions.setObservationAnswer(state, "static-1", { frictionType: "static", direction: "left", frictionMagnitudeCN: 220, operationDeltaCN: 0, committed: true });
state = P.transitions.recordObservation(state, { id: "static-1", measuredPullCN: 450, measuredVelocityMMps: 0, learnerForce: null });
state = P.transitions.setObservationAnswer(state, "static-low", { frictionType: "static", direction: "left", frictionMagnitudeCN: 220, operationDeltaCN: 0, committed: true });
state = P.transitions.setObservationAnswer(state, "static-high", { frictionType: "static", direction: "left", frictionMagnitudeCN: 450, operationDeltaCN: 0, committed: true });
assert.equal(state.balance.observations.length, 3);
state = P.transitions.acceptTrial(state, trial);
state = P.transitions.setPhase(state, "analysis");
const candidates = M.findCandidateWindows(trial);
assert.throws(() => P.transitions.setAnalysisTask(state, "fastPlateau", { startIndex: 10, endIndex: 20 }), /active|future/);
state = P.transitions.setAnalysisTask(state, "staticInterval", { ...candidates.static[0], frictionType: "static", relation: "equal" });
state = P.transitions.setAnalysisTask(state, "breakaway", { markerIndex: 50, estimatedFsMaxCN: 600, identifiedAs: "maximum-static-friction" });
state = P.transitions.setAnalysisTask(state, "slowPlateau", { ...candidates.slow[0], estimatedFkCN: 500 });
state = P.transitions.setAnalysisTask(state, "acceleration", { ...candidates.acceleration[0], relation: "pull-greater", pullEqualsFk: "no" });
state = P.transitions.setAnalysisTask(state, "fastPlateau", { ...candidates.fast[0], estimatedFkCN: 500, speedComparison: "same-average" });
state = P.transitions.setPhase(state, "predict");
assert.throws(() => P.transitions.setPrediction(state, 1, { id: scenario.predictions[1].id, scenarioId: scenario.predictions[1].scenarioId, frictionType: null, direction: null, magnitudeCN: null, motionOutcome: null, committed: false }), /active|future/);
const partialPrediction = P.transitions.setPrediction(state, 0, { id: scenario.predictions[0].id, scenarioId: scenario.predictions[0].scenarioId, frictionType: "static", direction: null, magnitudeCN: null, motionOutcome: null, committed: false });
const partialWire = P.encodeDraft(partialPrediction);
assert.deepEqual(P.decodeSnapshot({ version: 1, activity: "static-kinetic-friction-investigation-lab", kind: "draft", answer: partialWire }, scenario, "draft"), partialPrediction);
const malformedPredictionWire = P.clone(partialWire); malformedPredictionWire.P[0][2] = 99;
assert.throws(() => P.decodeSnapshot({ version: 1, activity: "static-kinetic-friction-investigation-lab", kind: "draft", answer: malformedPredictionWire }, scenario, "draft"), /enum/);
scenario.predictions.forEach((spec, index) => { state = P.transitions.setPrediction(state, index, { id: spec.id, scenarioId: spec.scenarioId, frictionType: spec.frictionType, direction: spec.direction, magnitudeCN: spec.magnitudeCN, motionOutcome: spec.motionOutcome, committed: true }); if (index < scenario.predictions.length - 1) { assert.equal(state.variant, "answer-complete"); assert.deepEqual(P.decodeSnapshot({ version: 1, activity: "static-kinetic-friction-investigation-lab", kind: "draft", answer: P.encodeDraft(state) }, scenario, "draft"), state); state = P.transitions.advancePrediction(state); } });
state = P.transitions.setPhase(state, "review");
assert.equal(P.hasCompleteAnswer(state), true);
const edit = P.transitions.enterReviewEdit(state, "analysis", "slowPlateau");
assert.equal(edit.variant, "review-edit");
const cancelled = P.transitions.cancelReviewEdit(edit);
assert.equal(cancelled.phase, "review");
const changedEdit = P.transitions.enterReviewEdit(state, "analysis", "slowPlateau");
const changed = P.transitions.setAnalysisTask(changedEdit, "slowPlateau", { startIndex: 52, endIndex: 95, estimatedFkCN: 500 });
assert.equal(changed.phase, "predict"); assert.equal(changed.variant, "answer-ready"); assert.equal(changed.predictions.every((item) => item === null), true);
const draft = P.encodeDraft(state); P.validateState(P.decodeSnapshot({ version: 1, activity: "static-kinetic-friction-investigation-lab", kind: "draft", answer: draft }, scenario, "draft"));
const review = P.encodeReview(state); assert.equal(review.w, "s1"); const expandedReview = P.decodeSnapshot({ version: 1, activity: "static-kinetic-friction-investigation-lab", kind: "review", answer: review }, scenario, "review"); P.validateState({ ...expandedReview, working: P.emptyWorking() }, { skipVariant: true });
const decoded = expandedReview;
assert.equal(decoded.phase, "review");
assert.deepEqual(P.decodeSnapshot({ version: 1, activity: "static-kinetic-friction-investigation-lab", kind: "review", answer: review }, scenario, "review"), P.normalizeReview(state));
assert.throws(() => P.validateState({ ...P.decodeSnapshot({ version: 1, activity: "static-kinetic-friction-investigation-lab", kind: "draft", answer: draft }, scenario, "draft"), balance: { ...state.balance, tared: false, tareCorrectionCN: 3 } }), /tare|invalid/);
console.log("Static/kinetic friction persistence checks passed");
