"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { XMLParser } = require("fast-xml-parser");
const root = path.resolve(__dirname, "../..");
const slug = "static-kinetic-friction-investigation-lab";
const html = fs.readFileSync(path.join(__dirname, "index.html"), "utf8");
const manifest = fs.readFileSync(path.join(root, "sim/manifests", `${slug}.xml`), "utf8");
const refs = [...html.matchAll(/(?:src|href)="([^"]+)"/g)].map((m) => m[1]).filter((x) => /\.(?:js|css)(?:[?#]|$)/.test(x) && x !== "../config.js").map((x) => { const clean = x.split(/[?#]/)[0]; return clean.startsWith("../") ? clean.slice(3) : `${slug}/${clean}`; }).sort();
const parsed = new XMLParser({ ignoreAttributes: false }).parse(manifest);
const files = [].concat(parsed.manifest.resources.resource.file || []).map((entry) => entry["@_href"]).filter((x) => x !== "config.js" && x !== `${slug}/index.html`).sort();
assert.deepEqual(refs, files);
for (const href of files.concat([`${slug}/index.html`, "config.js"])) assert.ok(fs.existsSync(path.join(root, "sim", href)));
assert.equal(parsed.manifest.resources.resource["@_adlcp:scormtype"], "sco");
const main = fs.readFileSync(path.join(__dirname, "main.js"), "utf8");
const persistence = fs.readFileSync(path.join(__dirname, "persistence.js"), "utf8");
assert.match(main, /loadAttempt/);
assert.match(main, /Physics\.createInputQueue/);
assert.match(main, /Physics\.enqueueInput/);
assert.match(main, /Physics\.inputAt/);
assert.match(main, /event\.timeStamp/);
assert.match(main, /getCoalescedEvents/);
assert.match(main, /frameDurationMs > 50/);
assert.doesNotMatch(main, /frameDurationMs > 250/);
assert.match(main, /first delivered frame establishes the recording clock/);
assert.match(main, /experimentStartupGraceFrames/);
assert.match(main, /first[\s\S]*interval after that baseline is the only startup[\s\S]*hand-off grace/);
assert.match(main, /experimentStartupGraceFrames = 1/);
assert.match(main, /startRecording\(\{ deferLoop: true \}\)/);
assert.match(main, /function rebaseExperimentInputClock/);
assert.match(main, /startExperimentReal: \(\) => startRecording\(\)/);
assert.match(main, /function establishExperimentInputClock/);
assert.match(main, /input\.pageTimeMs - experimentInputPageOriginMs/);
assert.match(main, /state\.working\?\.analysisDraft \|\| state\.analysis/);
assert.match(main, /const analysisDraft = state\.working\?\.analysisDraft/);
assert.match(main, /Boolean\(analysisDraft\) && Persistence\.ANALYSIS_KEYS\.some/);
const persistAnalysisDraft = main.slice(main.indexOf("function persistAnalysisDraft"), main.indexOf("function commitAnalysisDraft"));
assert.doesNotMatch(persistAnalysisDraft, /saveDraft\(/, "Part C draft transition does not perform a second LMS commit");
assert.match(main, /finalizeExperimentRecording\(\{ timedOut: true \}\)/);
assert.match(main, /function stopRecording\(\) \{ return finalizeExperimentRecording/);
const predictionDragDraft = main.slice(main.indexOf("function setPredictionForceDraft"), main.indexOf("function updatePredictionForceFromPointer"));
assert.doesNotMatch(predictionDragDraft, /saveDraft\(/, "Part D pointermove updates only local state and never commits to the LMS");
assert.match(main, /rawForceN[\s\S]*Math\.round\(rawForceN \* 10\) \/ 10/, "A3 force is quantized to 0.1 N before physics consumes it");
assert.match(main, /step\.dataset\.action = "select-prediction"/, "Part D progress steps can switch questions during normal prediction work");
assert.match(main, /document\.createElement\(state\.fromReview \? "span" : "button"\)/, "Part D progress steps remain read-only only during review edits");
assert.match(main, /#predictionCards \.prediction-card\[data-prediction-index=/, "Part D focus and drag code targets the active card instead of a progress button");
assert.match(persistence, /predictionDraft/, "Part D unsaved edits use a separate working draft");
console.log("Static/kinetic friction production wiring checks passed");
