"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { XMLParser } = require("fast-xml-parser");
const root = path.resolve(__dirname, "../..");
const slug = "static-kinetic-friction-investigation-lab";
const html = fs.readFileSync(path.join(__dirname, "index.html"), "utf8");
const manifest = fs.readFileSync(path.join(root, "sim/manifests", `${slug}.xml`), "utf8");
const refs = [...html.matchAll(/(?:src|href)="([^"]+)"/g)].map((m) => m[1]).filter((x) => /\.(?:js|css)(?:[?#]|$)/.test(x) && x !== "../config.js").map((x) => { const clean = x.split(/[?#]/)[0]; return clean.startsWith("../") ? clean.slice(3) : `${slug}/${clean}`; }).sort();
const parsed = new XMLParser({ ignoreAttributes: false }).parse(manifest);
const files = [].concat(parsed.manifest.resources.resource.file || []).map((entry) => entry["@_href"]).filter((x) => x !== "config.js" && x !== `${slug}/index.html`).sort();
assert.deepEqual(refs, files);
for (const href of files.concat([`${slug}/index.html`, "config.js"])) assert.ok(fs.existsSync(path.join(root, "sim", href)));
assert.equal(parsed.manifest.resources.resource["@_adlcp:scormtype"], "sco");
const main = fs.readFileSync(path.join(__dirname, "main.js"), "utf8");
assert.match(main, /loadAttempt/);
assert.match(main, /Physics\.createInputQueue/);
assert.match(main, /Physics\.enqueueInput/);
assert.match(main, /Physics\.inputAt/);
assert.match(main, /event\.timeStamp/);
assert.match(main, /getCoalescedEvents/);
assert.match(main, /frameDurationMs > 50/);
assert.doesNotMatch(main, /frameDurationMs > 250/);
assert.match(main, /finalizeExperimentRecording\(\{ timedOut: true \}\)/);
assert.match(main, /function stopRecording\(\) \{ return finalizeExperimentRecording/);
const predictionDragDraft = main.slice(main.indexOf("function setPredictionForceDraft"), main.indexOf("function updatePredictionForceFromPointer"));
assert.doesNotMatch(predictionDragDraft, /saveDraft\(/, "Part D pointermove updates only local state and never commits to the LMS");
assert.match(main, /rawForceN[\s\S]*Math\.round\(rawForceN \* 10\) \/ 10/, "A3 force is quantized to 0.1 N before physics consumes it");
console.log("Static/kinetic friction production wiring checks passed");
