(function () {
  "use strict";
  const Q = window.KinematicsQuantitativeQuestions; const N = window.KinematicsQuantitativeNotation; const M = window.KinematicsQuantitativeModel; const S = window.KinematicsQuantitativeScoring; const P = window.KinematicsQuantitativePersistence; const U = window.KinematicsQuantitativeUiPolicy;
  if (![Q, N, M, S, P, U, window.SimScorm, window.SimActivityFlow].every(Boolean)) throw new Error("Quantitative graph modules were not loaded");
  const ACTIVITY = "kinematics-quantitative-graph-builder"; const SVG = "http://www.w3.org/2000/svg";
  const el = Object.fromEntries([...document.querySelectorAll("[id]")].map((node) => [node.id, node]));
  const dims = { left: 58, top: 26, width: 620, height: 390, dock: 474, fullHeight: 500 };
  const axisArrowDepth = 12;
  let state = null; let mode = "activity"; let locked = false; let selected = null; let activeGraph = 0; let resultTask = 0; let resultTime = 0; let editors = new Map(); let drag = null; let panelContinuation = null; let cursor = null; let attempt = null; let pendingExpected = null; let reviewNotice = "";
  const diagnostics = { down: 0, move: 0, up: 0, cancel: 0, trustedTouch: 0 };
  const practiceDefinition = Object.freeze({ graphType: "x", times: [0, 4], targets: [], axis: { min: 0, max: 20, step: 1 }, question: { T: 4, x0: 0, v0: 0, a: 0 } });
  function svg(name, attributes = {}) { const node = document.createElementNS(SVG, name); Object.entries(attributes).forEach(([key, value]) => node.setAttribute(key, value)); return node; }
  const escape = N.escape; const graphHtml = (type) => N.graph(type, Q.GRAPH_LABELS[type].split(" ")[0]); const quantityNames = Object.freeze({ x: "位置", v: "速度", a: "加速度" });
  function announce(text) { el.liveRegion.textContent = ""; requestAnimationFrame(() => { el.liveRegion.textContent = text; }); }
  function format(value) { return Number.isInteger(value) ? String(value) : Number(value).toFixed(1); }
  function currentDefinition() { return mode === "practice" ? practiceDefinition : Q.taskDefinition(state.pid, activeGraph); }
  function editorFor(index, definition = currentDefinition()) { const key = mode === "practice" ? "practice" : String(index); if (!editors.has(key)) editors.set(key, new M.Editor(definition, mode === "practice" ? null : state.ans[index])); return editors.get(key); }
  function resetEditor(index) { editors.delete(mode === "practice" ? "practice" : String(index)); return editorFor(index); }
  function transform(definition) { return M.plotTransform(definition.axis, dims.width, dims.height, dims.left, dims.top); }
  function setState(next) { if (!next) return false; state = next; registerDraft(); return true; }
  function saveDraft() { if (!state || locked || mode === "practice") return; try { window.SimScorm.saveDraft(window.SimScorm.makeSnapshot(ACTIVITY, "draft", P.encode(state))); } catch (error) { console.warn(error); } }
  function registerDraft() { if (!state || locked) return; window.SimScorm.setDraftProvider(() => window.SimScorm.makeSnapshot(ACTIVITY, "draft", P.encode(state))); }
  function commitEditor(index, message = "已儲存控制點。") { if (mode !== "practice") { const next = P.setAnswer(state, index, editorFor(index).answer); if (!setState(next)) return; saveDraft(); } render(); announce(message); }
  function restorePanelScroll(scrollTop) { el.controlsPanel.scrollTop = scrollTop; requestAnimationFrame(() => { el.controlsPanel.scrollTop = scrollTop; }); }
  function rollbackActiveDrag(rebuild = true) { if (!drag) return; const panelScrollTop = el.controlsPanel.scrollTop; const active = drag; editorFor(activeGraph).answer = active.before; try { if (active.hit.hasPointerCapture(active.pointerId)) active.hit.releasePointerCapture(active.pointerId); } catch {} drag = null; if (rebuild) { render(); restorePanelScroll(panelScrollTop); } else { active.valueLabel.hidden = true; active.preview.hidden = true; updateBoardDuringDrag(currentDefinition(), editorFor(activeGraph)); } }
  function buildAxes(board, definition, answer) {
    const root = svg("svg", { viewBox: `0 0 740 ${dims.fullHeight}`, preserveAspectRatio: "xMidYMid meet", class: "graph-svg", role: "img", "aria-label": graphAria(definition, answer) }); const clip = svg("clipPath", { id: "plotClip" }); clip.append(svg("rect", { x: dims.left, y: dims.top, width: dims.width, height: dims.height })); root.append(clip);
    const T = definition.question.T; const tx = transform(definition); const grid = svg("g");
    for (let t = 0; t <= T; t += 1) { const x = tx.toX(t, T); grid.append(svg("line", { x1: x, x2: x, y1: dims.top, y2: dims.top + dims.height, class: definition.times.includes(t) ? "guide" : "grid" })); const label = svg("text", { x, y: dims.top + dims.height + 22, class: "tick", "text-anchor": "middle" }); label.textContent = t; grid.append(label); }
    for (let value = definition.axis.min; value <= definition.axis.max; value += definition.axis.step) { const y = tx.toY(value); grid.append(svg("line", { x1: dims.left, x2: value === 0 ? dims.left + dims.width - axisArrowDepth : dims.left + dims.width, y1: y, y2: y, class: value === 0 ? "axis axis-horizontal" : "grid", "data-axis-value": value })); if (value === definition.axis.min || value === definition.axis.max || value % (definition.graphType === "x" ? 5 : 1) === 0) { const label = svg("text", { x: dims.left - 8, y: y + 4, class: "tick", "text-anchor": "end" }); label.textContent = value; grid.append(label); } }
    root.append(grid); root.append(svg("line", { x1: dims.left, x2: dims.left, y1: dims.top + axisArrowDepth, y2: dims.top + dims.height, class: "axis axis-vertical", "data-axis-role": "vertical" })); appendAxisArrows(root, definition);
    const svgText = (node, parts) => parts.forEach(([text, className]) => { const span = svg("tspan", className ? { class: className } : {}); span.textContent = text; node.append(span); }); const xLabel = svg("text", { x: dims.left + dims.width + 8, y: tx.toY(0) + 5, class: "axis-label time-axis-label", "text-anchor": "start" }); svgText(xLabel, [["t", "math-var"], [" / s", "upright-unit"]]); root.append(xLabel); const yLabel = svg("text", { x: dims.left, y: dims.top - 10, class: "axis-label", "text-anchor": "start" }); const yUnit = definition.graphType === "x" ? "m" : definition.graphType === "v" ? "(m/s)" : "(m/s²)"; svgText(yLabel, [[definition.graphType, "math-var"], [" / ", ""], [yUnit, "upright-unit"]]); root.append(yLabel);
    board.append(root); return root;
  }
  function appendAxisArrows(target, definition) {
    const tx = transform(definition); const right = dims.left + dims.width; const zeroY = tx.toY(0);
    target.append(
      svg("polygon", { points: `${right - axisArrowDepth},${zeroY - 7} ${right},${zeroY} ${right - axisArrowDepth},${zeroY + 7}`, class: "axis-arrow axis-arrow-time", "data-axis-direction": "time-positive", "data-base-x": right - axisArrowDepth, "data-tip-x": right, "data-tip-y": zeroY }),
      svg("polygon", { points: `${dims.left - 7},${dims.top + axisArrowDepth} ${dims.left},${dims.top} ${dims.left + 7},${dims.top + axisArrowDepth}`, class: "axis-arrow axis-arrow-value", "data-axis-direction": "value-positive", "data-base-y": dims.top + axisArrowDepth, "data-tip-x": dims.left, "data-tip-y": dims.top })
    );
  }
  function graphAria(definition, answer) { const name = Q.GRAPH_LABELS[definition.graphType] || "示範位置—時間圖"; const unit = Q.UNITS[definition.graphType] || "m"; const status = answer.map((value, index) => `t=${definition.times[index]} s：${value == null ? "未設定" : `${value} ${unit}`}`).join("；"); return `${name}，縱軸範圍 ${definition.axis.min} 至 ${definition.axis.max} ${unit}。${status}`; }
  function pathD(points, definition) { const tx = transform(definition); return points.map(([time, value], index) => `${index ? "L" : "M"}${tx.toX(time, definition.question.T).toFixed(2)},${tx.toY(value).toFixed(2)}`).join(" "); }
  function positionHit(hit, definition, index, value) { const tx = transform(definition); const x = tx.toX(definition.times[index], definition.question.T); const y = value == null ? dims.dock : tx.toY(value); hit.style.left = `${x / 740 * 100}%`; hit.style.top = `${y / dims.fullHeight * 100}%`; }
  function renderMagnifier(definition, coordinate, x, y) {
    const viewWidth = 180; const viewHeight = 120; const viewX = M.clamp(x - viewWidth / 2, 0, 740 - viewWidth); const viewY = M.clamp(y - viewHeight / 2, 0, dims.fullHeight - viewHeight);
    const lens = svg("svg", { class: "drag-magnifier-svg", viewBox: `${viewX} ${viewY} ${viewWidth} ${viewHeight}`, preserveAspectRatio: "xMidYMid meet", "aria-hidden": "true", "data-center-x": x, "data-center-y": y });
    lens.append(svg("rect", { x: 0, y: 0, width: 740, height: dims.fullHeight, class: "magnifier-background" }));
    const context = svg("g", { class: "magnifier-context" }); const tx = transform(definition);
    for (let time = 0; time <= definition.question.T; time += 1) { const gridX = tx.toX(time, definition.question.T); context.append(svg("line", { x1: gridX, x2: gridX, y1: dims.top, y2: dims.top + dims.height, class: definition.times.includes(time) ? "guide" : "grid" })); }
    for (let axisValue = definition.axis.min; axisValue <= definition.axis.max; axisValue += definition.axis.step) { const gridY = tx.toY(axisValue); context.append(svg("line", { x1: dims.left, x2: axisValue === 0 ? dims.left + dims.width - axisArrowDepth : dims.left + dims.width, y1: gridY, y2: gridY, class: axisValue === 0 ? "axis axis-horizontal" : "grid", "data-axis-value": axisValue })); }
    context.append(svg("line", { x1: dims.left, x2: dims.left, y1: dims.top + axisArrowDepth, y2: dims.top + dims.height, class: "axis axis-vertical", "data-axis-role": "vertical" })); appendAxisArrows(context, definition);
    lens.append(context);
    const cueX = viewX + viewWidth - 38; const cueY = viewY + viewHeight - 12; const cue = svg("g", { class: "magnifier-orientation", "data-cue-anchor-x": cueX, "data-cue-anchor-y": cueY });
    cue.append(
      svg("line", { x1: cueX, y1: cueY, x2: cueX + 18, y2: cueY, class: "magnifier-orientation-axis", "data-cue-direction": "time-positive" }),
      svg("polygon", { points: `${cueX + 18},${cueY - 6} ${cueX + 26},${cueY} ${cueX + 18},${cueY + 6}`, class: "magnifier-orientation-arrow", "data-cue-direction": "time-positive", "data-base-x": cueX + 18, "data-tip-x": cueX + 26, "data-tip-y": cueY }),
      svg("line", { x1: cueX, y1: cueY, x2: cueX, y2: cueY - 16, class: "magnifier-orientation-axis", "data-cue-direction": "value-positive" }),
      svg("polygon", { points: `${cueX - 6},${cueY - 16} ${cueX},${cueY - 24} ${cueX + 6},${cueY - 16}`, class: "magnifier-orientation-arrow", "data-cue-direction": "value-positive", "data-base-y": cueY - 16, "data-tip-x": cueX, "data-tip-y": cueY - 24 })
    );
    lens.append(cue);
    const studentPath = el.graphMount.querySelector(".student-path")?.getAttribute("d") || ""; lens.append(svg("path", { class: "student-path magnifier-student-path", d: studentPath }));
    lens.append(svg("line", { x1: x - 22, x2: x + 22, y1: y, y2: y, class: "magnifier-crosshair" }), svg("line", { x1: x, x2: x, y1: y - 22, y2: y + 22, class: "magnifier-crosshair" }), svg("circle", { cx: x, cy: y, r: 9, class: "magnifier-point" }));
    const title = document.createElement("span"); title.className = "drag-preview-title"; title.textContent = "局部放大";
    const readout = document.createElement("span"); readout.className = "drag-preview-coordinate"; readout.innerHTML = coordinate;
    drag.preview.replaceChildren(title, lens, readout); drag.preview.hidden = false;
  }
  function updateDragUi(definition, value) { if (!drag || value == null) return; const tx = transform(definition); const x = tx.toX(definition.times[drag.index], definition.question.T); const y = tx.toY(value); const coordinate = N.dragCoordinate(drag.index, definition.times[drag.index], definition.graphType, value); drag.valueLabel.innerHTML = coordinate; drag.valueLabel.hidden = false; const board = el.graphMount.querySelector(".graph-board"); const labelWidth = drag.valueLabel.offsetWidth; const labelHeight = drag.valueLabel.offsetHeight; const markerCssX = x / 740 * board.clientWidth; const markerCssY = y / dims.fullHeight * board.clientHeight; const left = markerCssX < board.clientWidth / 2 ? markerCssX + 18 : markerCssX - labelWidth - 18; drag.valueLabel.style.left = `${Math.max(4, Math.min(board.clientWidth - labelWidth - 4, left))}px`; drag.valueLabel.style.top = `${Math.max(labelHeight / 2 + 4, Math.min(board.clientHeight - labelHeight / 2 - 4, markerCssY))}px`; if (drag.pointerType === "touch" && drag.moved) renderMagnifier(definition, coordinate, x, y); }
  function buildBoard(definition, editor, review = false) {
    el.graphMount.replaceChildren(); const board = document.createElement("div"); board.className = "graph-board"; el.graphMount.append(board); const root = buildAxes(board, definition, editor.answer); const overlay = document.createElement("div"); overlay.className = "hit-overlay"; const valueLabel = document.createElement("div"); valueLabel.className = "drag-value-label"; valueLabel.hidden = true; valueLabel.setAttribute("aria-hidden", "true"); const preview = document.createElement("div"); preview.className = "drag-preview"; preview.hidden = true; preview.setAttribute("aria-hidden", "true"); board.append(overlay, valueLabel, preview);
    const paths = svg("g", { "clip-path": "url(#plotClip)" }); root.append(paths);
    const student = svg("path", { class: "student-path" }); paths.append(student);
    const correct = svg("path", { class: "correct-path" }); if (review) { correct.setAttribute("d", pathD(M.sampledPath(definition, definition.targets), definition)); paths.append(correct); }
    const markers = svg("g"); root.append(markers); const hits = [];
    editor.answer.forEach((value, index) => {
      const x = transform(definition).toX(definition.times[index], definition.question.T); const y = value == null ? dims.dock : transform(definition).toY(value); const dock = svg("rect", { x: x - 17, y: dims.dock - 17, width: 34, height: 34, rx: 5, class: "dock", "data-dock-index": index }); if (value !== null) dock.setAttribute("visibility", "hidden"); markers.append(dock); markers.append(svg("circle", { cx: x, cy: y, r: value == null ? 4 : 7, class: `point-dot ${selected === index ? "selected" : ""}`, "data-marker-index": index }));
      const hit = document.createElement("button"); hit.className = "point-hit"; hit.type = "button"; hit.dataset.index = index; hit.dataset.quantity = definition.graphType; hit.setAttribute("aria-selected", String(selected === index)); hit.setAttribute("aria-label", `控制點 P${index}，t=${definition.times[index]} s，${value == null ? "未設定" : `${value} ${Q.UNITS[definition.graphType] || "m"}`}`); hit.tabIndex = review ? -1 : 0; positionHit(hit, definition, index, value); overlay.append(hit); hits.push(hit);
    });
    const fn = M.graphFunction(definition, editor.answer); if (fn) student.setAttribute("d", pathD(M.sampledPath(definition, editor.answer), definition));
    if (review) addCursor(board, root, overlay, definition, editor); else hits.forEach((hit) => bindPoint(hit, definition, editor));
    return board;
  }
  function bindPoint(hit, definition, editor) {
    hit.addEventListener("pointerdown", (event) => {
      if (drag && event.pointerId !== drag.pointerId) { event.preventDefault(); return; } if (locked || drag || !event.isPrimary) return; diagnostics.down += 1; if (event.pointerType === "touch" && event.isTrusted) diagnostics.trustedTouch += 1; const index = Number(hit.dataset.index); selected = index; syncSelectedRows(); const rect = el.graphMount.querySelector(".graph-board").getBoundingClientRect(); const current = editor.answer[index]; const y = current == null ? dims.dock / dims.fullHeight * rect.height : transform(definition).toY(current) / dims.fullHeight * rect.height; const preview = rect.left + rect.width / 2 < event.clientX ? "left" : "right"; const vertical = rect.top + rect.height / 2 < event.clientY ? "top" : "bottom"; drag = { pointerId: event.pointerId, index, before: editor.answer.slice(), startY: event.clientY, lastY: event.clientY, offset: event.clientY - (rect.top + y), moved: false, hit, pointerType: event.pointerType, valueLabel: rect ? el.graphMount.querySelector(".drag-value-label") : null, preview: el.graphMount.querySelector(".drag-preview") }; drag.preview.classList.add(`is-${vertical}-${preview}`); hit.setPointerCapture(event.pointerId); updateBoardDuringDrag(definition, editor); event.preventDefault();
    });
    hit.addEventListener("pointermove", (event) => { if (!drag || drag.pointerId !== event.pointerId) return; diagnostics.move += 1; const delta = event.clientY - drag.startY; if (!drag.moved && Math.abs(delta) < M.ACTIVATION_THRESHOLD_CSS_PX) return; drag.moved = true; const rect = el.graphMount.querySelector(".graph-board").getBoundingClientRect(); const local = (event.clientY - drag.offset - rect.top) / rect.height * dims.fullHeight; const value = M.snap(transform(definition).fromY(local), definition.axis); editor.answer[drag.index] = value; drag.lastY = event.clientY; updateBoardDuringDrag(definition, editor); updateDragUi(definition, value); event.preventDefault(); });
    const finish = (event, rollback) => { if (!drag || drag.pointerId !== event.pointerId) return; const panelScrollTop = el.controlsPanel.scrollTop; if (event.type === "pointercancel" || rollback) diagnostics.cancel += 1; else diagnostics.up += 1; const current = drag; const changed = JSON.stringify(editor.answer) !== JSON.stringify(current.before); drag = null; if (rollback || !changed) editor.answer = current.before; else { const chosen = editor.answer[current.index]; editor.answer = current.before; editor.commit(current.before.map((value, index) => index === current.index ? chosen : value)); commitEditor(activeGraph, "已以吸附刻度儲存控制點。"); } render(); restorePanelScroll(panelScrollTop); };
    hit.addEventListener("pointerup", (event) => finish(event, false)); hit.addEventListener("pointercancel", (event) => finish(event, true)); hit.addEventListener("lostpointercapture", (event) => finish(event, true));
    hit.addEventListener("keydown", (event) => { if (locked) return; const index = Number(hit.dataset.index); let changed = false; if (["ArrowUp", "ArrowRight", "ArrowDown", "ArrowLeft"].includes(event.key)) { const sign = ["ArrowUp", "ArrowRight"].includes(event.key) ? 1 : -1; changed = editor.step(index, sign * (event.shiftKey ? 5 : 1)); } else if (["Delete", "Backspace"].includes(event.key)) changed = editor.clear(index); else if (["Enter", " "].includes(event.key)) selected = index; if (changed) { commitEditor(activeGraph, "已以鍵盤更新控制點。"); requestAnimationFrame(() => el.graphMount.querySelector(`.point-hit[data-index="${index}"]`)?.focus()); } else if (event.key === "Escape") render(); if (changed || ["Enter", " "].includes(event.key)) event.preventDefault(); });
  }
  function syncSelectedRows() { [el.pointRows, el.practiceRows].forEach((container) => container.querySelectorAll(".point-row").forEach((row) => row.classList.toggle("is-selected", Number(row.dataset.index) === selected))); }
  function updateBoardDuringDrag(definition, editor) { const board = el.graphMount.querySelector(".graph-board"); if (!board) return; syncSelectedRows(); const svgPath = board.querySelector(".student-path"); const fn = M.graphFunction(definition, editor.answer); svgPath.setAttribute("d", fn ? pathD(M.sampledPath(definition, editor.answer), definition) : ""); const tx = transform(definition); board.querySelectorAll(".point-hit").forEach((hit, index) => positionHit(hit, definition, index, editor.answer[index])); board.querySelectorAll("[data-marker-index]").forEach((marker) => { const index = Number(marker.dataset.markerIndex); const value = editor.answer[index]; const isSelected = selected === index; marker.classList.toggle("selected", isSelected); marker.setAttribute("cy", value == null ? dims.dock : tx.toY(value)); marker.setAttribute("r", isSelected ? 8 : value == null ? 4 : 7); }); board.querySelectorAll("[data-dock-index]").forEach((dock) => { const index = Number(dock.dataset.dockIndex); dock.setAttribute("visibility", editor.answer[index] == null ? "visible" : "hidden"); }); const index = drag?.index ?? selected; const value = editor.answer[index]; el.editorStatus.innerHTML = `目前 P<sub class="numeric-subscript">${index ?? ""}</sub>：${value == null ? "未設定" : N.quantity(value, definition.graphType)}`; }
  function updateCursor(time, announceChange = true) { if (!cursor) return; resultTime = M.clamp(Math.round(time * 2) / 2, 0, cursor.definition.question.T); const x = transform(cursor.definition).toX(resultTime, cursor.definition.question.T); cursor.line.setAttribute("x1", x); cursor.line.setAttribute("x2", x); cursor.hit.style.left = `${x / 740 * 100}%`; cursor.hit.setAttribute("aria-valuenow", resultTime); cursor.hit.setAttribute("aria-valuetext", `${resultTime} 秒`); const q = cursor.definition.question; const correct = `t=${format(resultTime)} s；正確 x=${format(Q.valueAt(q, "x", resultTime))} m，v=${format(Q.valueAt(q, "v", resultTime))} m/s，a=${format(Q.valueAt(q, "a", resultTime))} m/s²`; const correctHtml = `${N.variable("t")}=${N.quantity(format(resultTime), "t")}；正確 ${N.variable("x")}=${N.quantity(format(Q.valueAt(q, "x", resultTime)), "x")}，${N.variable("v")}=${N.quantity(format(Q.valueAt(q, "v", resultTime)), "v")}，${N.variable("a")}=${N.quantity(format(Q.valueAt(q, "a", resultTime)), "a")}`;
    const student = M.graphFunction(cursor.definition, state.ans[resultTask]); el.cursorReadout.innerHTML = student ? `${correctHtml}；你的 ${N.variable(cursor.definition.graphType)}(${N.variable("t")})=${N.quantity(format(student.valueAt(resultTime)), cursor.definition.graphType)}` : `${correctHtml}；你的這幅圖尚未完成，不能外推。`; if (announceChange) announce(correct); }
  function addCursor(board, root, overlay, definition, editor) {
    const x = transform(definition).toX(resultTime, definition.question.T); const line = svg("line", { x1: x, x2: x, y1: dims.top, y2: dims.top + dims.height, class: "time-cursor" }); root.append(line); const hit = document.createElement("button"); hit.className = "time-cursor-hit"; hit.type = "button"; hit.setAttribute("role", "slider"); hit.setAttribute("aria-label", "結果時間游標：同步查看 x(t)、v(t)、a(t)"); hit.setAttribute("aria-valuemin", "0"); hit.setAttribute("aria-valuemax", definition.question.T); hit.style.top = `${(dims.top + dims.height / 2) / dims.fullHeight * 100}%`; overlay.append(hit); cursor = { board, line, hit, definition, editor, before: resultTime }; updateCursor(resultTime, false);
    hit.addEventListener("keydown", (event) => { let next = resultTime; if (["ArrowLeft", "ArrowDown"].includes(event.key)) next -= .5; else if (["ArrowRight", "ArrowUp"].includes(event.key)) next += .5; else if (event.key === "Home") next = 0; else if (event.key === "End") next = definition.question.T; else return; event.preventDefault(); updateCursor(next); });
    let cursorDrag = null;
    hit.addEventListener("pointerdown", (event) => { if (!event.isPrimary) return; cursorDrag = { pointerId: event.pointerId, before: resultTime }; hit.setPointerCapture(event.pointerId); event.preventDefault(); });
    hit.addEventListener("pointermove", (event) => { if (!cursorDrag || cursorDrag.pointerId !== event.pointerId) return; const rect = board.getBoundingClientRect(); const svgX = (event.clientX - rect.left) / rect.width * 740; updateCursor((svgX - dims.left) / dims.width * definition.question.T); event.preventDefault(); });
    hit.addEventListener("pointerup", (event) => { if (!cursorDrag || cursorDrag.pointerId !== event.pointerId) return; cursorDrag = null; });
    const rollbackCursor = (event) => { if (!cursorDrag || cursorDrag.pointerId !== event.pointerId) return; const before = cursorDrag.before; cursorDrag = null; updateCursor(before); };
    hit.addEventListener("pointercancel", rollbackCursor); hit.addEventListener("lostpointercapture", rollbackCursor);
  }
  function updateRows(definition, editor) { el.pointRows.replaceChildren(); const unit = Q.UNITS[definition.graphType]; editor.answer.forEach((value, index) => { const row = document.createElement("div"); row.className = `point-row ${selected === index ? "is-selected" : ""}`; row.dataset.index = index; const context = document.createElement("div"); context.className = "point-context"; context.innerHTML = N.pointLabel(index, definition.times[index]); const controls = document.createElement("div"); controls.className = "point-control-line"; const label = document.createElement("label"); const inputId = `point-${index}`; label.htmlFor = inputId; label.innerHTML = `${N.variable(definition.graphType, index)}：`;
      const input = document.createElement("input"); input.id = inputId; input.type = "number"; input.step = "1"; input.min = definition.axis.min; input.max = definition.axis.max; input.placeholder = "未設定"; input.value = value ?? ""; input.setAttribute("aria-label", `控制點 P${index}，t=${definition.times[index]} s，${quantityNames[definition.graphType]} ${definition.graphType} 下標 ${index}，單位 ${unit}`);
      const apply = () => { const raw = input.value.trim(); let changed = false; if (raw === "") changed = editor.clear(index); else if (/^-?\d+$/.test(raw) && Number(raw) >= definition.axis.min && Number(raw) <= definition.axis.max) changed = editor.set(index, Number(raw)); if (changed) commitEditor(activeGraph, "已以數值欄更新控制點。"); else { if (raw) el.editorStatus.textContent = `請輸入 ${definition.axis.min} 至 ${definition.axis.max} 的整數。`; render(); } }; input.addEventListener("change", apply); input.addEventListener("keydown", (event) => { if (event.key === "Enter") { apply(); input.blur(); } });
      const unitLabel = document.createElement("span"); unitLabel.className = "point-unit upright-unit"; unitLabel.textContent = unit;
      const minus = document.createElement("button"); minus.textContent = "−"; minus.setAttribute("aria-label", `減少 P${index}`); minus.addEventListener("click", () => { if (editor.step(index, -1)) commitEditor(activeGraph, "已微調控制點。"); }); const plus = document.createElement("button"); plus.textContent = "+"; plus.setAttribute("aria-label", `增加 P${index}`); plus.addEventListener("click", () => { if (editor.step(index, 1)) commitEditor(activeGraph, "已微調控制點。"); }); const clear = document.createElement("button"); clear.textContent = "清除"; clear.setAttribute("aria-label", `清除 P${index}`); clear.addEventListener("click", () => { if (editor.clear(index)) commitEditor(activeGraph, "已清除控制點。 "); }); controls.append(label, input, unitLabel, minus, plus, clear); row.append(context, controls); el.pointRows.append(row); });
  }
  function updatePracticeRows(editor) { el.practiceRows.replaceChildren(); editor.answer.forEach((value, index) => { const row = document.createElement("div"); row.className = `point-row ${selected === index ? "is-selected" : ""}`; row.dataset.index = index; const context = document.createElement("div"); context.className = "point-context"; context.innerHTML = N.pointLabel(index, practiceDefinition.times[index]); const controls = document.createElement("div"); controls.className = "point-control-line"; const label = document.createElement("label"); const inputId = `practice-point-${index}`; label.htmlFor = inputId; label.innerHTML = `${N.variable("x", index)}：`; const input = document.createElement("input"); input.id = inputId; input.type = "number"; input.step = "1"; input.min = practiceDefinition.axis.min; input.max = practiceDefinition.axis.max; input.placeholder = "未設定"; input.value = value ?? ""; input.setAttribute("aria-label", `練習控制點 P${index}，t=${practiceDefinition.times[index]} s，位置 x 下標 ${index}，單位 m`); const change = () => { const raw = input.value.trim(); if (raw === "") editor.clear(index); else if (/^\d+$/.test(raw) && Number(raw) >= practiceDefinition.axis.min && Number(raw) <= practiceDefinition.axis.max) editor.set(index, Number(raw)); else { el.phaseCopy.textContent = `練習值必須是 ${practiceDefinition.axis.min} 至 ${practiceDefinition.axis.max} 的整數。`; } render(); }; input.addEventListener("change", change); const unitLabel = document.createElement("span"); unitLabel.className = "point-unit upright-unit"; unitLabel.textContent = "m"; const minus = document.createElement("button"); minus.textContent = "−"; minus.setAttribute("aria-label", `減少練習 P${index}`); minus.addEventListener("click", () => { editor.step(index, -1); render(); }); const plus = document.createElement("button"); plus.textContent = "+"; plus.setAttribute("aria-label", `增加練習 P${index}`); plus.addEventListener("click", () => { editor.step(index, 1); render(); }); const clear = document.createElement("button"); clear.textContent = "清除"; clear.setAttribute("aria-label", `清除練習 P${index}`); clear.addEventListener("click", () => { editor.clear(index); render(); }); controls.append(label, input, unitLabel, minus, plus, clear); row.append(context, controls); el.practiceRows.append(row); }); }
  function renderTask() {
    const definition = currentDefinition(); const editor = editorFor(activeGraph, definition); el.practiceView.classList.toggle("is-hidden", mode !== "practice"); el.taskView.classList.toggle("is-hidden", mode !== "activity"); el.reviewView.classList.add("is-hidden"); el.resultView.classList.add("is-hidden"); el.technicalView.classList.add("is-hidden");
    if (mode === "practice") { el.phaseCopy.textContent = "練習圖上的點不會影響正式挑戰。"; updatePracticeRows(editor); el.practiceClear.disabled = editor.answer.every((value) => value === null); buildBoard(definition, editor); return; }
    const question = definition.question; el.phaseCopy.textContent = "四個單段運動情境。"; el.missionKicker.textContent = `任務 ${definition.missionIndex + 1}/4`; el.missionTitle.innerHTML = graphHtml(definition.graphType); el.missionPrompt.innerHTML = N.prompt(question, definition.missionIndex);
    el.graphButtons.replaceChildren(); [0, 1, 2].forEach((offset) => { const index = Math.floor(activeGraph / 3) * 3 + offset; const task = Q.taskDefinition(state.pid, index); const button = document.createElement("button"); button.innerHTML = graphHtml(task.graphType); button.setAttribute("aria-pressed", String(index === activeGraph)); button.addEventListener("click", () => { activeGraph = index; selected = null; setState(P.switchTask(state, index)); render(); }); el.graphButtons.append(button); });
    el.graphSummary.innerHTML = N.summary(definition.times, definition.axis, definition.graphType); el.controlPointInstruction.innerHTML = N.controlsInstruction(definition.times.length); updateRows(definition, editor); el.undoButton.disabled = !editor.undo.length; el.redoButton.disabled = !editor.redo.length; el.clearGraphButton.disabled = editor.answer.every((value) => value === null); el.nextButton.textContent = state.mode === "edit" ? "返回提交前檢視" : "下一幅圖"; buildBoard(definition, editor);
  }
  function completeness(answer, definition) { if (!answer) return "未設定"; return M.isComplete(answer, definition) ? "已完整" : "部分完成"; }
  function thumbnail(definition, answer) { const image = svg("svg", { viewBox: "0 0 140 90", class: "review-thumb", role: "img", "aria-label": `${Q.GRAPH_LABELS[definition.graphType]}學生目前圖線縮圖` }); image.append(svg("rect", { x: 12, y: 8, width: 118, height: 64, fill: "#fff", stroke: "#94a3b8" })); const scale = M.plotTransform(definition.axis, 118, 64, 12, 8); const fn = M.graphFunction(definition, answer); if (fn) image.append(svg("path", { d: M.sampledPath(definition, answer).map(([time, value], index) => `${index ? "L" : "M"}${scale.toX(time, definition.question.T)},${scale.toY(value)}`).join(" "), class: "student-path" })); return image; }
  function renderReview() { mode = "review"; el.practiceView.classList.add("is-hidden"); el.taskView.classList.add("is-hidden"); el.resultView.classList.add("is-hidden"); el.technicalView.classList.add("is-hidden"); el.reviewView.classList.remove("is-hidden"); el.phaseCopy.textContent = "已開啟全部十二幅圖。"; el.reviewStatus.textContent = reviewNotice; el.reviewList.replaceChildren(); for (let mission = 0; mission < 4; mission += 1) { const item = document.createElement("article"); item.className = "review-mission"; const heading = document.createElement("strong"); heading.textContent = `任務 ${mission + 1}`; const statuses = document.createElement("p"); statuses.innerHTML = [0, 1, 2].map((offset) => { const index = mission * 3 + offset; const definition = Q.taskDefinition(state.pid, index); return `${graphHtml(definition.graphType)}：${escape(completeness(state.ans[index], definition))}`; }).join("<br>"); const thumbs = document.createElement("div"); thumbs.className = "review-thumbs"; [0, 1, 2].forEach((offset) => thumbs.append(thumbnail(Q.taskDefinition(state.pid, mission * 3 + offset), state.ans[mission * 3 + offset]))); const button = document.createElement("button"); button.textContent = "返回編輯此情境"; button.addEventListener("click", () => { activeGraph = mission * 3; setState(P.openReviewEdit(state, activeGraph)); mode = "activity"; render(); }); item.append(heading, statuses, thumbs, button); el.reviewList.append(item); } el.graphMount.replaceChildren(); }
  function renderResult() { const definition = Q.taskDefinition(state.pid, resultTask); const editor = new M.Editor(definition, state.ans[resultTask]); mode = "result"; locked = true; el.practiceView.classList.add("is-hidden"); el.taskView.classList.add("is-hidden"); el.reviewView.classList.add("is-hidden"); el.technicalView.classList.add("is-hidden"); el.resultView.classList.remove("is-hidden"); const result = S.scoreActivity(state.pid, state.ans); el.phaseCopy.textContent = "提交後的答案已鎖定；可用時間游標同步檢討三圖。"; el.resultTitle.textContent = "提交結果"; el.resultScore.textContent = `分數：${format(result.score)} / 100；${result.passed ? "已通過" : "未通過"}`; el.resultTabs.replaceChildren(); Q.TASKS.forEach((task, index) => { const button = document.createElement("button"); button.innerHTML = `任務 ${task.missionIndex + 1} ${graphHtml(task.graphType)}`; button.setAttribute("aria-pressed", String(index === resultTask)); button.addEventListener("click", () => { resultTask = index; resultTime = 0; renderResult(); }); el.resultTabs.append(button); }); const graph = result.details[resultTask]; const quantity = definition.graphType; const coordinates = definition.times.map((time, index) => `${N.variable("t")}=${N.quantity(time, "t")}：你的 ${N.variable(quantity)}=${state.ans[resultTask]?.[index] == null ? "--" : N.quantity(state.ans[resultTask][index], quantity)}；正確 ${N.variable(quantity)}=${N.quantity(definition.targets[index], quantity)}`).join("；"); const diagnosticsText = result.diagnostics[Math.floor(resultTask / 3)] || ""; el.resultFeedback.innerHTML = `圖例：藍色實線＝你的圖線；橙色虛線＝正確圖線。本圖得分：${format(graph.score)} / ${format(graph.maxScore)}。${coordinates}。${N.text(graph.feedback.join(" "))}${diagnosticsText ? ` ${N.text(diagnosticsText)}` : ""}`; buildBoard(definition, editor, true); }
  function renderTechnical(kind, message) { mode = "technical"; locked = true; el.practiceView.classList.add("is-hidden"); el.taskView.classList.add("is-hidden"); el.reviewView.classList.add("is-hidden"); el.resultView.classList.add("is-hidden"); el.technicalView.classList.remove("is-hidden"); el.technicalRetryButton.classList.add("is-hidden"); const view = U.technicalResult(kind); el.technicalTitle.textContent = view.title; el.technicalMessage.textContent = message || view.message; el.phaseCopy.textContent = view.message; el.graphMount.replaceChildren(); }
  function showPendingRetry() { el.technicalRetryButton.classList.remove("is-hidden"); el.technicalRetryButton.textContent = "重試同一份提交"; }
  function retryPendingSubmission() { const outcome = window.SimScorm.retryPending(); const returned = outcome.review; const decoded = P.decodeReview(returned?.answer); const computed = decoded ? S.scoreActivity(decoded.pid, decoded.ans) : null; const decision = U.pendingReturnDecision(outcome, pendingExpected, decoded, computed); if (decision === "quarantine") { window.SimScorm.quarantinePending(); return renderTechnical("technical", "重試回傳資料未能安全驗證，已停止重試。 "); } if (decision === "review") { state = P.reviewToState(decoded); renderResult(); return; } if (decision === "committed") { state = P.reviewToState(decoded); renderResult(); el.retryButton.classList.remove("is-hidden"); el.retryButton.textContent = "完成離開程序"; return; } if (decision === "pending") { renderTechnical("pending", outcome.reason); showPendingRetry(); return; } renderTechnical("technical", "重試提交未能安全完成。 "); }
  function render() { if (mode === "review") renderReview(); else if (mode === "result") renderResult(); else if (mode === "technical") return; else renderTask(); }
  function makeReviewSnapshot(result) { const review = P.makeReview(state); const snapshot = window.SimScorm.makeSnapshot(ACTIVITY, "review", review, result); snapshot.maxScore = result.maxScore; if (new TextEncoder().encode(JSON.stringify(snapshot)).length > 2200) throw new Error("Review snapshot exceeds budget"); return snapshot; }
  function restoreFinished(snapshot, attemptData) { const review = P.decodeReview(snapshot?.answer); const recorded = U.attemptSummary(attemptData); const fallback = `已完成記錄未能安全驗證；活動保持鎖定。Moodle 記錄分數：${recorded.score}；狀態：${recorded.status}。`; if (!review || !U.validResultMetadata(snapshot)) return renderTechnical("technical", fallback); state = P.reviewToState(review); const computed = S.scoreActivity(state.pid, state.ans); const trust = U.reviewOutcome(computed, snapshot, attemptData); if (!trust.trusted) return renderTechnical("technical", fallback); renderResult(); }
  function submit() { const result = S.scoreActivity(state.pid, state.ans); let review; try { review = makeReviewSnapshot(result); } catch (error) { renderTechnical("technical", error.message); return; } const handle = (outcome) => U.submission(outcome, { success: () => { state = P.reviewToState(review.answer); renderResult(); }, committed: () => { state = P.reviewToState(review.answer); renderResult(); el.retryButton.classList.remove("is-hidden"); el.retryButton.textContent = "完成離開程序"; }, frozen: (failure) => { pendingExpected = review; state = P.reviewToState(review.answer); renderTechnical("pending", failure?.reason); showPendingRetry(); }, retry: (failure) => { if (failure?.retryable) { reviewNotice = U.retryableRetryMessage; mode = "review"; locked = false; renderReview(); } else renderTechnical("technical", "提交失敗，且系統未能安全承諾可重試。 "); } }); window.SimScorm.submitWithCallbacks(result, review, { onSuccess: handle, onFailure: handle }); }
  function startup() { attempt = window.SimScorm.loadAttempt(ACTIVITY); const startupState = window.SimActivityFlow.startup(attempt); if (startupState === "editable") { const restored = attempt.snapshot?.answer ? P.decode(attempt.snapshot.answer) : null; if (attempt.snapshot?.answer && !restored) return renderTechnical("technical", "草稿資料無法安全還原。 "); state = restored || P.initialState(); mode = state.phase === "practice" ? "practice" : state.phase === "review" ? "review" : "activity"; activeGraph = state.ti || 0; registerDraft(); return render(); } if (startupState === "review") return restoreFinished(attempt.snapshot, attempt); if (startupState === "frozen") { const payload = attempt.snapshot?.payload; let review = null; try { review = payload?.reviewJson ? JSON.parse(payload.reviewJson) : null; } catch {} const decoded = P.decodeReview(review?.answer); const metadata = { score: payload?.score, maxScore: payload?.maxScore, passed: payload?.passed }; if (!decoded || !U.validResultMetadata(metadata) || !U.validResultMetadata(review)) { window.SimScorm.quarantinePending(); return renderTechnical("technical", "待確認提交資料未能安全驗證，已停止重試。 "); } state = P.reviewToState(decoded); const computed = S.scoreActivity(state.pid, state.ans); if (computed.score !== payload.score || computed.passed !== payload.passed || computed.score !== review.score || computed.passed !== review.passed || review.maxScore !== 100) { window.SimScorm.quarantinePending(); return renderTechnical("technical", "待確認提交與權威答案不符，已停止重試。 "); } pendingExpected = review; renderTechnical("pending"); showPendingRetry(); return; } renderTechnical("technical"); }
  el.startChallenge.addEventListener("click", () => { const pid = Q.choosePaper(); state = P.startTasks(P.initialState(), pid); mode = "activity"; activeGraph = 0; editors = new Map(); reviewNotice = ""; registerDraft(); saveDraft(); render(); }); el.practiceClear.addEventListener("click", () => { const editor = editorFor(0, practiceDefinition); if (editor.clearAll()) render(); });
  el.formulaToggle.addEventListener("click", () => { const hidden = el.formulaCard.classList.toggle("is-hidden"); el.formulaToggle.setAttribute("aria-expanded", String(!hidden)); el.formulaToggle.textContent = hidden ? "顯示公式提示" : "隱藏公式提示"; });
  el.undoButton.addEventListener("click", () => { const editor = editorFor(activeGraph); if (editor.undoOnce()) commitEditor(activeGraph, "已復原上一步。 "); }); el.redoButton.addEventListener("click", () => { const editor = editorFor(activeGraph); if (editor.redoOnce()) commitEditor(activeGraph, "已取消復原。 "); }); el.clearGraphButton.addEventListener("click", () => { const editor = editorFor(activeGraph); if (editor.clearAll()) commitEditor(activeGraph, "已清除這幅圖；可復原。 "); });
  el.nextButton.addEventListener("click", () => { const next = P.nextTask(state); if (!next) return; state = next; if (state.phase === "review") { saveDraft(); mode = "review"; } else { activeGraph = state.ti; mode = "activity"; } registerDraft(); saveDraft(); render(); }); el.submitButton.addEventListener("click", submit); el.retryButton.addEventListener("click", () => { const outcome = window.SimScorm.finish(); if (outcome) el.retryButton.classList.add("is-hidden"); }); el.technicalRetryButton.addEventListener("click", retryPendingSubmission);
  el.stageRegion.addEventListener("pointerdown", (event) => { if (drag && event.pointerId !== drag.pointerId && !event.target.closest(".point-hit")) rollbackActiveDrag(false); }, true);
  el.controlsPanel.addEventListener("pointerdown", (event) => {
    if (!drag || event.pointerId === drag.pointerId) return;
    rollbackActiveDrag(false);
    panelContinuation = { pointerId: event.pointerId, startY: event.clientY, scrollTop: el.controlsPanel.scrollTop };
    el.controlsPanel.setPointerCapture(event.pointerId);
    event.preventDefault();
  }, true);
  el.controlsPanel.addEventListener("pointermove", (event) => {
    if (!panelContinuation || event.pointerId !== panelContinuation.pointerId) return;
    const max = Math.max(0, el.controlsPanel.scrollHeight - el.controlsPanel.clientHeight);
    el.controlsPanel.scrollTop = M.clamp(panelContinuation.scrollTop + panelContinuation.startY - event.clientY, 0, max);
    event.preventDefault();
  });
  const endPanelContinuation = (event) => {
    if (!panelContinuation || event.pointerId !== panelContinuation.pointerId) return;
    panelContinuation = null;
    event.preventDefault();
  };
  el.controlsPanel.addEventListener("pointerup", endPanelContinuation);
  el.controlsPanel.addEventListener("pointercancel", endPanelContinuation);
  el.controlsPanel.addEventListener("lostpointercapture", endPanelContinuation);
  function recomputeLayout() { const viewport = window.visualViewport; const width = viewport?.width || window.innerWidth; const height = viewport?.height || window.innerHeight; el.app.classList.toggle("is-compact", U.usesCompactLayout({ width, height })); }
  window.addEventListener("blur", rollbackActiveDrag); window.addEventListener("resize", recomputeLayout); window.visualViewport?.addEventListener("resize", recomputeLayout); if (window.ResizeObserver) new ResizeObserver(recomputeLayout).observe(el.app); recomputeLayout(); window.__kinematicsQuantitativeDiagnostics = diagnostics;
  window.__kinematicsQuantitativeDebug = {
    diagnostics: () => ({ ...diagnostics }), state: () => state ? JSON.parse(JSON.stringify(state)) : null, mode: () => mode,
    activeGraph: () => activeGraph, editorAnswer: () => editorFor(activeGraph).answer.slice(), editorUndoLength: () => editorFor(activeGraph).undo.length, resultTime: () => resultTime
  };
  startup();
})();
