(function (root, factory) {
  const api = factory(); if (typeof module === "object" && module.exports) module.exports = api; if (root) root.KinematicsQuantitativeNotation = api;
})(typeof window !== "undefined" ? window : globalThis, function () {
  "use strict";
  const escape = (value) => String(value).replace(/[&<>"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[char]));
  const symbols = new Set(["x", "v", "a", "t", "T"]); const units = Object.freeze({ x: "m", v: "m/s", a: "m/s²", t: "s" });
  const variable = (name, sub = "") => `<var>${symbols.has(name) ? name : "?"}</var>${sub === "" ? "" : `<sub class="numeric-subscript">${escape(sub)}</sub>`}`;
  const unit = (type) => `<span class="upright-unit">${units[type] || units.t}</span>`;
  const number = (value) => escape(value);
  const quantity = (value, type) => `<span class="quantity">${number(value)} ${unit(type)}</span>`;
  const graph = (type, label) => `${escape(label)} ${variable(type)}–${variable("t")}`;
  function text(value) { return String(value).split(/([-+]?\d+(?:\.\d+)?\s*至\s*[-+]?\d+(?:\.\d+)?\s*m\/s²|[-+]?\d+(?:\.\d+)?\s*至\s*[-+]?\d+(?:\.\d+)?\s*m\/s|[-+]?\d+(?:\.\d+)?\s*至\s*[-+]?\d+(?:\.\d+)?\s*m|[-+]?\d+(?:\.\d+)?\s*m\/s²|[-+]?\d+(?:\.\d+)?\s*m\/s|[-+]?\d+(?:\.\d+)?\s*m|½at²|v₀|x₀|m\/s²|m\/s|[xvat]–t|[xvatT])/g).map((part) => { const range = part.match(/^([-+]?\d+(?:\.\d+)?)\s*至\s*([-+]?\d+(?:\.\d+)?)\s*(m\/s²|m\/s|m)$/); const measured = part.match(/^([-+]?\d+(?:\.\d+)?)\s*(m\/s²|m\/s|m)$/); const type = (unitText) => unitText === "m" ? "x" : unitText === "m/s" ? "v" : "a"; if (range) return `${quantity(range[1], type(range[3]))} 至 ${quantity(range[2], type(range[3]))}`; if (measured) return quantity(measured[1], type(measured[2])); if (part === "½at²") return `½${variable("a")}${variable("t")}<sup>2</sup>`; if (part === "v₀") return variable("v", "0"); if (part === "x₀") return variable("x", "0"); if (part === "m/s²") return unit("a"); if (part === "m/s") return unit("v"); if (/^[xvat]–t$/.test(part)) return `${variable(part[0])}–${variable("t")}`; if (symbols.has(part)) return variable(part); return escape(part); }).join(""); }
  function prompt(question, index) { const atZero = `${variable("t")}=${quantity(0, "t")} 時位於 ${variable("x")}=${quantity(question.x0, "x")}`; if (index === 0) return `物體在 ${atZero}，其後以固定速度 ${variable("v")}=${quantity(question.v0, "v")} 向正方向運動 ${quantity(question.T, "t")}。建立三幅圖。`; if (index === 1) return `物體在 ${atZero}，並由靜止開始，以固定正加速度 ${variable("a")}=${quantity(question.a, "a")} 運動 ${quantity(question.T, "t")}。建立三幅圖。`; if (index === 2) return `物體在 ${atZero}，已有正初速度 ${variable("v", "0")}=${quantity(question.v0, "v")}，以固定正加速度 ${variable("a")}=${quantity(question.a, "a")} 運動 ${quantity(question.T, "t")}。建立三幅圖。`; return `物體在 ${atZero}，以正初速度 ${variable("v", "0")}=${quantity(question.v0, "v")} 運動，並以固定負加速度 ${variable("a")}=${quantity(question.a, "a")} 勻減速；在 ${quantity(question.T, "t")} 剛好停止，不反向。`; }
  const pointLabel = (index, time) => `P<sub class="numeric-subscript">${number(index)}</sub>，${variable("t")} = ${quantity(time, "t")}`; const dragCoordinate = (index, time, type, value) => `P<sub class="numeric-subscript">${number(index)}</sub>　${variable("t")}=${quantity(time, "t")}；${variable(type)}=${quantity(value, type)}`; const summary = (times, axis, type) => `固定時間：${times.map((time) => quantity(time, "t")).join("、")}；縱軸 ${quantity(axis.min, type)} 至 ${quantity(axis.max, type)}。`;
  const controlsInstruction = (count) => `請拖動線圖下方的${count === 2 ? "兩個" : "三個"}控制點（${Array.from({ length: count }, (_, index) => `P<sub class="numeric-subscript">${index}</sub>`).join("、")}）到正確數值；亦可使用數值欄或 −／＋ 微調。設定後，系統會自動畫出圖線。`;
  return { escape, variable, unit, quantity, graph, prompt, pointLabel, dragCoordinate, summary, controlsInstruction, text };
});
