"use strict";
const assert = require("node:assert/strict"); const Q = require("./question-definitions.js"); const P = require("./persistence.js"); const S = require("./scoring.js");
let state = P.initialState(); assert.equal(P.validateDraft(state), true); state = P.startTasks(state, "A"); assert.equal(state.ti, 0); state = P.setAnswer(state, 0, [0, 20]); assert.deepEqual(state.ans[0], [0, 20]);
state = P.setAnswer(state, 0, [null, null]); assert.equal(state.ans[0], null, "clearing the last point canonicalizes to null"); assert.equal(P.decode(P.encode(state)).ans[0], null, "reload preserves a cleared graph as blank"); state = P.setAnswer(state, 0, [0, 20]);
state = P.switchTask(state, 1); state = P.setAnswer(state, 1, [5, 5]); state = P.switchTask(state, 2); state = P.setAnswer(state, 2, [0, 0]); state = P.nextTask(state); assert.equal(state.ti, 3);
for (let i = 3; i < 12; i += 1) { while (state.ti !== i) state = P.nextTask(state); state = P.setAnswer(state, i, Q.taskDefinition("A", i).targets); }
state = P.nextTask(state); assert.equal(state.phase, "review"); const encoded = P.encode(state); const decoded = P.decode(encoded); assert.deepEqual(decoded, encoded); assert.equal(S.scoreActivity(decoded.pid, decoded.ans).score, 100);
const review = P.makeReview(decoded); assert.deepEqual(P.reviewToState(P.decodeReview(review)).ans, decoded.ans); assert.equal(P.bytes(review) < 1300, true);
const nonCanonicalReviewState = { ...decoded, ans: decoded.ans.slice() }; nonCanonicalReviewState.ans[0] = [null, null]; const canonicalReview = P.makeReview(nonCanonicalReviewState); assert.equal(canonicalReview.ans[0], null, "makeReview canonicalizes all-null graph arrays"); assert.equal(P.decodeReview(canonicalReview).ans[0], null, "canonical makeReview output remains decodable");
const corrupt = { ...encoded, ans: encoded.ans.slice() }; corrupt.ans[0] = [0, 20.5]; assert.equal(P.decode(corrupt), null);
const nonCanonical = { ...encoded, ans: encoded.ans.slice() }; nonCanonical.ans[0] = [null, null]; assert.equal(P.decode(nonCanonical), null, "decoder rejects alternate all-null array encoding");
const practice = P.initialState(); assert.deepEqual(P.decode(P.encode(practice)), practice, "practice round trip");
assert.ok(P.startTasks(P.decode(P.encode(practice)), "A"), "restored practice has its legal start-challenge continuation");
for (const taskIndex of [0, 3, 6, 9]) { let fixture = P.startTasks(P.initialState(), "A"); while (fixture.ti !== taskIndex) fixture = P.nextTask(fixture); const definition = Q.taskDefinition("A", taskIndex); fixture = P.setAnswer(fixture, taskIndex, definition.targets.map((value, index) => index ? null : value)); const restored = P.decode(P.encode(fixture)); assert.ok(restored, `first-pass mission ${taskIndex / 3 + 1} round trip`); assert.equal(S.scoreActivity(restored.pid, restored.ans).score, S.scoreActivity(fixture.pid, fixture.ans).score); assert.ok(P.nextTask(restored), `first-pass mission ${taskIndex / 3 + 1} has legal continuation`); }
const reviewEdit = P.openReviewEdit(decoded, 7); assert.ok(reviewEdit && P.decode(P.encode(reviewEdit)), "review-edit round trip"); assert.equal(P.nextTask(P.decode(P.encode(reviewEdit))).phase, "review", "review-edit continuation returns review");
function firstPassAt(index) { let fixture = P.startTasks(P.initialState(), "A"); const missionStart = Math.floor(index / 3) * 3; while (fixture.ti < missionStart) fixture = P.nextTask(fixture); return fixture.ti === index ? fixture : P.switchTask(fixture, index); }
for (let index = 0; index < 12; index += 1) for (const [variant, answer] of [["null", null], ["partial", Q.taskDefinition("A", index).targets.map((value, point) => point ? null : value)], ["complete", Q.taskDefinition("A", index).targets]]) { const fixture = P.setAnswer(firstPassAt(index), index, answer); const restored = P.decode(P.encode(fixture)); assert.ok(restored, `first-pass active ${index} ${variant} round trip`); assert.equal(S.scoreActivity(restored.pid, restored.ans).score, S.scoreActivity(fixture.pid, fixture.ans).score); assert.equal(S.scoreActivity(restored.pid, restored.ans).passed, S.scoreActivity(fixture.pid, fixture.ans).passed); assert.ok(P.nextTask(restored), `first-pass active ${index} ${variant} continues legally`); }
for (const [variant, reviewState] of [["incomplete", { ...decoded, ans: decoded.ans.map((answer, index) => index === 0 ? null : answer) }], ["ready", decoded]]) { const restored = P.decode(P.encode(reviewState)); assert.ok(restored, `review ${variant} round trip`); assert.equal(S.scoreActivity(restored.pid, restored.ans).score, S.scoreActivity(reviewState.pid, reviewState.ans).score); assert.equal(S.scoreActivity(restored.pid, restored.ans).passed, S.scoreActivity(reviewState.pid, reviewState.ans).passed); assert.ok(P.openReviewEdit(restored, 0), `review ${variant} can legally reopen an editor`); }
for (let index = 0; index < 12; index += 1) for (const [variant, answer] of [["null", null], ["partial", Q.taskDefinition("A", index).targets.map((value, point) => point ? null : value)], ["complete", Q.taskDefinition("A", index).targets]]) { let fixture = P.openReviewEdit(decoded, index); fixture = P.setAnswer(fixture, index, answer); const restored = P.decode(P.encode(fixture)); assert.ok(restored, `review-edit ${index} ${variant} round trip`); assert.equal(S.scoreActivity(restored.pid, restored.ans).score, S.scoreActivity(fixture.pid, fixture.ans).score); assert.equal(S.scoreActivity(restored.pid, restored.ans).passed, S.scoreActivity(fixture.pid, fixture.ans).passed); assert.equal(P.nextTask(restored).phase, "review", `review-edit ${index} ${variant} returns review`); }
for (const mutation of [
  (value) => ({ ...value, v: 2 }), (value) => ({ ...value, qv: 9 }), (value) => ({ ...value, pid: "toString" }),
  (value) => ({ ...value, ti: 99 }), (value) => ({ ...value, mode: "bad" }), (value) => ({ ...value, vm: 7 }),
  (value) => { const next = { ...value, ans: value.ans.slice() }; next.ans[0] = [999, 0]; return next; },
  (value) => { const next = { ...value, ans: value.ans.slice() }; next.ans[0] = [0.5, 0]; return next; }
]) assert.equal(P.decode(mutation(encoded)), null, "invalid state matrix rejects mutation");
const taskFive = firstPassAt(5); for (const mutation of [
  (value) => ({ ...value, vm: value.vm & ~(1 << 0) }), (value) => ({ ...value, vm: value.vm & ~(1 << value.ti) }),
  (value) => ({ ...value, vm: value.vm | (1 << 6) }), (value) => { const next = { ...value, ans: value.ans.slice() }; next.ans[6] = Q.taskDefinition("A", 6).targets; return next; },
  (value) => { const next = { ...value, ans: value.ans.slice() }; next.ans[0] = [-1, null]; return next; }, (value) => { const next = { ...value, ans: value.ans.slice() }; next.ans[value.ti] = [NaN, null]; return next; }, (value) => { const next = { ...value, ans: value.ans.slice() }; next.ans[value.ti] = [Infinity, null]; return next; }
]) assert.equal(P.decode(mutation(taskFive)), null, "task invariant mutation is rejected");
assert.equal(P.decode({ ...encoded, ti: 0 }), null, "review forbids taskIndex field"); assert.equal(P.decode({ ...encoded, mode: "first" }), null, "review forbids mode field");
console.log("Quantitative graph persistence tests passed");
