"use strict";
const assert = require("node:assert/strict"); const Q = require("./question-definitions.js"); const S = require("./scoring.js");
function correct(pid) { return Array.from({ length: 12 }, (_, index) => Q.taskDefinition(pid, index).targets.slice()); }
let result = S.scoreActivity("A", correct("A")); assert.equal(result.score, 100); assert.equal(result.passed, true); assert.deepEqual(result.families, { x: 40, v: 32, a: 28 });
for (let index = 0; index < 12; index += 1) { const definition = Q.taskDefinition("A", index); const graph = S.scoreGraph(definition, definition.targets); assert.equal(graph.score, graph.maxScore, `task ${index} full component total`); graph.components.forEach((part) => { const answer = definition.targets.slice(); answer[part.index] = null; assert.equal(graph.maxScore - S.scoreGraph(definition, answer).score, part.points, `task ${index} point ${part.index} has documented weight ${part.points}`); }); }
assert.deepEqual(result.missions, [25, 25, 25, 25]); for (let mission = 0; mission < 4; mission += 1) { const answers = correct("A"); answers[mission * 3] = null; answers[mission * 3 + 1] = null; answers[mission * 3 + 2] = [Q.taskDefinition("A", mission * 3 + 2).targets[0], null]; result = S.scoreActivity("A", answers); assert.equal(result.missions[mission], 3.5, `Mission ${mission + 1} nearest reachable score below 10 is 3.5`); assert.equal(result.gates.missions, false); }
for (let mission = 0; mission < 4; mission += 1) { const answers = Array(12).fill(null); const index = mission * 3; answers[index] = Q.taskDefinition("A", index).targets.slice(); result = S.scoreActivity("A", answers); assert.equal(result.missions[mission], 10, `Mission ${mission + 1} 10-point floor is exact`); assert.ok(result.missions[mission] >= 10); answers[index][0] = null; result = S.scoreActivity("A", answers); assert.ok(result.missions[mission] < 10, `Mission ${mission + 1} nearest reachable point removal is below the floor`); }
const partial = correct("A"); partial[9][0] = 1; result = S.scoreActivity("A", partial); assert.equal(result.score, 97); assert.equal(result.gates.decelerationComplete, false); assert.equal(result.passed, false);
const empty = S.scoreActivity("A", Array(12).fill(null)); assert.equal(empty.score, 0); assert.equal(empty.passed, false);
const diagnostic = correct("A"); diagnostic[5] = [1, 2]; assert.match(S.crossDiagnostic("A", diagnostic, 1), /加速度隨時間改變/);
const half = correct("A"); half[0] = [0, 20]; half[3] = [0, 4, 16]; half[6] = [2, 8, 18]; half[9] = [0, 12, 16]; for (const i of [1,2,4,5,7,8,10,11]) half[i] = [999]; result = S.scoreActivity("A", half); assert.equal(result.families.x, 40); assert.equal(result.score, 40); assert.equal(result.passed, false);
for (const [index, point] of [[0, 0], [1, 0], [2, 0], [11, 0]]) { const answers = correct("A"); const target = answers[index][point]; answers[index][point] = target + 1; assert.ok(S.scoreActivity("A", answers).score < 100, `adjacent snap cell is rejected for task ${index}`); }
for (const [index, point] of [[5, 0], [8, 1]]) { const answers = correct("A"); answers[index][point] += 1; assert.ok(S.scoreActivity("A", answers).score < 100, `adjacent positive-a snap cell is rejected for task ${index}`); }
const midpointDefinition = Q.taskDefinition("A", 3); const midpointOnly = S.feedbackFor(midpointDefinition, S.scoreGraph(midpointDefinition, [0, 5, 16])); assert.ok(midpointOnly.some((message) => /中間控制點/.test(message))); assert.ok(midpointOnly.every((message) => !message.includes("½")), "[0,5,16] has only generic midpoint evidence");
const halfOmitted = S.feedbackFor(midpointDefinition, S.scoreGraph(midpointDefinition, [0, 5, 17])); assert.ok(halfOmitted.some((message) => message.includes("½at²")), "midpoint plus endpoint evidence can diagnose omitted ½");
for (const answer of [[0, 3, 15], [0, 5, 15]]) assert.ok(S.feedbackFor(midpointDefinition, S.scoreGraph(midpointDefinition, answer)).every((message) => !message.includes("½at²")), `${JSON.stringify(answer)} lacks the directional omitted-½ evidence`);
const threshold = correct("A"); threshold[0] = [0, 20]; threshold[3] = [0, 4, 16]; threshold[6] = [2, 8, 18]; threshold[9] = [0, 12, 16]; for (const index of [1,2,4,5,7,8,10,11]) threshold[index] = [null, null]; result = S.scoreActivity("A", threshold); assert.equal(result.score, 40); assert.equal(result.gates.x, true); assert.equal(result.passed, false, "representative and family gates cannot be bypassed");
const missionFailure = correct("A"); missionFailure[9] = null; assert.equal(S.scoreActivity("A", missionFailure).gates.decelerationComplete, false); assert.equal(S.scoreActivity("A", missionFailure).passed, false);
const seventy = Array(12).fill(null); seventy[0] = correct("A")[0]; seventy[3] = correct("A")[3]; seventy[4] = correct("A")[4]; seventy[5] = correct("A")[5]; seventy[6] = correct("A")[6]; seventy[9] = correct("A")[9]; seventy[10] = correct("A")[10]; seventy[11] = correct("A")[11]; result = S.scoreActivity("A", seventy); assert.equal(result.score, 70); assert.equal(result.passed, true, "reachable 70 fixture passes every mastery gate");
const sixtyNinePointFive = seventy.map((answer) => answer && answer.slice()); sixtyNinePointFive[2] = [0, null]; sixtyNinePointFive[10][0] = null; result = S.scoreActivity("A", sixtyNinePointFive); assert.equal(result.score, 69.5); assert.equal(result.passed, false, "69.5 does not round up to pass");
const xFloor = correct("A"); for (const index of [0, 3, 6, 9]) xFloor[index] = null; xFloor[0] = [0, 20]; xFloor[3] = [0, 4, 16]; result = S.scoreActivity("A", xFloor); assert.equal(result.families.x, 20, "x-family floor is exactly reachable"); assert.equal(result.gates.x, true); xFloor[3][2] = null; result = S.scoreActivity("A", xFloor); assert.equal(result.families.x, 16, "nearest reachable x-family score below floor is 16"); assert.equal(result.gates.x, false);
const vFloor = correct("A"); for (const index of [1, 4, 7, 10]) vFloor[index] = null; vFloor[1] = correct("A")[1]; vFloor[4] = correct("A")[4]; result = S.scoreActivity("A", vFloor); assert.equal(result.families.v, 16, "v-family floor is exactly reachable"); assert.equal(result.gates.v, true); vFloor[4][0] = null; result = S.scoreActivity("A", vFloor); assert.equal(result.families.v, 12, "nearest reachable v-family score below floor is 12"); assert.equal(result.gates.v, false);
const aFloor = correct("A"); for (const index of [2, 5, 8, 11]) aFloor[index] = null; aFloor[2] = correct("A")[2]; aFloor[5] = correct("A")[5]; result = S.scoreActivity("A", aFloor); assert.equal(result.families.a, 14, "a-family floor is exactly reachable"); assert.equal(result.gates.a, true); aFloor[5][0] = null; result = S.scoreActivity("A", aFloor); assert.equal(result.families.a, 10.5, "nearest reachable a-family score below floor is 10.5"); assert.equal(result.gates.a, false);
const positiveRepresentative = correct("A"); positiveRepresentative[3] = null; assert.equal(S.scoreActivity("A", positiveRepresentative).gates.positiveComplete, true, "Mission 3 is a complete positive-acceleration representative"); positiveRepresentative[6][0] = null; assert.equal(S.scoreActivity("A", positiveRepresentative).gates.positiveComplete, false, "missing one Mission 3 point closes positive representative gate");
console.log("Quantitative graph scoring tests passed");
