#!/usr/bin/env node
"use strict";

const path = require("path");
const { spawnSync } = require("child_process");

const root = path.resolve(__dirname, "..");
const tests = [
  "sim/fbd-horizontal-block/scoring.test.js",
  "sim/plane-mirror-pencil-ray-diagram/scoring.test.js",
  "sim/plane-mirror-pencil-ray-diagram/draft-save.test.js",
  "sim/displacement-distance-map-journey/scoring.test.js",
  "sim/displacement-distance-map-journey/route-coverage.test.js",
  "sim/displacement-distance-map-journey/map-persistence.test.js",
  "sim/inertial-reference-frame-road-observer/scoring.test.js",
  "sim/inertial-reference-frame-road-observer/animation.test.js",
  "sim/position-time-graph-motion-lab/scoring.test.js",
  "sim/position-time-graph-motion-lab/generator.test.js",
  "sim/position-time-graph-motion-lab/persistence.test.js",
  "sim/position-time-graph-motion-lab/lifecycle.test.js",
  "sim/position-time-graph-motion-lab/ui-runtime.test.js",
  "sim/position-time-graph-motion-lab/production-wiring.test.js",
  "sim/position-time-graph-motion-lab/pending-final.test.js",
  "tools/position-time-browser-regression.test.js",
  "sim/linear-motion-velocity-lab/motion-model.test.js",
  "sim/linear-motion-velocity-lab/scene-visuals.test.js",
  "sim/linear-motion-velocity-lab/scoring.test.js",
  "sim/linear-motion-velocity-lab/persistence.test.js",
  "sim/linear-motion-velocity-lab/accessibility.test.js",
  "sim/linear-motion-velocity-lab/ui-runtime.test.js",
  "sim/kinematics-driving-challenge/driving-model.test.js",
  "sim/kinematics-driving-challenge/level-definitions.test.js",
  "sim/kinematics-driving-challenge/scoring.test.js",
  "sim/kinematics-driving-challenge/persistence.test.js",
  "sim/kinematics-driving-challenge/scene-visuals.test.js",
  "sim/kinematics-driving-challenge/ui-runtime.test.js",
  "sim/kinematics-driving-challenge/accessibility.test.js",
  "sim/kinematics-qualitative-graph-sketching/task-definitions.test.js",
  "sim/kinematics-qualitative-graph-sketching/notation.test.js",
  "sim/kinematics-qualitative-graph-sketching/graph-model.test.js",
  "sim/kinematics-qualitative-graph-sketching/graph-analysis.test.js",
  "sim/kinematics-qualitative-graph-sketching/scoring.test.js",
  "sim/kinematics-qualitative-graph-sketching/persistence.test.js",
  "sim/kinematics-qualitative-graph-sketching/ui-runtime.test.js",
  "sim/kinematics-qualitative-graph-sketching/accessibility.test.js",
  "tools/kinematics-qualitative-graph-browser-regression.js",
  "sim/kinematics-quantitative-graph-builder/question-definitions.test.js",
  "sim/kinematics-quantitative-graph-builder/notation.test.js",
  "sim/kinematics-quantitative-graph-builder/graph-model.test.js",
  "sim/kinematics-quantitative-graph-builder/scoring.test.js",
  "sim/kinematics-quantitative-graph-builder/persistence.test.js",
  "sim/kinematics-quantitative-graph-builder/ui-runtime.test.js",
  "sim/kinematics-quantitative-graph-builder/accessibility.test.js",
  "tools/kinematics-quantitative-graph-browser-regression.js",
  "sim/free-fall-stroboscopic-measurement-lab/model.test.js",
  "sim/free-fall-stroboscopic-measurement-lab/animation.test.js",
  "sim/free-fall-stroboscopic-measurement-lab/scoring.test.js",
  "sim/free-fall-stroboscopic-measurement-lab/persistence.test.js",
  "sim/free-fall-stroboscopic-measurement-lab/persistence-matrix.test.js",
  "sim/free-fall-stroboscopic-measurement-lab/ui-runtime.test.js",
  "sim/free-fall-stroboscopic-measurement-lab/lifecycle.test.js",
  "sim/free-fall-stroboscopic-measurement-lab/accessibility.test.js",
  "tools/free-fall-stroboscopic-browser-regression.js",
  "sim/centre-of-mass-investigation-lab/generator.test.js",
  "sim/centre-of-mass-investigation-lab/model.test.js",
  "sim/centre-of-mass-investigation-lab/scoring.test.js",
  "sim/centre-of-mass-investigation-lab/persistence.test.js",
  "sim/centre-of-mass-investigation-lab/lifecycle.test.js",
  "sim/centre-of-mass-investigation-lab/ui-runtime.test.js",
  "sim/centre-of-mass-investigation-lab/accessibility.test.js",
  "sim/hookes-law-spring-investigation-lab/generator.test.js",
  "sim/hookes-law-spring-investigation-lab/model.test.js",
  "sim/hookes-law-spring-investigation-lab/animation.test.js",
  "sim/hookes-law-spring-investigation-lab/scoring.test.js",
  "sim/hookes-law-spring-investigation-lab/persistence.test.js",
  "sim/hookes-law-spring-investigation-lab/lifecycle.test.js",
  "sim/hookes-law-spring-investigation-lab/accessibility.test.js",
  "sim/hookes-law-spring-investigation-lab/ui-runtime.test.js",
  "sim/hookes-law-spring-investigation-lab/delayed-feedback.test.js",
  "sim/hookes-law-spring-investigation-lab/touch-contract.test.js",
  "sim/hookes-law-spring-investigation-lab/pending-final.test.js",
  "tools/hookes-law-spring-browser-regression.test.js",
  "sim/static-kinetic-friction-investigation-lab/generator.test.js",
  "sim/static-kinetic-friction-investigation-lab/physics.test.js",
  "sim/static-kinetic-friction-investigation-lab/measurement.test.js",
  "sim/static-kinetic-friction-investigation-lab/graph-analysis.test.js",
  "sim/static-kinetic-friction-investigation-lab/scoring.test.js",
  "sim/static-kinetic-friction-investigation-lab/persistence.test.js",
  "sim/static-kinetic-friction-investigation-lab/lifecycle.test.js",
  "sim/static-kinetic-friction-investigation-lab/delayed-feedback.test.js",
  "sim/static-kinetic-friction-investigation-lab/accessibility.test.js",
  "sim/static-kinetic-friction-investigation-lab/production-wiring.test.js",
  "tools/static-kinetic-friction-browser-regression.js",
  "sim/force-composition-construction-lab/generator.test.js",
  "sim/force-composition-construction-lab/notation.test.js",
  "sim/force-composition-construction-lab/model.test.js",
  "sim/force-composition-construction-lab/scoring.test.js",
  "sim/force-composition-construction-lab/persistence.test.js",
  "sim/force-composition-construction-lab/lifecycle.test.js",
  "sim/force-composition-construction-lab/ui-runtime.test.js",
  "sim/force-composition-construction-lab/accessibility.test.js",
  "tools/force-composition-browser-regression.test.js",
  "tools/centre-of-mass-browser-regression.js",
  "tools/mobile-touch-scroll.test.js",
  "sim/shared/scorm.test.js",
  "sim/shared/activity-flow.test.js"
];

for (const test of tests) {
  const result = spawnSync(process.execPath, [path.join(root, test)], { stdio: "inherit" });
  if (result.status !== 0) process.exit(result.status || 1);
}
